### ISSUE TITLE
Fix "Column name platform.*.* is invalid" error message in Refine 

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#100]
In Refine there is an error message that reads: "Column name platform._._ is invalid. Allowed types for this column are "Host", "Unknown." This error appears even when there is no column named Platform, which is confusing. I'm not really sure what this is supposed to indicate. (Spreadsheet ref no. 10)

**Comment by sosguthorpe** [comment]
This is basically telling you the name of your column is not allowed. So platform.host.name is fine but platform.test.name is not as "test" isn't allowed here.

platform unknown.name would also be fine.

It's also worth noting that the error message has been changed and the message doesn't appear for me with a column just named "platform" is there a specific project you can point me at that I can look at?

**Comment by kristenwilson** [comment]
I created a new project called Sage: Test for Steve: 140804 that shows this error.

This project doesn't have any columns that include the word "platform" at all. So I'm not sure which column is causing this error to be generated. If I create a properly named column like "platform.host.url," this error will go away, even if I do not edit any of the existing columns.
