### ISSUE TITLE
Preserve data being typed into a field while still on the same page

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#104]
When you are typing in a field, then accidentally click out of it without saving, your data is lost. Can it still be there when you go back as long as you don't navigate off the page? (Spreadsheet ref no. 20)

**Comment by sosguthorpe** [comment]
Am scheduling this in for the next milestone although this might change depending on the complexity of a fix for this.

**Comment by sosguthorpe** [comment]
Moved to 3.5 milestone as I think it's a little too involved to complete for this release.

**Comment by kristenwilson** [comment]
That's alright with me.

**Comment by kristenwilson** [comment]
Are we still going to try to do this?

**Comment by jhsolomon** [comment]
This does not work for the Published From and Published To date fields, but it does work for other text.
