### ISSUE TITLE
Alphabetize search results by default

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#105]
Search results should be alphabetized by default in all cases. (Spreadsheet ref no. 21)

**Comment by sosguthorpe** [comment]
I believe there was an unanswered query regarding this.

Search results are ordered by relevance by default. Isn't this more desirable than alpha sorting everything?

**Comment by kristenwilson** [comment]
Sorry, this was a confusing description on my part. I meant that the list of records you see before searching should be alphabetized. So if you go to Search>Packages, you will see this screen: https://test-gokb.kuali.org/gokb/search/index?qbe=g%3Apackages

Right now, I believe this list is displaying in the order that records were created in the system. It should be A-Z. Once a user performs a search, then I think relevance is the way to go.

**Comment by ianibo** [comment]
Actually, orgs are sorted, but I think if you look at the records at the top of the list in the screenshot, in the database they have a space character at the start - and hence are sorting high. Closing.
