### ISSUE TITLE
Fix the display of empty identifier records

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#109]
Fix the display of "empty" identifier components so they don't look like an error. (Spreadsheet ref no. 27)

**Comment by sosguthorpe** [comment]
I'm not entirely sure what this means. Please can you supply an example URI for me to look at.

**Comment by kristenwilson** [comment]
Sure. Here's where you see the empty label in the display: https://test-gokb.kuali.org/gokb/search/index?qbe=g%3Acomponents

And if I click on one of the empty records, I just see this: https://test-gokb.kuali.org/gokb/resource/show/org.gokb.cred.Identifier%3A2

From a user perspective, these records look like errors. If these are real identifier records, can they display some meaningful info about the identifiers they represent?
