### ISSUE TITLE
Actions don't work when all review tasks are selected

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#114]
If all the check boxes on a page of review tasks are selected, you won't be able to choose any of the actions. If I uncheck one, then the actions become available again. (Spreadsheet ref no. 35)

**Comment by kristenwilson** [comment]
Tested this and I'm now finding that the error still persists. Additionally, now when I select some chec boxes and try to perform an action, it doesn't work at all. (E.g., select multiple tasks and choose the close action, tasks are not closed.)

**Comment by sosguthorpe** [comment]
Can you please try a shift refresh as it seems to work fine for me here. Maybe the javascript has been cached by your browser.

**Comment by kristenwilson** [comment]
I tried a shift refresh, but am still seeing the same result. I also tried clearing the cache using Firefox options and trying it in Google Chrome -- some problem each time.

**Comment by kristenwilson** [comment]
So I realized what's happening here. I've been testing this with the "open" filter applied. So when I close the review tasks, they are immediately removed from the display and replaced with the next ones in the list. And since I've been looking at whole pages that contain nothing but identical tasks, it looks like nothing is happening. So this actually is working. And the multiple checkbox select is working too. So I would say the bug part of this is fixed. It might be helpful to add some kind of display message at the top that says "successfully closed 25 review tasks" or similar.

Sorry for the confusion!

**Comment by kristenwilson** [comment]
Confirmed fixed
