### ISSUE TITLE
Issues with creating a source

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#117]
When I click on the "Create" dropdown menu, there is no longer an option to create a new source. This is happening for admin and regular users -- need to clarify whether this is an admin function. Also, I was able to get to the "create source" page by modifying the URL of another create page, which could also be a problem. (Spreadsheet ref no. 40)

**Comment by sosguthorpe** [comment]
Can you please confirm whether this is still a problem? I can see it on the menu. It might be that the admin group does not have the necessary permission to create a source? You'll need to configure the permissions on the system.

**Comment by kristenwilson** [comment]
Confirmed that this is fixed.
