### ISSUE TITLE
Fix review task that says "Package was created without a provider."

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#121]
I got a review tasking saying "Package was created without a provider." However, the provide was there. (Spreadsheet ref no. 8)

**Comment by sosguthorpe** [comment]
Does this happen every time? Could it be that the data was corrected but the task wasn't closed?

**Comment by kristenwilson** [comment]
It seems to be. I loaded a package into Kuali Test on Tuesday (7/22) that
created this review task:
https://test-gokb.kuali.org/gokb/resource/show/org.gokb.cred.ReviewRequest%3A518

However, if you look at the package record, you'll see that the provider is
there. OpenRefine requires you to select a provider before ingesting data,
so I don't think it would be possible to create a package without one
unless you were doing it by hand.

On Thu, Jul 24, 2014 at 6:42 AM, sosguthorpe notifications@github.com
wrote:

> Does this happen every time? Could it be that the data was corrected but
> the task wasn't closed?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/k-int/gokb-phase1/issues/121#issuecomment-49992757.

## 

Kristen Wilson
Associate Head, Acquisitions and Discovery
GOKb Editor
North Carolina State University Libraries
919-513-3354
kristen_wilson@ncsu.edu

**Comment by kristenwilson** [comment]
I think I know why this is happening. You can create a package on the fly in OpenRefine by using the package look-up menu and choosing to generate a new one. However, at this point, you haven't yet ingested your data, so no provider has been uploaded -- and a review tasks is created. Once you ingest your data, the provider is populated. However, it's really unlikely that you would look at your review tasks after you've created a package through Refine, but before you finish ingesting your data. So this appears as an error, even though its technically not. Would it be possible to hold off on generating review tasks for a package until after the Refine ingest is complete?

**Comment by sosguthorpe** [comment]
The problem here is that the system has no idea that the user might ingest later on. There could be a long time period between the package creation and the ingest, so how can we differentiate between a package with no provider and a package waiting for an ingest to set the provider.

Maybe we run a nightly procedure to set some of these review requests instead of on-save. We could then say set this review request if a package had existed in the system for X days and still didn't have a provider. It's not going to be something that there is a quick fix for, as I think we do need the request for review here.

**Comment by ostephens** [comment]
I generally like the idea of creating review requests based on an overnight procedure - this would open up the possibility of creating review requests for other types of issue. As an example creating review requests for situations where TIPP start/end dates conflict with Title History and Title Publication start/end dates.

**Comment by kristenwilson** [comment]
I like that idea too. In the meantime, I think this is OK to keep as is. I will just make sure my documentation reflects the behavior of this error, so people know what it expect.

**Comment by sosguthorpe** [comment]
Think that this is something we can plan for 3.5 however it will be lower priority for now.

**Comment by jhsolomon** [comment]
This is still not working. I tested it and it took a long time for the errors to show up in my to-do list, so I missed it earlier.  We will need to retest.

**Comment by kristenwilson** [comment]
I think that these error messages are still being generated as described when the issue was originally submitted. It does not appear that any kind of nightly clean-up is taking place as Steve had described above. I created a package in Refine and saw a review task generated immediately: https://gokb.k-int.com/gokb/resource/show/org.gokb.cred.ReviewRequest%3A5121.

**Comment by jhsolomon** [comment]
I am still getting this error message.

**Comment by sosguthorpe** [comment]
2 issues at work here. The quick create function was not physically linking the provider with the package. And the review request is always raised by the quickCreate action. I have changed this so the quick create now links the provider if one was supplied and the review request now checks for this before being raised. This should mean using the new 2 step creation function in refine should mean no review request but if we use this functionality somewhere else (the old clients still connecting to the test server for instance) then the provider will not be set and there will be a review request.

**Comment by kristenwilson** [comment]
The two-step creation function actually works out really well to solve this problem. Most packages are initially created through Refine, so this should take care of the issue in many cases.
