### ISSUE TITLE
Using 'Organisation Lookup' in Refine shows the Organisation multiple times in list

### ISSUE THREAD

**Issue by ostephens** [k-int/gokb-phase1#122]
Each organisation in the lookup seems to appear once per variant name. In Screenshot shows how Routledge (Firm) is appearing multiple times

![screen shot 2014-07-09 at 13 48 25](https://cloud.githubusercontent.com/assets/576174/3524399/8836847c-0767-11e4-96ba-3cc49d678691.png)

**Comment by kristenwilson** [comment]
Confirmed fixed
