### ISSUE TITLE
Arising from SME session - (1) before / after displays to be wider; (2) date control on event date that works for all browsers; (3) hard deletion for TH event

### ISSUE THREAD

**Issue by ianibo** [k-int/gokb-phase1#127]
Displays wide
Need info about what browsers the standard date control is failing on
Hard Delete.. Pending... 3.5

**Comment by sosguthorpe** [comment]
Issue #160 deals with the date control.

**Comment by iyawnis** [comment]
@kristenwilson  For title history, should only hard deleting be available (for everyone)  OR should hard delete only be available to admins, and current delete mechanism (set status deleted) available for rest ?

**Comment by iyawnis** [comment]
Deleting Title History events from the database has been done since #101 . Is something else expected?

**Comment by kristenwilson** [comment]
No, I think all of this has been done for a while. I will close it.
