### ISSUE TITLE
Grails error encountered when viewing a Title

### ISSUE THREAD

**Issue by iamcreative** [k-int/gokb-phase1#132]
Logged in as user 'admin', password 'admin'
When this user clicks to view a title they encounter a grails error for some of them. E.g.  
https://test-gokb.kuali.org/gokb/resource/show/org.gokb.cred.TitleInstance%3A5902 and https://test-gokb.kuali.org/gokb/resource/show/org.gokb.cred.TitleInstance%3A5909

(This title works fine though: https://test-gokb.kuali.org/gokb/resource/show/org.gokb.cred.TitleInstance%3A5913)

Text of Grails error for /org.gokb.cred.TitleInstance%3A5902:
"Error 500: Internal Server Error
URI
/gokb/resource/show/org.gokb.cred.TitleInstance%3A5902
Class
java.lang.NullPointerException
Message
Cannot invoke method getClassName() on null object
Trace
    Line | Method
->>  530 | doFilter  in /resource/show.gsp

---

Caused by GrailsTagException: Error executing tag <g:render>: Cannot invoke method getClassName() on null object
->>   27 | doCall    in /WEB-INF/grails-app/views/resource/show.gsp
- \- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - "

**Comment by ianibo** [comment]
gokb.k-int.com/gokb

?

On 7 August 2014 10:54, iamcreative notifications@github.com wrote:

> Logged in as user 'admin', password 'admin'
> When this user clicks to view a title they encounter a grails error for
> some of them. E.g.
> 
> https://test-gokb.kuali.org/gokb/resource/show/org.gokb.cred.TitleInstance%3A5902
> and
> https://test-gokb.kuali.org/gokb/resource/show/org.gokb.cred.TitleInstance%3A5909
> 
> (This title works fine though:
> https://test-gokb.kuali.org/gokb/resource/show/org.gokb.cred.TitleInstance%3A5913
> )
> 
> Text of Grails error for /org.gokb.cred.TitleInstance%3A5902:
> "Error 500: Internal Server Error
> URI
> /gokb/resource/show/org.gokb.cred.TitleInstance%3A5902
> Class
> java.lang.NullPointerException
> Message
> Cannot invoke method getClassName() on null object
> Trace
> Line | Method
> 
> ## ->> 530 | doFilter in /resource/show.gsp
> 
> Caused by GrailsTagException: Error executing tag : Cannot invoke method
> getClassName() on null object
> ->> 27 | doCall in /WEB-INF/grails-app/views/resource/show.gsp
> 
> ---
> - "
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/k-int/gokb-phase1/issues/132.

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo
GoodReads: https://www.goodreads.com/user/show/3106516-ian-ibbotson

**Comment by ianibo** [comment]
(WHich is to say - I thought we were testing on the k-int machine and NOT
the kuali one)

On 7 August 2014 10:54, iamcreative notifications@github.com wrote:

> Logged in as user 'admin', password 'admin'
> When this user clicks to view a title they encounter a grails error for
> some of them. E.g.
> 
> https://test-gokb.kuali.org/gokb/resource/show/org.gokb.cred.TitleInstance%3A5902
> and
> https://test-gokb.kuali.org/gokb/resource/show/org.gokb.cred.TitleInstance%3A5909
> 
> (This title works fine though:
> https://test-gokb.kuali.org/gokb/resource/show/org.gokb.cred.TitleInstance%3A5913
> )
> 
> Text of Grails error for /org.gokb.cred.TitleInstance%3A5902:
> "Error 500: Internal Server Error
> URI
> /gokb/resource/show/org.gokb.cred.TitleInstance%3A5902
> Class
> java.lang.NullPointerException
> Message
> Cannot invoke method getClassName() on null object
> Trace
> Line | Method
> 
> ## ->> 530 | doFilter in /resource/show.gsp
> 
> Caused by GrailsTagException: Error executing tag : Cannot invoke method
> getClassName() on null object
> ->> 27 | doCall in /WEB-INF/grails-app/views/resource/show.gsp
> 
> ---
> - "
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/k-int/gokb-phase1/issues/132.

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo
GoodReads: https://www.goodreads.com/user/show/3106516-ian-ibbotson

**Comment by ianibo** [comment]
Can you add in the URL of the search page where you clicked the link to
this title please - this title doesn't appear to be in the db - which is
why there is an error.

On 7 August 2014 10:54, iamcreative notifications@github.com wrote:

> Logged in as user 'admin', password 'admin'
> When this user clicks to view a title they encounter a grails error for
> some of them. E.g.
> 
> https://test-gokb.kuali.org/gokb/resource/show/org.gokb.cred.TitleInstance%3A5902
> and
> https://test-gokb.kuali.org/gokb/resource/show/org.gokb.cred.TitleInstance%3A5909
> 
> (This title works fine though:
> https://test-gokb.kuali.org/gokb/resource/show/org.gokb.cred.TitleInstance%3A5913
> )
> 
> Text of Grails error for /org.gokb.cred.TitleInstance%3A5902:
> "Error 500: Internal Server Error
> URI
> /gokb/resource/show/org.gokb.cred.TitleInstance%3A5902
> Class
> java.lang.NullPointerException
> Message
> Cannot invoke method getClassName() on null object
> Trace
> Line | Method
> 
> ## ->> 530 | doFilter in /resource/show.gsp
> 
> Caused by GrailsTagException: Error executing tag : Cannot invoke method
> getClassName() on null object
> ->> 27 | doCall in /WEB-INF/grails-app/views/resource/show.gsp
> 
> ---
> - "
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/k-int/gokb-phase1/issues/132.

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo
GoodReads: https://www.goodreads.com/user/show/3106516-ian-ibbotson

**Comment by iamcreative** [comment]
Ah yes, I've just realised I'm testing on the wrong machine ... what a spanner!

Here is the link just in case you want to look at it: https://test-gokb.kuali.org/gokb/search/index?qbe=g%3Atitles but it's probably more a case of deleting this issue and pretending you never saw it ... apols for the time wasting!
