### ISSUE TITLE
Create New Record screens are (mostly) read only

### ISSUE THREAD

**Issue by iamcreative** [k-int/gokb-phase1#133]
When logged in as user 'hharrop' the following Create screens appear to be read only/uneditable:
http://gokb.k-int.com/gokb/create/index?tmpl=org.gokb.cred.License
http://gokb.k-int.com/gokb/create/index?tmpl=org.gokb.cred.Office
http://gokb.k-int.com/gokb/create/index?tmpl=org.gokb.cred.Org
http://gokb.k-int.com/gokb/create/index?tmpl=org.gokb.cred.Package
http://gokb.k-int.com/gokb/create/index?tmpl=org.gokb.cred.Platform
http://gokb.k-int.com/gokb/create/index?tmpl=org.gokb.cred.ReviewRequest
http://gokb.k-int.com/gokb/create/index?tmpl=org.gokb.cred.Source
http://gokb.k-int.com/gokb/create/index?tmpl=org.gokb.cred.Imprint

When logged in as user 'admin' the .Org and .Package screens _are_ editable but the rest plus these additional Create screens are uneditable:
http://gokb.k-int.com/gokb/create/index?tmpl=org.gokb.cred.AdditionalPropertyDefinition
http://gokb.k-int.com/gokb/create/index?tmpl=org.gokb.cred.RefdataCategory
http://gokb.k-int.com/gokb/create/index?tmpl=org.gokb.cred.Territory

**Comment by ianibbo** [comment]
Heya.. Yes, your user needs the right roles allocating now - which means
the first step in the testing procedure needs to be to log on as admin and
set the permissions on the various domains that you want.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ianibbo** [comment]
Permissions are set by logging on as admin at

http://gokb.k-int.com/gokb/search/index?qbe=g%3Adomains

for example, to have standard users able to edit licenses go to

http://gokb.k-int.com/gokb/resource/show/org.gokb.cred.KBDomainInfo%3A13

and click on the tick on the [appropriate - for example] ROLE_USER and
ROLE_EDITOR rows for the  READ, WRITE, DELETE and ADMIN columns.

Suggest this step be added to the testing script as it's a critical
requirement of GOKb.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com
