### ISSUE TITLE
Searching for '*' in the Global Search results in a Grails Runtime Exception

### ISSUE THREAD

**Issue by iamcreative** [k-int/gokb-phase1#134]
Logged in as 'hharrop' (password: test.hharrop)

When the user enters '_' in the Global Search and attempts to execute the search a Grails Runtime Exception error is returned.
Search URL: http://gokb.k-int.com/gokb/globalSearch/index
Search execution URL: http://gokb.k-int.com/gokb/globalSearch/index?q=_&submit=

Error text:
"Error 500: Internal Server Error
URI
/gokb/globalSearch/index
Class
org.elasticsearch.indices.IndexMissingException
Message
[gokb] missing
Trace
Line | Method
->>  771 | convertFromWildcards in org.elasticsearch.cluster.metadata.MetaData

---

|    659 | concreteIndices      in     ''
|    109 | <init> . . . . . . . in org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction
|     68 | <init>               in org.elasticsearch.action.search.type.TransportSearchQueryThenFetchAction$AsyncAction
|     62 | <init> . . . . . . . in     ''
|     59 | doExecute            in org.elasticsearch.action.search.type.TransportSearchQueryThenFetchAction
|     49 | doExecute . . . . .  in     ''
|     63 | execute              in org.elasticsearch.action.support.TransportAction
|    108 | doExecute . . . . .  in org.elasticsearch.action.search.TransportSearchAction
|     43 | doExecute            in     ''
|     63 | execute . . . . . .  in org.elasticsearch.action.support.TransportAction
|     92 | execute              in org.elasticsearch.client.node.NodeClient
|    212 | search . . . . . . . in org.elasticsearch.client.support.AbstractClient
|    330 | search               in org.elasticsearch.groovy.client.GClient
|    325 | search . . . . . . . in     ''
|     29 | index                in org.gokb.GlobalSearchController
|    195 | doFilter . . . . . . in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter             in grails.plugin.cache.web.filter.AbstractFilter
|   1145 | runWorker . . . . .  in java.util.concurrent.ThreadPoolExecutor
|    615 | run                  in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run . . . . . . . .  in java.lang.Thread"

**Comment by ianibo** [comment]
No longer throws exception - not pretty tho.
