### ISSUE TITLE
User able to edit elements of a read only Title record

### ISSUE THREAD

**Issue by iamcreative** [k-int/gokb-phase1#135]
User hharrop (password: test.hharrop) is able to delete entries in the 'Title History' table and can also delete and make authorized entries in the 'Alternate Titles' table - even though none of the other fields are editable and the record is clearly labelled as '(Read Only)' in the browser title bar. 

The same user can add titles on the 'Add to Title History' tab and attempt to delete an item from the Namespace table on the Identifiers tab but then encounters a Grails errors:
a) When they click 'Add Title History Event ->': "Error 500: Internal Server Error
URI
/gokb/resource/show/org.gokb.cred.TitleInstance:5913
Class
java.lang.NullPointerException
Message
null
Trace
    Line | Method
->>  530 | doFilter  in /resource/show.gsp

---

Caused by GrailsTagException: Error executing tag <g:render>: null
->>   29 | doCall    in /WEB-INF/grails-app/views/resource/show.gsp"

b) When they click 'Yes' on an attempted Identifier deletion: "Error 500: Internal Server Error
URI
/gokb/resource/show/org.gokb.cred.TitleInstance:5913
Class
java.lang.NullPointerException
Message
null
Trace
    Line | Method
->>  530 | doFilter  in /resource/show.gsp

---

Caused by GrailsTagException: Error executing tag <g:render>: null
->>   29 | doCall    in /WEB-INF/grails-app/views/resource/show.gsp
- \- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - "

Example record: http://gokb.k-int.com/gokb/resource/show/org.gokb.cred.TitleInstance%3A5913

Domain settings for Title Instance (I think this is the right one!): http://gokb.k-int.com/gokb/resource/show/org.gokb.cred.KBDomainInfo%3A33

**Comment by ianibo** [comment]
Ok.. For clarity - is this an issue that is tested against a specific
requirement, or a feature request arising from new testing?

On 7 August 2014 15:50, iamcreative notifications@github.com wrote:

> User hharrop (password: test.hharrop) is able to delete entries in the
> 'Title History' table and can also delete and make authorized entries in
> the 'Alternate Titles' table - even though none of the other fields are
> editable and the record is clearly labelled as '(Read Only)' in the browser
> title bar.
> 
> The same user can add titles on the 'Add to Title History' tab and attempt
> to delete an item from the Namespace table on the Identifiers tab but then
> encounters a Grails errors:
> a) When they click 'Add Title History Event ->': "Error 500: Internal
> Server Error
> URI
> /gokb/resource/show/org.gokb.cred.TitleInstance:5913
> Class
> java.lang.NullPointerException
> Message
> null
> Trace
> Line | Method
> 
> ## ->> 530 | doFilter in /resource/show.gsp
> 
> Caused by GrailsTagException: Error executing tag : null
> ->> 29 | doCall in /WEB-INF/grails-app/views/resource/show.gsp"
> 
> b) When they click 'Yes' on an attempted Identifier deletion: "Error 500:
> Internal Server Error
> URI
> /gokb/resource/show/org.gokb.cred.TitleInstance:5913
> Class
> java.lang.NullPointerException
> Message
> null
> Trace
> Line | Method
> 
> ## ->> 530 | doFilter in /resource/show.gsp
> 
> Caused by GrailsTagException: Error executing tag : null
> ->> 29 | doCall in /WEB-INF/grails-app/views/resource/show.gsp
> 
> ---
> - "
> 
> Example record:
> http://gokb.k-int.com/gokb/resource/show/org.gokb.cred.TitleInstance%3A5913
> 
> Domain settings for Title Instance (I think this is the right one!):
> http://gokb.k-int.com/gokb/resource/show/org.gokb.cred.KBDomainInfo%3A33
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/k-int/gokb-phase1/issues/135.

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo
GoodReads: https://www.goodreads.com/user/show/3106516-ian-ibbotson

**Comment by iamcreative** [comment]
Neither I think :) I've just raised it because I spotted it in the course of testing - I could be wrong but my expectation is that if a component is set up as 'Read Only' in the associated domain screen then none of the elements of that component should be editable by a user? It looked like a permissions bug to me.

**Comment by ianibbo** [comment]
There was a vague requirement - we've done something for 3.0.1. if what
we've done meets the requirement, but you feel it needs to go further -
then thats cool - but we need to record it as a feature request against 3.5
rather than a bug against 3.0.1 - we've done our best to estimate based on
the requirements - if every issue is going to creep in scope like this then
we all look bad, so I'd just rather find a way of logging things that don't
work, and things that need to do even more.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com
