### ISSUE TITLE
Add yearly browse to calendar widget

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#136]
Modify the calendar select feature on fields such as Access End Date to move forward and back by 12 month increments in addition to individual months. This would be especially helpful, since most of the dates we're dealing with are not within the current calendar year.

**Comment by sosguthorpe** [comment]
Bootstrap 3 currently has no calendar widget for the editable fields library. The calendar widget that was seen was part of the browser and therefor we have no control over this. I have moved to a 3 dropdown format of selecting a date for now (see #160) so we can keep consistency across the various browsers. Will keep this issue open for now as a reference point.

**Comment by sosguthorpe** [comment]
Have added a masked input box to force the users to input correctly formatted dates.

**Comment by kristenwilson** [comment]
No longer needed since we have changed the date input method.
