### ISSUE TITLE
Don’t allow use of right-click look up feature if user is not in a live field

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#139]
In Refine, if a user right-clicks anywhere in the interface, they will see a grayed-out version of the look up feature. Testers are finding this confusing b/c they sometime forget to first hit the "edit" button for a cell. They right-click and see the grayed-out menu, then assume their permissions are not set correctly. Can we make it so that the right-click menu is only accessible if the user is editing a live field?

**Comment by sosguthorpe** [comment]
This is going to be a difficult one. The menu is like that as it currently only has 1 item in the menu. The menu is already contextual in that it disabbles anything the user can not do in the area they have currently clicked, but as there is currenlty only 1 menu item I can see how it can be confusing. I'll have a think.

**Comment by sosguthorpe** [comment]
I'll take a look at this, for this release and see if there are any improvements we can make.

**Comment by sosguthorpe** [comment]
Unfortunately the context menu plugin will not allow us to not show the menu after the click has been actioned, so there isn't anything I can do here.

**Comment by kristenwilson** [comment]
OK, we can address this with training. I'll close this issue and remove it from 4.1.1.
