### ISSUE TITLE
Change field ti.identifier.{namespace} to title.identifier.{namespace}

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#145]
Title is identified as both ti and title within database field names. In the identifiers it is ti.identifier.{namespace} while in custom fields it is gokb.title.{fieldname}. It may be more convenient and easy to remember if it is always either ti or title. Testers suggest that title is more eye-readable.

**Comment by sosguthorpe** [comment]
Thinking this is probably pretty straight forward to change. Flagging as a quick fix.
