### ISSUE TITLE
Permissions not working for "create"

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#146]
The permissions that would block a user from creating records are not working correctly. I have a test account that I have assigned permissions to be able to read and edit certain record types (orgs, sources) but not create them. However, when I log in as this user, I am still allowed to create those records. If I change this user's permissions so that it can only read these record types (not edit or create), then I am also blocked from creating them. A fix for this needs to be in place before we can allow people to start working in production.

**Comment by ianibbo** [comment]
Have added the necessary code to check the perms - but need to double check
with steve about some meta class stuff that seems to be preventing it
working properly.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com
