### ISSUE TITLE
Title transfer action feedback

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#147]
The following all relate to the title transfer action, but should also be applied to the title name change action.
- If you click "Abandon transfer" or "process transfer" you are taken back to the GOKb homepage. Can this take you back to the title record where you originally started from instead?
- It's not entirely clear what the "select" check box is meant to do. It seems like its main function is that when it's checked and I choose "add transfer TIPPs," TIPPs will only be added for the ones that are checked. But after the new TIPPs appear, the "select" box reverts to checked again. Does this have any other effect? Should we label this differently? Maybe call it "Add transfer TIPP"?
- If I uncheck the "close" or "review" check boxes before I click "add transfer TIPPs," they will revert to checked after I click "add transfer TIPPs." This field should remember the user's selection.
- If you add a transfer TIPP to the action screen (i.e., where it shows up in green but hasn't yet been approved), there's no way to remove it without abandoning the whole transfer and starting over. Maybe there could be a "remove" button for each new TIPP the user is reviewing so that they can make changes throughout the  process.
- The top-level checkbox above the "select" field controls checkboxes in the "select," "close," and "review fields." I think these need to operate independently.
- When I processed a title transfer action, it automatically retired all of the associated TIPPs, even for the ones where I unchecked the "close" field on the transfer screen. I'm actually not  sure if "close" means "retire the TIPP" or if it means "close the coverage statement." We probably need more clear labeling on this. Also, if it doesn't mean "retire the TIPP," is there a place where I can choose whether or not to retire each TIPP?
- No review tasks were created when I processed a transfer, regardless of whether the "review" box was checked.
- When I'm looking at the list of new and current TIPPs and choosing whether to close them, etc., I'd also like to be able to edit the start/end coverage fields, since they may not all be the same.

**Comment by ianibo** [comment]
This issue is a bit of a problem because it's really several issues. Have resolved some and created a screencast to discuss the others here: http://youtu.be/AK4mIj4Fm4U . Am closing this issue now, please create atomic, actionable issues for anything thats still outstanding.
