### ISSUE TITLE
Org record is not showing associations with titles and TIPPs

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#148]
The Org record in GOKb is not showing associated titles and TIPPs. Sage is a good example: https://test-gokb.kuali.org/gokb/resource/show/org.gokb.cred.Org%3A1681

If you look at the packages tab, you'll see there are a large number of packages associated with this org. But if you look at the titles and TIPPs tabs, there are only a couple things actually showing up here.

**Comment by ianibo** [comment]
Heya.. This is done explicitly through the publisher on individual title records, rather than implicitly through tipp package relationships. I _think_ that only the titles currently listed have a publisher set? Whats the best way forward on this?

**Comment by ostephens** [comment]
Just to note that this is the only way (afaik) to access a list of titles published by a specific org at the moment, so if we change the way this listing works, I think we'd need consideration of how you'd get a list of published titles rather than 'provided' titles.

But that said I don't have strong feelings on whether this list should be 'Published Titles' (could re-label tab to make this clear?) or 'Titles in Packages where this Org is the Provider'

**Comment by kristenwilson** [comment]
I would prefer to keep this limited to titles published by a specific org.
I wasn't intending to ask that we change the way this is done. I just
missed the connection between the fact that import of publishers through
Refine has been broken, leading to no publishers displaying here. I like
the idea of relabeling the tab "Published titles."

On Tue, Sep 2, 2014 at 10:02 AM, Owen Stephens notifications@github.com
wrote:

> Just to note that this is the only way (afaik) to access a list of titles
> published by a specific org at the moment, so if we change the way this
> listing works, I think we'd need consideration of how you'd get a list of
> published titles rather than 'provided' titles.
> 
> But that said I don't have strong feelings on whether this list should be
> 'Published Titles' (could re-label tab to make this clear?) or 'Titles in
> Packages where this Org is the Provider'
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/k-int/gokb-phase1/issues/148#issuecomment-54155544.

## 

Kristen Wilson
Associate Head, Acquisitions and Discovery
GOKb Editor
North Carolina State University Libraries
919-513-3354
kristen_wilson@ncsu.edu
