### ISSUE TITLE
Invalid Host URL should report pattern being used to check for valid URL

### ISSUE THREAD

**Issue by ianibo** [k-int/gokb-phase1#149]
Trying to import the clean GSA from the testdata folder reports invalid URLs, but I can't see why they are invalid. Adding the pattern to the error text is a real help to users trying to figure out why a URL is invalid.

**Comment by sosguthorpe** [comment]
Agreed. Although, I think wee need to come up with a more sentence like description to describe it as outputting the REGEX won't mean much to regular users.

**Comment by kristenwilson** [comment]
Decided this was not needed in Refine. Will document on wiki.
