### ISSUE TITLE
GOKb refine extension reported to not behave on Mac

### ISSUE THREAD

**Issue by sosguthorpe** [k-int/gokb-phase1#15]
Users have reported refine extension doesn't work on mac.

**Comment by sosguthorpe** [comment]
Tested on a Mac in office and it worked fine specs below:

OSX 10.8.4
Java Version 7_19 and 1.6.0_51
Safari Version 6.0.5

**Comment by sosguthorpe** [comment]
Assigning to OS to retry the current extension download.

**Comment by sosguthorpe** [comment]
Screen shot showing how to get console window to show when running java app in OSX. You just need to run the correct file from within the refine folder (Contents/MacOS/javaApplicationStub).

![running refine on mac with console](https://f.cloud.github.com/assets/2544187/948027/41d7301a-035f-11e3-8285-64a1765827ec.png)

**Comment by ostephens** [comment]
Confirmed working for me on Mac 10.8.4
Looks like previous version of extension gave a javascript error "ReferenceError: \u00D4\u00AA\u00F8 is not defined" which may have been cause of problem?

**Comment by ostephens** [comment]
Happy to see this closed if you are happy
