### ISSUE TITLE
OpenRefine sometimes times out

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#151]
When preforming an action in OpenRefine, the client occasionally times out. When this happens, the user will just see the "Working" dialogue and spinning wheel indefinitely (longest recorded time around 10 min.). If you refresh the page in your web browser, you will return to your project in Refine and the last action you were trying to preform will be completed. From my experience, this seems to happen most commonly during delete actions.

**Comment by sosguthorpe** [comment]
This would suggest that the timeouts set in the tool are not having an effect. Will need to investigate this more.

**Comment by ianibo** [comment]
Closing now as new timeouts in force. If timeouts recur, please open a new issue with all information.
