### ISSUE TITLE
Can't access TIPP from the TI record

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#152]
If you try to access a TIPP record using the link on the Availability tab of the Title Instance record, you will get an error that says:

Create New Component
Unable to find record in database : Please notify support

If you try to access a TIPP by searching, it will come up without a problem. I think this is a bug that occurred with 3.0.1 and should be fixed before we push that release out to production.

**Comment by ianibo** [comment]
Heya Kristen - Can you add a URL of one that fails please (Or do all of them fail?) Cheers,e

**Comment by ianibo** [comment]
Looks like the class is a proxy - link ends up as https://test-gokb.kuali.org/gokb/resource/show/org.gokb.cred.KBComponent_%24%24_javassist_24%3A37777

@sosguthorpe can you check out pls?

**Comment by ianibo** [comment]
Hey Steve - Did one of the metamethods that I removed deal with deproxying? Anyway - I added a slightly hacky explicit deproxy call to the template for now. CLosing this issue.

**Comment by sosguthorpe** [comment]
Heyup,

Should still be on all k_int domain objects. Just call getClassName() instead.

Will take a quick look.

**Comment by kristenwilson** [comment]
Confirmed fixed.
