### ISSUE TITLE
Remove 'TIPPs' tab from Org display

### ISSUE THREAD

**Issue by ostephens** [k-int/gokb-phase1#153]
See also #148 for related discussion.

The org display (e.g. https://test-gokb.kuali.org/gokb/resource/show/org.gokb.cred.Org%3A1681) currently has a tab labelled 'Tipps'.

This should be removed (Tipps related to a org as either package provider or title publisher can be accessed via the Tipps search)

**Comment by sosguthorpe** [comment]
Should we therefore think about maybe adding 2 links to this display that takes the user to the search page?
i.e.
Search for TIPPs provided by x
Search for TIPPs published by x

Maybe the wider use of a "Related Search" list on all applicable components (not just orgs) might be a good idea?
