### ISSUE TITLE
Search option on Title search should be labelled 'Publisher' not 'Content Provider'

### ISSUE THREAD

**Issue by ostephens** [k-int/gokb-phase1#154]
The Title search screen (https://test-gokb.kuali.org/gokb/search/index?qbe=g%3Atitles) has two search inputs labelled "Name or Title" and "Content Provider"

The Content Provider box currently accepts an Org ID, but retrieves items linked by a 'Publisher' org relationship rather than Content Provider relationship. This behaviour is probably the correct behaviour (i.e. search by Title/Publisher the correct search), so the 'Content Provider' search box should be re-labelled to Publisher.

Ideally the Publisher search box should support a 'Search for' dropdown/type ahead box rather than requiring the user to know the Org ID

**Comment by ianibbo** [comment]
I think this search is used in one of the full details screens (The input
form is hidden) so we need to be a bit careful when changing it.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
To clarify I think the behaviour is correct. The search created from this search form is like:
https://gokb.k-int.com/gokb/search/index?qbe=g%3Atitles&qp_name=test&qp_prov_id=143

(and as you point out there is an equivalent search from the Org display -> Titles tab of https://gokb.k-int.com/gokb/search/index?qbe=g%3Atitles&hide=qp_prov_id&qp_name=test&qp_prov_id=143)

As far as I can see these searches do not find titles 'provided' by org 143 (i.e. content provider role via package), but find titles 'published' by org 143 (Org role of publisher in relation to title). This is the correct outcome.

Hope that makes sense

**Comment by ianibo** [comment]
Hidden controller - used for navigation in other contexts.

**Comment by kristenwilson** [comment]
Confirmed for now, but opened #256 to revisit title search options in a future release.
