### ISSUE TITLE
Ignore punctuation in CRED searches

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#155]
Users have reported that they would find it easier to search n the CRED interface if punctuation is ignored.

**Comment by ianibo** [comment]
Have added a normalise function to utils, and this is callable from search templates. Implemented on Package Name search to start with. Can't do this everywhere, so need definitive list of search forms that want normalised name searching.

**Comment by kristenwilson** [comment]
Verified this is working for package search only at this point.
