### ISSUE TITLE
Hide deleted components in CRED

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#164]
This was an issue that was supposed to be fixed in an earlier release, but I can't find it in Github. Components with a deleted status should be hidden by default in the CRED. There should be a option to show these components as part of the search interface.

**Comment by ianibo** [comment]
Closing this here - Titles, Orgs and some other components  now have a dropdown to control the visibility of deleted items. This fix can be applied anywhere, but there is no way to globally make the change. Please log specific issues for each search where you want to have deleted components hidden.
