### ISSUE TITLE
Actions don't apply to seleted items across multiple pages

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#166]
If I select all the items on a page (e.g., review tasks), I get an option to select all items across pages. If I do this, I see a message that says all items are selected. If I then try to apply an action to all items (e.g., close review tasks), the action will only apply to the current page. The action should apply to all selected tasks across pages.

**Comment by ianibo** [comment]
This is a bit of a feature and needs some hefty thought - for example when/how do you clear the existing checks and decide that you're starting from nothing again.

**Comment by ianibo** [comment]
Have emailed K with questions

**Comment by ianibo** [comment]
It's not feasible in 4.0 to do this (And as a request, it doesn't really fit with current web idioms), but what we have done is to implement the multi-state select all, so - hitting the select all checkbox now causes text to appear asking the user if they wish to select all pages. Doing so will cause the subsequent screen to list all rows selected by the query. Users will have to use search criteria to narrow the selection of rows to be actioned (We can add more criteria). But the ability to individually select every row (For example, every tipp) is going to break the form requests on most browsers, and is therefore not really practical. Could use a call to discuss if this is OK.
