### ISSUE TITLE
StartDate/EndDate not displaying correctly on Package search

### ISSUE THREAD

**Issue by ostephens** [k-int/gokb-phase1#171]
e.g. http://test.kbplus.ac.uk/kbplus/packageDetails/index?offset=0&pkgname=the&sorting=sortname&order=desc&search=yes

Instead of dates is displaying "hit.source.startDate" and "hit.source.endDate"

![screen shot 2014-09-19 at 11 17 01](https://cloud.githubusercontent.com/assets/576174/4333867/2b7df0c8-3fe6-11e4-8137-f885e558acf3.png)

Not sure if this is application or service issue?

**Comment by iyawnis** [comment]
Fixed in KBPlus commit 6298e26286aea0dde1d1dbede9d638467b441560
