### ISSUE TITLE
Notes in review tasks do not save

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#175]
When I try to add a note to a review task, it does not save. I can open up the notes screen and type in a note. When I click "Add," the notes screen just closes. When I open it back up, my note has note saved.

**Comment by kristenwilson** [comment]
Notes are still not saving.

**Comment by kristenwilson** [comment]
This is a bug so I'm putting into 4.1.1 -- hope that is OK.

**Comment by sosguthorpe** [comment]
This seems to be saving fine now so will close once merged into release.
