### ISSUE TITLE
Create title change action

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#177]
This is a Title History event that ripples through with option to defer to 'To Dos'. This release will only deal with name changes in this release - other scenarios might be built on this basis if appropriate.

Action should:
- close out publication dates for earlier title(s)
- create later title(s) with starting publication date
- propagate TIPP changes and new TIPP(s) across all packages that contain the earlier title(s). 
- handle all title change scenarios (e.g., splits, mergers).

Action should be consistent with title transfer action where possible, and should take into account all feedback found on issue #147.

**Comment by kristenwilson** [comment]
See use cases document: Dropbox\GOKb\Dev Phase 3 R3.5 planning\Supporting documentation\140630 Title change use cases and actions

**Comment by ianibo** [comment]
Can we clean up the description a bit? Starts off by saying we are only doing title name change but then says handle all scenarios. Also, do we assume the titles already exist and this is an operation to implement the change (Think we have to) - Need a call about this monday (urgent) as there seem to be lots of detail to fill in.
