### ISSUE TITLE
Add variant name functionality to Platform record

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#179]

**Comment by iyawnis** [comment]
@kristenwilson  Should this be added as a new tab within Platform view, same as Organization, or within the existing Platform Details tab, same as Title/Tipp ?

**Comment by kristenwilson** [comment]
I think a separate tab is easier to read. Thanks!

**Comment by iyawnis** [comment]
While I am at it, you prefer tabs for Title/Tipp alternative names, or these should be left as they are?

**Comment by kristenwilson** [comment]
Let's move it so that they're all consistent.

**Comment by kristenwilson** [comment]
The variant name functionality is now present on the Title, Platform, and Package records. However, I've noticed a bug on all three. If you create a new variant name and click "make authorized," it will be set as the authorized name. But if you click "Make authorized" again once you've done it the first time, the functionality no longer works.

Here's a Platform record with a few alternate names for testing: https://gokb.k-int.com/gokb/resource/show/org.gokb.cred.Platform%3A37778
