### ISSUE TITLE
Sort mechanism for all list columns

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#189]
Uniformly implement sortable column headings across all lists of components (in search results and on tabbed display within records)

**Comment by iyawnis** [comment]
Adding sortable columns was not possible for TIPPs, due to the structure of this component.

**Comment by iyawnis** [comment]
Is sorting by name enough, or it is required for every column of search results ?

**Comment by kristenwilson** [comment]
Name is most important, but eventually I would like to see sorting on all columns.

**Comment by kristenwilson** [comment]
Confirmed that Name/Title columns for components are now sortable. Will we do the other columns in this release or should I open a separate ticket?

**Comment by iyawnis** [comment]
I will add it for all columns

**Comment by iyawnis** [comment]
I believe the only sort missing is nominal platform for packages. Please open a separate issue if this is a must, as it requires code changes.

**Comment by kristenwilson** [comment]
I think we can let the nominal platform go for now.
