### ISSUE TITLE
Title history improvements

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#190]
1.  The label “Current publisher” doesn’t make sense for earlier titles in a title history. These titles are not currently published, so there is no current publisher. Suggest field label change to “Latest publisher.” 
2.  In title history table display, visually highlight the cells that represent the title currently being viewed. 
3.  When adding a title history, allow search by ISSN.
4.  Add ability to manually add a publisher to the Title record.
5.  Add ability to see a comprehensive title history for the entire title family that includes both title changes and publisher changes as separate events. This could be shown as a pop-up or a link to a separate page (I’m open to UI suggestions here).
6. Consideration of consuming KB+ TH Notes as structured GOKB TH Events

**Comment by ianibo** [comment]
This is a massive compound issue - please break down into individual actionable issues

**Comment by kristenwilson** [comment]
#1-4 from list above are done. #255 and #248 will address remaining issues, which are not essential for release 4.0.
