### ISSUE TITLE
Replace platform confirmation message

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#191]
When a user has performed a ‘Replace Platform’ action on an individual Platform record, they are taken to a ‘Platform replacement result’ screen; this should show information about how many TIPP records will be and then have been amended and what will happen in terms of Platform Status

**Comment by iyawnis** [comment]
@kristenwilson What you mean about 'what will happen in terms of Platform Status'? Currently, the status of the platforms is not affected in any way.

**Comment by iyawnis** [comment]
I just reviewed the code and the old platform status is set to deleted. Is this the desired behaviour ?

**Comment by kristenwilson** [comment]
Yes, it is correct the the old platform be set to deleted. Here is some more specific text for the Replace Platform action.

Screen 1:
1. Change header so it says "Replace the following platforms"
2. In grid, change "Packages" head to "Platforms."
3. Underneath the grid and the select menu add a note that says:
This action will:
- Replace the platform for all TIPPs currently associated with the [Name of old platform]
- Set the status of [Name of old platform] to "Retired."
  ![platform1](https://cloud.githubusercontent.com/assets/7397776/5744945/fd7ccfaa-9bf2-11e4-98c1-d76deb5dbd8e.png)

Screen 2:
Add a message that says: [Number] of TIPPs have successfully been updated to platform [Name of new platform]. The platform [Name of old platform] has been retired.

![platform2](https://cloud.githubusercontent.com/assets/7397776/5745123/625cb4c0-9bf4-11e4-9337-c6ebcc3e8fa2.png)

**Comment by iyawnis** [comment]
![scrn1](https://cloud.githubusercontent.com/assets/2336352/5756379/dd21484e-9ca6-11e4-880d-c755584280da.png)
![screenshot from 2015-01-15 11 04 22](https://cloud.githubusercontent.com/assets/2336352/5756378/dd20be6a-9ca6-11e4-8045-e9943ac731a6.png)

**Comment by kristenwilson** [comment]
This looks great. Thanks!

**Comment by kristenwilson** [comment]
In testing this, I noticed that while the message says that the selected platforms will be retired, they are actually deleted. I think retired is the more appropriate action. Can we change this?

**Comment by iyawnis** [comment]
Sorry for this kristen. The deleted status behaviour has not changed during these changes, this is what always happened. If there is a 'retired' status category, you want me to use that ?

**Comment by iyawnis** [comment]
Right, I can see now there is a Retired status. Again this is different behaviour from what was done until now, should I change it ?

**Comment by kristenwilson** [comment]
Yes, I think using the retired status is the better choice. Thanks for changing it.
