### ISSUE TITLE
Platform attributes and combos

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#194]
Platforms needs to be more richly described in terms of Types, Combos, date ranges, etc. Note detailed KB+ Focus Group feedback.  Cover implications in Refine, CRED and API. Owen to propose an approach by 7-Sep

**Comment by ianibo** [comment]
Hey Kristen - is there any additional detail you can attach to this issue?

**Comment by kristenwilson** [comment]
This came from the original backlog spreadsheet that we transferred into Github. I'm not sure if Owen had specific thoughts about the platform record that he was planning on documenting or if he was just going to review what was there. It sounds like there was some feedback from KB+.

Just taking a quick look, I don't think there is a huge demand for adding to the platform record right now. The only gap I see is that the org record has a tab for platforms but there is no way to actually make a connection between the two. It might be nice to get that in.

**Comment by ostephens** [comment]
In terms of KB+ feedback the list below is things we've been asked for in KB+ in relation to platforms which might also apply to GOKb (i.e. excluding things like 'store local username/passwords').
- Authentication method(s) supported
  - Shibboleth
  - IP
  - Username/password
- Does the platform carry a hosting fee?
- Accessibility information
  - Browser compatibility
  - DDA compliance (I guess the US equivalent would be Section 508 and ADA compliance)
  - Which mobile platforms are supported
- Platform uptime stats
- Support information
  - Technical support website
  - Technical support phone
- Usage statistics information
  - Link to usage stats area
  - SUSHI details
-  Link to Library administration area for platform
- Customisation options
  - information about applying branding (e.g. logo size)
  - link resolver options

**Comment by ostephens** [comment]
I'm not keen to add properties we aren't going to use, so if there is no desire to extend the Platform properties right now, then I'm happy with that.

However that said I would really recommend that the way we record Authentication information for the Platform is not adequate in that it allows only one value when it is extremely common for platforms to support multiple Authentication methods - so I'd recommend this is either a repeatable property, or broken out into a yes/no property for each authentication type (so IP: y/n; Shibboleth: y/n; Username/Password: y/n)

**Comment by ianibo** [comment]
Do we know what the use case is for having the availability of the auth methods? Trying to decide what the best approach is, but its hard to visualise exactly how this knowledge will be used - For example, knowing that a service supports un/pw auth isn't much use unless you know the un/pw. Slightly different for IP/Shib, but not totally. Yes/No properties for each are easier, but there may be per-method properties needed - like ip range(s), shib institution, ?

**Comment by ostephens** [comment]
The way I understand the usecase for this at the GOKb level is that if you were looking at options for buying access to a title, you might want to know the platform capabilities before you bought. So you might have a policy of not supporting platforms that don't support Shib.

For this usecase a simple y/n would seem to be appropriate.

I guess I can imagine something slightly more involved in terms of having additional information about Shib config, or which Access Management Federations are supported - but I haven't seen any requests for this level of detail.

At the KB+ level there is definitely the desire to record 'local' information - such as un/pw as you suggest - but I've not included requests like this in the list above as I've assumed any local information like this to be out of scope for GOKb

@kristenwilson do you have a view on whether the 'Authentication' field is helpful at all at the moment? If it isn't needed at all then maybe the immediate solution would be to not use/display it and only tackle the question I've raised here when there is more demand/capacity for this data.

**Comment by ianibbo** [comment]
Fab - have added Y/N fields for now and will extend/revise as more
requirements surface.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by iyawnis** [comment]
Any further action expected for 4.1?

**Comment by ianibbo** [comment]
Nope  - I suggest closing the issue and adding a comment asking for
definitive/specific changes and additions to be added as new issues.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by iyawnis** [comment]
I will assume silence is consent. As Ian suggested, any further work relating to this issue should be detailed in a new issue.
