### ISSUE TITLE
Co-Ref service - Submit & Consume

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#197]
Making the service read / write - In order to gain traction this needs to be dome with specific use cases / users (e.g. Publishers or KBs) in mind - use JUSP & OLE use cases for Titles. A further use case to consider is ISSN-L (see download in dropbox)

**Comment by ianibo** [comment]
Question: how do we know when we can close this issue?

**Comment by kristenwilson** [comment]
Per call on 10/17, add links to wiki documentation and JUSP use case to co-referencing service page in CRED.
