### ISSUE TITLE
Ingested status not showing correctly in Refine

### ISSUE THREAD

**Issue by ostephens** [k-int/gokb-phase1#2]
After a file has been ingested, Refine does not always seem to indicate correctly that this is the case. This is not directly after ingest, but looking at the ingest status of projects that may have been ingested at some point in the past.

E.g. package http://gokb.k-int.com/gokb/resource/show/org.gokb.cred.Package%3A5928 successfully ingested from project http://gokb.k-int.com/gokb/resource/show/org.gokb.refine.RefineProject%3A5922 I think. However in my Refine display I see 

![screen shot 2013-06-06 at 08 51 27](https://f.cloud.github.com/assets/576174/616823/426c868a-ce7e-11e2-8ccb-ca32516b396d.png)

Which does not show project (Highwire:Duke:6-5-2013) as 'Ingested'

**Comment by sosguthorpe** [comment]
This needs improving with a status label. Currently ingested is set if the process got to 100%. I.e. Finished ingesting. If an error occurs then this is never reached and instead says "checked in". We need some proper error reporting on this screen too.

**Comment by sosguthorpe** [comment]
Should now be fixed.
