### ISSUE TITLE
Package name control

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#205]
Controlling Package names – perhaps a two box process to create a new package name.
Idea was that we give users more guidance on naming conventions.

Box 1: Org Name (Choose from Controlled list)
Box 2: Package name

**Comment by iyawnis** [comment]
Which screens is this affecting? The only way I currently see for setting a package name is through the Alternative Names tab.

**Comment by kristenwilson** [comment]
This was originally intended for Refine. When you search for a package using the look-up tool, you have the option to create a new package from that screen. We want to enforce the construction of a package name in the following format:

{Authorized Org Name}: {Package Name}

It would make sense to have this on the alternate names tab for packages as well.

**Comment by iyawnis** [comment]
Is there any format/validation expected for the Box2, which will take the package name ?

**Comment by kristenwilson** [comment]
No, that one has no enforceable format.
