### ISSUE TITLE
Manage list of projects in Refine

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#207]
Sort/filter projects by name, provider, status; delete projects; filter or divide projects between tabs (my projects, completed projects, all projects). Propose filtered list rather than tabs; could include user name, number times processed, last date.

**Comment by sosguthorpe** [comment]
So not all the above is going to be provided in this release but certainly tabs for "My Projects" and "All" will be provided with the possibility of filters within those tabs for existing columns. What constitutes a "complete" project? Is this just one that has been ingested at some point? Because projects can be re-ingested with corrections made so is that really complete?

**Comment by kristenwilson** [comment]
I think the features you've listed will go a long way toward making this
screen more usable.

As for "complete," it is hard to say exactly when that might occur. Would
it be possible to have an "archived" tab instead, and give users the option
to manually archive things that are part of their "my projects" group?

On Fri, Jan 9, 2015 at 7:52 AM, sosguthorpe notifications@github.com
wrote:

> So not all the above is going to be provided in this release but certainly
> tabs for "My Projects" and "All" will be provided with the possibility of
> filters within those tabs for existing columns. What constitutes a
> "complete" project? Is this just one that has been ingested at some point?
> Because projects can be re-ingested with corrections made so is that really
> complete?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/k-int/gokb-phase1/issues/207#issuecomment-69330443.

## 

Kristen Wilson
Associate Head, Acquisitions and Discovery
GOKb Editor
North Carolina State University Libraries
919-513-3354
kristen_wilson@ncsu.edu

**Comment by kristenwilson** [comment]
I know this is not closed yet, but just wanted to say it looks great. I think our SMEs will be very happy with the changes. One small suggestion if there's still time to slip it in -- would it be possible to default the sort order so that the most recent project displays first? A few people noted that would be their preference. Thanks!

**Comment by sosguthorpe** [comment]
I have made the "modified" column sortable and also set it to be the default.

**Comment by kristenwilson** [comment]
Confirmed that all is working as expected.

The one piece of outstanding functionality here is the ability to archive projects. Should I open a separate issue for that?

**Comment by sosguthorpe** [comment]
Yes I think this should be a new issue now. This round of coding was 
mainly about displaying the data that we had rather than allowing for 2 
way communication from this screen.

**Comment by kristenwilson** [comment]
Opened #394 to cover archiving issue.
