### ISSUE TITLE
Simplify OA fields and allow upload through Refine

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#211]
Create a single TI-level attribute for OA. Values should be: Yes, No, Hybrid, Delayed, Unknown. Remove TIPP-level attributes for delayed and hybrid OA.

Users should be able to upload new attribute through Refine.

**Comment by ianibo** [comment]
Have added properties as requested and removed tipp level properties. Do we really want this bouncing around from refine tho? Massive potential for this value to be bounced around with every import.. seems dangerous.

**Comment by ianibo** [comment]
Steve: Have added "oa" property to TitleInstance and linked through to TitleInstance.OAStatus RefdataCategory (With values defined above). Can you add the relevant bit of code to IngestService to grab title.oastatus (?) from refine and set this value as appropriate. Ta.

**Comment by ianibo** [comment]
Use Full OA and No OA

**Comment by kristenwilson** [comment]
In the CRED, the title.oastatus field is a refdata category and I have the ability to edit the possible values for the field. However, when I try to populate this field using a refine upload and the available values as defined in the CRED, I get an error message that says:

One or more rows contain invalid values in the column "title.oastatus".Allowed values are "Yes", "No", "Hybrid", "Delayed", "Unknown". Values are not case sensitive.

So Refine is forcing me to enter values that contradict the available choices in the CRED. Can this be reconciled? If possible, I'd prefer to use the values assigned in the CRED.

**Comment by kristenwilson** [comment]
This is still a problem. See screencast demo: http://screencast.com/t/LaX7ydemvJvu

**Comment by kristenwilson** [comment]
This is still not working correctly. There two issues:
1. Refine now tells me that the accepted values for this field are Full OA, No OA, and Unknown. However, in the CRED, there are two additional values -- Hybrid OA and Delayed OA. Since this is a ref data category and these values could conceivably change, it would be best if Refine could base it's validation on what's actually allowed in the CRED at the time the project is being updated. If that's not possible and the values need to be hard coded into Refine, then we'll need to add the two additional values. We'll also need to remember to update them whenever we update the ref data in the CRED.
2. If I use one of the three values that Refine accepts, I can successfully ingest the project, but the OA value on the TI record is not updated.

**Comment by sosguthorpe** [comment]
While number 1 is possible and; in deed, preferable; I think it falls out of scope for this round of fixes. If I get time to squeeze it in before a full release then I will, but for now this falls under the tag of an enhancement. I have created #301 to track that.

I am looking into number 2.
