### ISSUE TITLE
Package & Platform look-up to include variant name 

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#214]
Variant name to work as per Variant Org
(Note that on spreadsheet, this also said that these look ups should have a "quick create" feature. There is already a "create" feature for packages. I don't think we should have this for platforms in Refine.)

**Comment by sosguthorpe** [comment]
Checked the Refine modula code and the variantName is searched on for Package and platform. Now that the UI has a method to add these this functionality should just start working.
