### ISSUE TITLE
Permissions to cover Refine imports

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#215]
CRED permissions interface to grant individual users permission to create and ingest projects via Refine.Add Refine User Roles for (a) create project and (b) ingest package

**Comment by sosguthorpe** [comment]
I believe we originally agreed to add a single user role that can do both of the above in refine rather than have separate permissions for create project and ingest (see #131). Can we please confirm which is the desired behaviour?

**Comment by ianibo** [comment]
Steve: We agreed signle user role, yes. Role added in bootstrap, and perms on api methods change to require ROLE_REFINEUSER. you might want to test for this when user logs in through refine I guess.. NOt sure what effect this will have on refine client - so please give it a thorough test.

**Comment by kristenwilson** [comment]
This works well. If you log into Refine but don't have permissions, you will receive an error message and all features are grayed out.
