### ISSUE TITLE
Remove "Create TIPP" form

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#216]
Currently, you can create a TIPP from the "Create TIPP" form, but you can not link it to a package or platform. This functionality should be added so that all work relating to creating a new TIPP can be done from one location.

**Comment by kristenwilson** [comment]
Decision to remove create TIPP form entirely. Only way to create TIPP is through package screen.

**Comment by ianibo** [comment]
Done.

**Comment by kristenwilson** [comment]
Confirmed fixed.
