### ISSUE TITLE
Add navigation and actions to both top and bottom of page

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#218]
Improve usability by allowing users access to controls w/o scrolling between top and bottom of page. Navigation has been added to top and bottom of page already. Actions menu is currently only available at bottom of page.

**Comment by iyawnis** [comment]
Is this for the screens under 'search' (showing table of available titles, packages, orgs, etc), or is it referring to other screens as well ?

**Comment by kristenwilson** [comment]
Yes, I believe it's just the search screens.

**Comment by iyawnis** [comment]
Without selection:
![screenshot from 2015-02-10 11 34 24](https://cloud.githubusercontent.com/assets/2336352/6126681/f6100330-b11a-11e4-89ca-f787527d3e5e.png)

With selection:
![screenshot from 2015-02-10 11 35 19](https://cloud.githubusercontent.com/assets/2336352/6126690/06714a90-b11b-11e4-8c10-736713b5bac4.png)

**Comment by kristenwilson** [comment]
Looks good, thanks.
