### ISSUE TITLE
Menu dropdown order

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#219]
Re-organise ‘Search’ menu to bring to the top: Package, Platform, Organisation, Title (TI), TIPP. Then line separator then remaining entities in alpha-order. Keep the order of the 'Create' menu dropdown in step with whatever order is chosen for the 'Search' menu

**Comment by ianibo** [comment]
Admins already have partial control over this as entries are grouped by their type (Current types are Admin, Standard and Support) and then alphabetically by name within group (As requested in HH feedback). 

Have additionally added SortOrder to domain classes. Administrators can now override sorting of menu entries by setting this - entries are grouped by Type and then sorted by sortKey, and then name within sort key.

menus are generated at login and cached so effects only seen after logout/login.

Pls note.. nulls sort high, so an sql update to set everything else to XX might by needed..

 update kbdomain_info set kbd_sort_order = 'XX' where kbd_sort_order is null;

This is the best we can do in this release without a substantial re-engineering of the domain handing module.
