### ISSUE TITLE
Fix global search column display

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#223]
Make same as other searches - and other than for TIPPs remove the Component ID and link with the Component Name instead

**Comment by ianibo** [comment]
Have updated columns. GLobal search is different to normal search, so getting them to present the same is hard (For example, facet listings only available in global search). Have harmonised as far as possible. Please open additional issues with specific changes (For example, make column headings grey). Used name as requested.

**Comment by kristenwilson** [comment]
Confirmed fixed
