### ISSUE TITLE
Fix refresh after deleting item in a tabbed view

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#224]
Currently when a user deletes an item from a tabbed view (e.g. deleting an Identifier from a Title record) the user is taken to the first tab on the record after the deletion and has to click back onto their previous tab to check if the deletion was successful. Suggest keeping the user on the same tab they are editing.

This is an annoying workflow so correct in this example and any others that follow the same pattern, As this is a persistent problem, KW will submit other cases as Github issues when they are identified - so may persist beyond R3.5

**Comment by ianibo** [comment]
For discussion - this is going to take a substantial amount of effort to do in 4.0

**Comment by kristenwilson** [comment]
Tab problem is fixed, but identifiers are now not being deleted. See #254.

**Comment by kristenwilson** [comment]
Confirmed fixed for this particular scenario. Will continue to report as other instances are noted.
