### ISSUE TITLE
Territory/Curator functionality

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#225]
As agreed on the 8/29 call, we will implement territories as below for version 4:
- Change the name Territory to Curator to indicate responsibility, rather than a geographic location.
- Add soft warning so that if someone is who not part of the curating group edits a record, they will be alerted to the fact that it has an official curator.

**Comment by kristenwilson** [comment]
See Dropbox\GOKb\Dev Phase 3 R3.5 planning\Supporting documentation\140828 Territory requirements for full spec.

**Comment by ianibo** [comment]
For discussion : this will have a performance impact on all screens - users to confirm.

**Comment by kristenwilson** [comment]
The basic functionality for this is working well. I can create a curatorial group, add users to a group, and assign a group to a package or platform. There are a few issues though:

1 I think there needs to be a separate permissions structure for linking a curatory group to a component. Currently, if I can edit a record, I can edit the curator assignment. However, for most users, we will want them to be able to edit the record itself, but not the curatory group, which should be limited to an editor or admin.
1. The "unlink" feature for the curatory group assignment doesn't seem to be controlled by any permissions domain. I can unlink a curator even when using an account with no write permissions.
2. I think the warning text is a little strong. Can we replace it with: "Warning. You are not a curator of this component. You can still edit it, but please contact the curator before making major changes."
3. Could we include a contact name and email address on the curator record? This would allow people to know who to contact if they have issues with a curated component.
4. If no curator is assigned, I don't think we should show the warning message. Can we change it so it displays only when a curator is present?

**Comment by sosguthorpe** [comment]
You can set the permissions for CuratoryGroup in the normal way. Create, Delete etc. I have now also made the link/unlink functionality dependant on 2 permissions. The user must have permission to edit the current record (i.e. a Package) but also have the "Administer" permission for Curatory Group. Once these changes are merged, you'll then be able to assign permissions to which ever groups you like.

**Comment by kristenwilson** [comment]
All of the above issues are confirmed fixed.

There is one new issue. When I try to assign a curator to a record now, I get an error message and the link is not made successfully.
