### ISSUE TITLE
Package and TIPP not created on Ingest

### ISSUE THREAD

**Issue by ostephens** [k-int/gokb-phase1#23]
Just tried ingesting what seemed to be a minimally valid Refine project (i.e. minimum amount of information provided to avoid all errors and warnings in Refine). 

Project is http://gokb.k-int.com/gokb/search/index?qbe=g%3Aprojects&det=2
Project contains a single line, defining a single TI with a single TIPP in a single Package.

The project seemed to ingest OK (no errors, marked as 'Ingested')
TI created OK http://gokb.k-int.com/gokb/search/index?qbe=g%3Atitles&det=1
But no Package or TIPP created

**Comment by ianibo** [comment]
Suspect tipps not being shown in interface rather than not being created. Will discuss with steve first thing.
