### ISSUE TITLE
Cannot attach data files to component

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#231]
When I upload a data file that is not automatically converted to a component in the system, I expect to be able to choose an existing component and attach the file to it. However, there is no way to do this in the UI. The data file record has an "attached to" field, but it is not editable. 

Example: http://gokb.kuali.org/gokb/resource/show/org.gokb.cred.DataFile%3A67325

**Comment by sosguthorpe** [comment]
We need to review the way files are stored in GOKb. Because of the architecture we need to store files in the database. We need to unify all files in the system to use this method of storage to make everything consistent.

**Comment by iyawnis** [comment]
Viewing existing file attachments and adding new is now done via a tab (similar to what already is available for License). Which other components should have this tab ?

**Comment by iyawnis** [comment]
![screenshot from 2015-02-02 17 43 38](https://cloud.githubusercontent.com/assets/2336352/6005535/0d00883a-ab03-11e4-808b-b5c0b3c648ed.png)

**Comment by sosguthorpe** [comment]
@latusaki The License file should not be editable. It should only be components where the attachment is optional that we should be able to do this. Whereas licenses need the file there.
Similarly you shouldn't be able to link a component from a file either. This is to stop the links from being broken between files that are needed, like licenses.

On license and file I would show the Files/Components linked and allow the users to see them but they should not be Deletable.

As for which components should have this functionality, I would defer this to @kristenwilson .

**Comment by kristenwilson** [comment]
At the moment, this really only applies to the license record. The issue we have here is that there are two categories of files for licenses:
1. ONIX-PL files: These are the XML files that are used to generate the license record. As Steve says, we don't want users to be able to edit or delete these records, since they are a required part of the license.
2. Supplementary files: We are receiving supplementary files (mostly html and pdfs) for license records. We do want to be able to attach these records to the license file and delete them if needed. 

So there needs to be a distinction on the license record between these two groups and separate functionality. 

Right now, I don't have any other use cases for attaching data files to other component types.

**Comment by iyawnis** [comment]
This was implemented by adding an 'Editable' field on DataFile. By default this is null/No. If this field is set to Yes, the DataFile will be available for attaching to components /licences, through a typedown inside the Files tab.

**Comment by kristenwilson** [comment]
I can confirm that this works as described. One question: The license mappings we're getting from Selden include a bunch of html files that show a more detailed view of the licenses. Is there a reason why GOKb will not allow me to open these files in my browser? I can open them from the desktop and they display perfectly in my browser, but opening from GOKb results in an error.

See https://gokb.k-int.com/gokb/resource/show/org.gokb.cred.License%3A37770

**Comment by iyawnis** [comment]
The files (xml and html) for that licence are not available. @sosguthorpe has copied the available files from Live, so I am not sure if there is some other way to get hold of the missing ones.

**Comment by kristenwilson** [comment]
I can see that this is working now on the other license: https://gokb.k-int.com/gokb/resource/show/org.gokb.cred.License%3A37763

I'm not sure why the files are missing on the DeGruyter license: https://gokb.k-int.com/gokb/resource/show/org.gokb.cred.License%3A37770

When I go to search>data files, I can see both files listed in the search results. In particular, the html file was one that I uploaded manually yesterday, so it seems odd that it became unavailable so quickly.

I'm not sure if I should close this issue or not? If the missing file problem won't happen in the live environment, then I think it should be OK.

**Comment by iyawnis** [comment]
It appears there is a problem with HTMLs specifically, other datatypes work will resolve this asap.
