### ISSUE TITLE
Add a notes field for TI, TIPP, Package

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#240]
Users have suggested note fields on at least the following components: TI, TIPP, Package. This would allow us to convey descriptive information about these entities. Each note should have an audit stamp with user and date; each note is new and has its own audit stamp, like a comment field.

**Comment by kristenwilson** [comment]
I tested the new header that contains the change history and notes for each title. I was able to successfully add a new note and view the history. 

There are a few changes that I think would improve looks and usability:
1. Would it be possible to remove the plain header underneath the new header? Currently, we have two headers that say the same thing, and I think it would look better with just one.
2. If we go with just the new header, can we increase the font size a little? (Similar to the old header.)
3. When you click the "add" button for a note, it closes the notes dialogue box. Can we leave the box open after adding the note?
4. Would it be possible to give an indicator of how many notes there are for a record? Maybe a number next to the icon, similar  to what we do on the tabs? (Not essential)

![notes_and_history](https://cloud.githubusercontent.com/assets/7397776/7501405/98dabd5c-f401-11e4-84df-4a72ef6e48fc.png)

**Comment by kristenwilson** [comment]
Tested this, all works as described in Ian's comment above. One other thing we might want to fix on this eventually is wrapping the test on long notes -- see example: http://test-gokb.kuali.org/gokb/resource/show/org.gokb.cred.TitleInstance%3A52417. Should I open another issue for that and/or the other formatting changes?

**Comment by ianibo** [comment]
No need to open another - we'll address it under this issue.

Ian.

On 20 May 2015 at 16:49, kristenwilson notifications@github.com wrote:

> Tested this, all works as described in Ian's comment above. One other
> thing we might want to fix on this eventually is wrapping the test on long
> notes -- see example:
> http://test-gokb.kuali.org/gokb/resource/show/org.gokb.cred.TitleInstance%3A52417.
> Should I open another issue for that and/or the other formatting changes?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/k-int/gokb-phase1/issues/240#issuecomment-103934335.

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo
GoodReads: https://www.goodreads.com/user/show/3106516-ian-ibbotson
