### ISSUE TITLE
Co-reference service error when multiple records for single identifier

### ISSUE THREAD

**Issue by ostephens** [k-int/gokb-phase1#242]
Using the Co-reference service without specifying a namespace causes an error when there are multiple records for the identifier across namespaces.

E.g. https://test-gokb.kuali.org/gokb/coreference/index?nspart=&idpart=0380-1330

gives error:

```
Error 500: Internal Server Error
URI
/gokb/coreference/index
Class
org.hibernate.NonUniqueResultException
Message
query did not return a unique result: 2
Trace
    Line | Method
->>  641 | doCall               in grails.gorm.DetachedCriteria$_get_closure2
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    931 | doCall               in grails.gorm.DetachedCriteria$_withPopulatedQuery_closure10
|    694 | doCall . . . . . . . in org.grails.datastore.gorm.GormStaticApi$_withDatastoreSession_closure23
|    302 | execute              in org.grails.datastore.mapping.core.DatastoreUtils
|     37 | execute . . . . . .  in org.grails.datastore.gorm.AbstractDatastoreApi
|    693 | withDatastoreSession in org.grails.datastore.gorm.GormStaticApi
|    913 | withPopulatedQuery . in grails.gorm.DetachedCriteria
|    640 | get                  in     ''
|    639 | get . . . . . . . .  in     ''
|     26 | index                in org.gokb.CoreferenceController
|    198 | doFilter . . . . . . in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter             in grails.plugin.cache.web.filter.AbstractFilter
|   1145 | runWorker . . . . .  in java.util.concurrent.ThreadPoolExecutor
|    615 | run                  in java.util.concurrent.ThreadPoolExecutor$Worker
^    722 | run . . . . . . . .  in java.lang.Thread
```

**Comment by ianibo** [comment]
ouch!

on this..

On 3 October 2014 17:22, Owen Stephens notifications@github.com wrote:

> Using the Co-reference service without specifying a namespace causes an
> error when there are multiple records for the identifier across namespaces.
> 
> E.g.
> https://test-gokb.kuali.org/gokb/coreference/index?nspart=&idpart=0380-1330
> 
> gives error:
> 
> Error 500: Internal Server Error
> URI
> /gokb/coreference/index
> Class
> org.hibernate.NonUniqueResultException
> Message
> query did not return a unique result: 2
> Trace
>     Line | Method
> ->>  641 | doCall               in grails.gorm.DetachedCriteria$_get_closure2
> 
> ---
> 
> |    931 | doCall               in grails.gorm.DetachedCriteria$_withPopulatedQuery_closure10
> |    694 | doCall . . . . . . . in org.grails.datastore.gorm.GormStaticApi$_withDatastoreSession_closure23
> |    302 | execute              in org.grails.datastore.mapping.core.DatastoreUtils
> |     37 | execute . . . . . .  in org.grails.datastore.gorm.AbstractDatastoreApi
> |    693 | withDatastoreSession in org.grails.datastore.gorm.GormStaticApi
> |    913 | withPopulatedQuery . in grails.gorm.DetachedCriteria
> |    640 | get                  in     ''
> |    639 | get . . . . . . . .  in     ''
> |     26 | index                in org.gokb.CoreferenceController
> |    198 | doFilter . . . . . . in grails.plugin.cache.web.filter.PageFragmentCachingFilter
> |     63 | doFilter             in grails.plugin.cache.web.filter.AbstractFilter
> |   1145 | runWorker . . . . .  in java.util.concurrent.ThreadPoolExecutor
> |    615 | run                  in java.util.concurrent.ThreadPoolExecutor$Worker
> ^    722 | run . . . . . . . .  in java.lang.Thread
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/k-int/gokb-phase1/issues/242.

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo
GoodReads: https://www.goodreads.com/user/show/3106516-ian-ibbotson
