### ISSUE TITLE
Comprehensive title history

### ISSUE THREAD

**Issue by ianibo** [k-int/gokb-phase1#247]
Add ability to see a comprehensive title history for the entire title family that includes both title changes and publisher changes as separate events. This could be shown as a pop-up or a link to a separate page (I’m open to UI suggestions here).

**Comment by kristenwilson** [comment]
Are we still planning to have this in 5.0? I don't see anything there.

**Comment by ianibo** [comment]
Example image below of a title history which includes a title 1 step away from the current title. Need to set up some test cases, but generically recurses through the title history structure.

![image](https://cloud.githubusercontent.com/assets/53283/9907960/70fa7dd6-5c89-11e5-9e5b-b47716519178.png)

**Comment by kristenwilson** [comment]
Created a couple test cases and seems to be working well.
