### ISSUE TITLE
Global Search throwing a Grails Runtime error

### ISSUE THREAD

**Issue by iamcreative** [k-int/gokb-phase1#251]
Username: TestUserA Oct14_HH Password: TestUserA

Error 500: Internal Server Error
URI /gokb/globalSearch/index
Class org.elasticsearch.indices.IndexMissingException
Message [gokb] missing

Trace
Line | Method
->>  771 | convertFromWildcards in org.elasticsearch.cluster.metadata.MetaData

---

|    659 | concreteIndices      in     ''
|    109 | <init> . . . . . . . in org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction
|     68 | <init>               in org.elasticsearch.action.search.type.TransportSearchQueryThenFetchAction$AsyncAction
|     62 | <init> . . . . . . . in     ''
|     59 | doExecute            in org.elasticsearch.action.search.type.TransportSearchQueryThenFetchAction
|     49 | doExecute . . . . .  in     ''
|     63 | execute              in org.elasticsearch.action.support.TransportAction
|    108 | doExecute . . . . .  in org.elasticsearch.action.search.TransportSearchAction
|     43 | doExecute            in     ''
|     63 | execute . . . . . .  in org.elasticsearch.action.support.TransportAction
|     92 | execute              in org.elasticsearch.client.node.NodeClient
|    212 | search . . . . . . . in org.elasticsearch.client.support.AbstractClient
|    330 | search               in org.elasticsearch.groovy.client.GClient
|    325 | search . . . . . . . in     ''
|     29 | index                in org.gokb.GlobalSearchController
|    195 | doFilter . . . . . . in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter             in grails.plugin.cache.web.filter.AbstractFilter
|   1145 | runWorker . . . . .  in java.util.concurrent.ThreadPoolExecutor
|    615 | run                  in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run . . . . . . . .  in java.lang.Thread

**Comment by ianibbo** [comment]
Sorry - no idea where this is.. Can we have URLs in the report please?

Don't think any of the systems are ready to be tested yet....

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by iamcreative** [comment]
Sorry I thought the URI was sufficient - the URL in this case is http://gokb.k-int.com/gokb/globalSearch/index?q=Art 

I'll retest in any case once the system is test-ready :)
