### ISSUE TITLE
Cannot delete identifiers

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#254]
When I try to delete an identifier from a title record, I get a dialogue box that says "Are you sure you want to delete this identifier." I click "yes." The screen refreshes, but the identifier is not deleted. I discovered this problem in relation to testing #224, but not sure if it is related. In previous versions of GOKb, this feature did work properly.

**Comment by sosguthorpe** [comment]
Should now be fixed

**Comment by ianibo** [comment]
Tested locally, confirming fixed in head.
