### ISSUE TITLE
Refine display issues

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#259]
I manually resolved an error in Refine by renaming a column. When I did this, the error/warning messages all jumped halfway down the page. 
![refine-error-1](https://cloud.githubusercontent.com/assets/7397776/4828423/07a32cfe-5f80-11e4-869f-80f3c00f0cf8.png)
![refine-error-2](https://cloud.githubusercontent.com/assets/7397776/4828428/0e6ec84a-5f80-11e4-8cc0-6f74de6e271b.png)

I then used "undo" to reverse my fix. At that point, all of the error and warning messages disappeared.
![Uploading refine-error-2.png . . .]()

**Comment by sosguthorpe** [comment]
Browser caching
