### ISSUE TITLE
Ingest results not displaying in Refine

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#262]
When I ingest a package in Refine, the ingest is successful, but the results of the ingest are not being displayed. Normally, after you begin an ingest, you are taken back to the list of projects in Refine, and you see a progress meter for your project. When the ingest is finished, you will see an Ingested status in the list of projects.

In the new client, after I begin the ingest, the project properties box just remains open. This is confusing because at first it made me think the ingest wasn't working. Can we return this to its original behavior?

**Comment by sosguthorpe** [comment]
This doesn't happen for me. I do get taken to the correct screen. Can you please tell me which browser you are using? I'll test it on windows using that browser to see if I can replicate it.

**Comment by kristenwilson** [comment]
I'm using Firefox.

**Comment by sosguthorpe** [comment]
Please can you check in the project you have checked out then I can try 
and ingest under windows?

P.S. Your refine client should have told you that it auto-updated and 
then shutdown refine for you to restart. Also don't forget to clear all 
your caches in your browser for the new changes to come through.

**Comment by kristenwilson** [comment]
Just checked it in.

On Thu, Oct 30, 2014 at 3:11 PM, sosguthorpe notifications@github.com
wrote:

> Please can you check in the project you have checked out then I can try
> and ingest under windows.
> 
> P.S. Your refine client should have told you that it auto-updated and
> then shutdown refine for you to restart. Also don't forget to clear all
> your caches in your browser for teh new changes to come through.
> 
> On 30/10/14 17:41, kristenwilson wrote:
> 
> > I'm using Firefox.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/k-int/gokb-phase1/issues/262#issuecomment-61135730.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/k-int/gokb-phase1/issues/262#issuecomment-61152632.

## 

Kristen Wilson
Associate Head, Acquisitions and Discovery
GOKb Editor
North Carolina State University Libraries
919-513-3354
kristen_wilson@ncsu.edu

**Comment by sosguthorpe** [comment]
Thanks Kristen. I can confirm I can see that it is broken on windows.

Can you confirm whether or not your client updated itself?

**Comment by kristenwilson** [comment]
I believe it did update. I had to step away from my desk for a bit and left
it open. When I got back, Refine had closed. I didn't see the message about
the update, but that may have been because I wasn't here and it disappeared
when the program shut down. I cleared my cache and went back in and
everything is looking good.

Kristen

On Thu, Oct 30, 2014 at 3:17 PM, sosguthorpe notifications@github.com
wrote:

> Thanks Kristen.
> 
> Can you confirm whether or not your client updated itself?
> 
> On 30/10/14 19:16, kristenwilson wrote:
> 
> > Just checked it in.
> > 
> > On Thu, Oct 30, 2014 at 3:11 PM, sosguthorpe notifications@github.com
> > wrote:
> > 
> > > Please can you check in the project you have checked out then I can try
> > > and ingest under windows.
> > > 
> > > P.S. Your refine client should have told you that it auto-updated and
> > > then shutdown refine for you to restart. Also don't forget to clear all
> > > your caches in your browser for teh new changes to come through.
> > > 
> > > On 30/10/14 17:41, kristenwilson wrote:
> > > 
> > > > I'm using Firefox.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > 
> > > > https://github.com/k-int/gokb-phase1/issues/262#issuecomment-61135730.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/k-int/gokb-phase1/issues/262#issuecomment-61152632
> > > .
> > 
> > ## 
> > 
> > Kristen Wilson
> > Associate Head, Acquisitions and Discovery
> > GOKb Editor
> > North Carolina State University Libraries
> > 919-513-3354
> > kristen_wilson@ncsu.edu
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/k-int/gokb-phase1/issues/262#issuecomment-61153580.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/k-int/gokb-phase1/issues/262#issuecomment-61153855.

## 

Kristen Wilson
Associate Head, Acquisitions and Discovery
GOKb Editor
North Carolina State University Libraries
919-513-3354
kristen_wilson@ncsu.edu

**Comment by sosguthorpe** [comment]
The message should have been a permanent one. This looks like a bug with OpenRefine on windows and not our module. I'm knocking off now but will pick it up sometime tomorrow.

Thanks for your help.

**Comment by kristenwilson** [comment]
I'm still seeing an odd display when I try to ingest a package. After ingest today, I saw this:

![ingest-error](https://cloud.githubusercontent.com/assets/7397776/5077686/c5c288d6-6e73-11e4-83f7-1ca48e8bdca8.png)

Despite the error message, the project had ingested just fine.

**Comment by kristenwilson** [comment]
This problem is still occurring. See screencast demo: http://screencast.com/t/mqEthVpH9d

**Comment by kristenwilson** [comment]
Confirmed fixed.
