### ISSUE TITLE
Source not ingesting from Refine

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#263]
When I ingest a project from Refine, the source field is not populated in the resulting package in the CRED. In previous releases, this source was populated successfully through Refine ingest. Can we fix?

**Comment by sosguthorpe** [comment]
Works fine for me now. Might have been another issue causing this as a side-effect.

**Comment by kristenwilson** [comment]
Source is still not ingesting for me. Ingested two projects today and source was not populated for either one.

**Comment by kristenwilson** [comment]
See screencast demo: http://screencast.com/t/RnMTS3vPX

**Comment by sosguthorpe** [comment]
Yes. I was only checking the Project. Hadn't realilsed it was to be saved against the package too. Completely my fault for not reading this issue properly.

**Comment by kristenwilson** [comment]
Confirmed fixed.
