### ISSUE TITLE
Give GOKb export files useful names

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#264]
Currently, all GOKb export files are named "GOKb." Can these have a more useful name? A good name would be the same as or similar to the header that's included in each file. Example: Taylor  & Francis : Taylor & Francis: Sociology and Related Disciplines Collection 2014 : 2014-10-30. (I'm fine with eliminating spaces or removing punctuation, etc.)

**Comment by kristenwilson** [comment]
See #201

**Comment by sosguthorpe** [comment]
Closing. Works in FF for me now.
