### ISSUE TITLE
GOKb export files are not recognized by Windows

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#265]
The GOKb export file is not recognized by Windows -- I think this may be because it doesn't have a file extension. I can still open it with something like Notepad++ or import it into Excel. I think it would be more intuitive to users if it had a familiar file type. This will also allow the file to be more easily opened in Excel or other programs designed for TSV files.

**Comment by kristenwilson** [comment]
See #201

**Comment by ianibo** [comment]
Steve - can you handle this one please - you seemed to have an idea - works just fine for me in linux. Browser issue?

**Comment by sosguthorpe** [comment]
Related to #264 

Headers may have already been sent? Which browser are you using Ian? Broken for me on FF (linux).

**Comment by ianibbo** [comment]
Chrome -
Don't think they are already sent... nothing I can see which would cause
that.. Will recheck code

e

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ianibo** [comment]
Tested using firefox on lin - seems fine now - think the quoted filename sorted it.
