### ISSUE TITLE
TIPP record not displaying correct header

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#269]
The TIPP record used to display a header with detailed information, like this: TIPP : 89795 - ADHD Attention Deficit and Hyperactivity Disorders in Springer: Complete Journals via SpringerLink 

In 4.0, the TIPP header only displays: TIPP: 12345. Fix this so that it only displays the full header.

**Comment by ianibo** [comment]
Added derivedName to component and tipp. used it in tipp header. Not sure exactly where this issue refers to in app so please add more info and URL if not fixed where you are looking.,

**Comment by kristenwilson** [comment]
This is still not displaying the full TIPP display name. 

Here's how it used to look:
https://test-gokb.kuali.org/gokb/resource/show/org.gokb.cred.TitleInstancePackagePlatform%3A112214

Here's how it looks now:https://gokb.k-int.com/gokb/resource/show/org.gokb.cred.TitleInstancePackagePlatform%3A58694

**Comment by ianibo** [comment]
Re-fixed. 
![image](https://cloud.githubusercontent.com/assets/53283/5202909/f8508b92-7579-11e4-9db1-421f3ae121ec.png)
