### ISSUE TITLE
Alternative title being created even where it exactly matches existing title

### ISSUE THREAD

**Issue by ostephens** [k-int/gokb-phase1#27]
E.g. http://gokb.k-int.com/gokb/search/index?qbe=g%3Atitles&qp_name=Ambix%25&det=1

Three listed 'alternative titles' - one is genuine 'alternative', other two are identical and also identical to TI title.

Behaviour should be no alternative title created if title fingerprints identical to TI title or existing alternative title

**Comment by sosguthorpe** [comment]
Can you check this is still the case please Owen. If if is still occurring on new data can you detail a specific project that should reproduce the behaviour please?

**Comment by ostephens** [comment]
Cannot reproduce behaviour

**Comment by ostephens** [comment]
Have now reproduced behaviour
Was ingesting project where no identifiers present, but title string matched - this created a new Variant title identical to the title string
Replicated this problem for two titles
In each case a data review task created see:
http://gokb.k-int.com/gokb/search/index?qbe=g%3AreviewRequests&det=18&max=100
http://gokb.k-int.com/gokb/search/index?qbe=g%3AreviewRequests&det=20&max=100

**Comment by sosguthorpe** [comment]
Yep. Was only testing whether the variant has already been added, not checking the actual title. SHould be fixed now.

**Comment by ostephens** [comment]
Fixed
