### ISSUE TITLE
Character limits are preventing ingest of large values

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#271]
#249 asks that character limits be upped. Ian said via email: I've made the type of the column "text" - which means it's now a large object and unlikely to hit a size limit again.

Testing shows that a large number of characters in a field value is not preventing ingest of the whole title record as previously. However, a large number of characters did prevent the individual field from ingesting. Ian's message implied that the field limits themselves should be fixed so that large notes could be ingest. Is that correct? Large field values should be able to be ingested if possible.

**Comment by ianibo** [comment]
Made name text and updated database on kbplus.k-int.com.

**Comment by kristenwilson** [comment]
This is affecting the gokb.ti/tipp.xx custom field

**Comment by kristenwilson** [comment]
This is still an issue. I ingested a project with with following in the gokb.tipp.notes field:

Incorporating Social Science & Medicine. Part A: Medical Psychology & Medical Sociology , Social Science & Medicine. Part B: Medical Anthropology , Social Science & Medicine. Part C: Medical Economics , Social Science & Medicine. Part D: Medical Geography , Social Science & Medicine. Part E: Medical Psychology and Social Science & Medicine. Part F: Medical and Social Ethics;

The entire title record did not ingest and there is no way for the user to know why this is happening. Can we expand the character limit for the ti/tipp custom field to let in bigger notes?

**Comment by ianibo** [comment]
Fixed in code, closing here. If this recurs, need issue raising with hostname and URL as the database schema needs updating per system.
