### ISSUE TITLE
#143 not fixed -- Display name for TIPP on review tasks

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#273]
Per #143 review tasks with a TIPP as the component should use a display name, rather than appearing empty. This has not been fixed. Example: https://gokb.k-int.com/gokb/resource/show/org.gokb.cred.ReviewRequest%3A7

**Comment by ianibo** [comment]
Added new method for getting display name of component.

**Comment by kristenwilson** [comment]
Would it be possible to display the name of the title associated with the TIPP for better human readability?
