### ISSUE TITLE
Aphabetize Orgs list

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#274]
Per #105, list of components should be alphabetized before user performs a search. This appears to have been implemented for packages and titles, but not orgs. This might be one of those things were we need to put in separate issues for each instance. I think Orgs are the only other priority for 4.0. I can submit others at a later time.

**Comment by kristenwilson** [comment]
Orgs are still not alphabetized when I first go to the orgs search page. The goal is that they should be alphabetized to start with, then sorted by relevance after a search is entered. 

![orgs_not_alpha](https://cloud.githubusercontent.com/assets/7397776/5077790/c30c952c-6e74-11e4-8e49-ea71b31f94c9.png)

**Comment by sosguthorpe** [comment]
The orgs are in fact being sorted alphanumerically. The 2 top records actually start with a space " ". This puts them top as far as the sort order goes. I have just edited these 2 and that seemed to do the trick. The space doesn't show when editing as HTML natively ignores leading and tailing white space, the database, however treats this as the first character.

**Comment by sosguthorpe** [comment]
As these searches are driven by database queries and not an index, like the Global search page there is no "relevance" when it comes to results. So the sorting will always be alphanumeric.

**Comment by ianibo** [comment]
Closing, per steves comments - spaces are sorting high.
