### ISSUE TITLE
Retire package action not working

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#275]
The "Retire Package" option from the actions menu on a package record does not work. I can select the action and confirm that i really want to retire the package. But after that, the package status remains current and all TIPPs remain current as well. These should be set to retired per #178.

**Comment by ianibo** [comment]
Steve - have checked in change to re-introduce retire, but when it fires deproxy gets into a tangle - it's called for each tipp after a call to getTipps and complains thus:

2014-11-02 10:41:44,650 [http-bio-8080-exec-8] DEBUG gokb.WorkflowController  - Attempting to fire method retire ([[user:admin / admin, params:[selectedBulkAction:method::retire, bulk:org.gokb.cred.Package:37465:true, bulk:org:[gokb.cred.Package:37465:true, gokb:[cred.Package:37465:true, cred:[Package:37465:true]]], action:action, controller:workflow]]])
| Error groovy.lang.MissingMethodException: No signature of method: com.k_int.apis.GrailsDomainHelpersApi.deproxy() is applicable for argument types: (org.gokb.cred.Package, org.gokb.cred.KBComponent_$$_javassist_24) values: [American Society for Microbiology:Master List 2013 (Package 37465), ...]
Possible solutions: deproxy(java.lang.Object), deproxy(java.lang.Class, java.lang.Object)

**Comment by ianibo** [comment]
Again? Jeez I really need to keep an eye out for that! 

thanks fella.

**Comment by sosguthorpe** [comment]
No problemo.
