### ISSUE TITLE
Title change action does not set start date correctly for new TIPP

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#279]
When I use the title change action to create a new TIPP, the start date for that TIPP is not set to the value I entered. Below is an example of a title change I submitted:

![title-change](https://cloud.githubusercontent.com/assets/7397776/4862509/3452703c-610d-11e4-97e0-13fb0268094c.png)

I filled in 2013-01-01 as the start date for the new TIPP. However, the start date on the new TIPP was the same as the start date of the old TIPP. See https://gokb.k-int.com/gokb/resource/show/org.gokb.cred.TitleInstancePackagePlatform%3A55539

(Also note that the new TIPP is being linked to the wrong title per #278.

**Comment by kristenwilson** [comment]
See #177

**Comment by ianibo** [comment]
needs retest.

**Comment by kristenwilson** [comment]
I'm still seeing the same issue here. I processed the title change below, and entered start dates of 2013-01-01 for all of the new TIPPs (in green). 
![title-change-example](https://cloud.githubusercontent.com/assets/7397776/5204529/1edbe7f0-755e-11e4-82e7-4e6359a09cc8.png)

But when these TIPPs were created, they have a start date of 1997-01-01. 
![new_tipp_dates_error](https://cloud.githubusercontent.com/assets/7397776/5204544/3d569194-755e-11e4-802f-b1fff19563bb.png)

The dates for TIPPs need to be set correctly based on the dates entered into the title change action screen.

**Comment by ianibo** [comment]
Bizzare - INvestigating.

On 31 October 2014 at 14:51, kristenwilson notifications@github.com wrote:

> When I use the title change action to create a new TIPP, the start date
> for that TIPP is not set to the value I entered. Below is an example of a
> title change I submitted:
> 
> [image: title-change]
> https://cloud.githubusercontent.com/assets/7397776/4862509/3452703c-610d-11e4-97e0-13fb0268094c.png
> 
> I filled in 2013-01-01 as the start date for the new TIPP. However, the
> start date on the new TIPP was the same as the start date of the old TIPP.
> See
> https://gokb.k-int.com/gokb/resource/show/org.gokb.cred.TitleInstancePackagePlatform%3A55539
> 
> (Also note that the new TIPP is being linked to the wrong title per #278
> https://github.com/k-int/gokb-phase1/issues/278.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/k-int/gokb-phase1/issues/279.

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo
GoodReads: https://www.goodreads.com/user/show/3106516-ian-ibbotson

**Comment by kristenwilson** [comment]
I was able to confirm this is now working.
