### ISSUE TITLE
Show source files on project record in CRED

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#284]
There is currently no UI for the Refine source files that are being stored in GOKb. Add a display for these files to the UI for the project record in the CRED and allow users to download the file from here. See #203.

**Comment by kristenwilson** [comment]
I'm getting an error message when I try to download the source file.
![source-download-error](https://cloud.githubusercontent.com/assets/7397776/5077724/1fc918e0-6e74-11e4-99fc-11423ec7ed14.png)

**Comment by kristenwilson** [comment]
When I try to download the source file from a project record in CRED, I'm still getting the error above. Is any additional clarification needed here?

**Comment by sosguthorpe** [comment]
This seems to be working fine now.
