### ISSUE TITLE
Implement KBART2

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#286]
Ingest all KBART2 fields and export files in KBART2 format.

**Comment by kristenwilson** [comment]
Sync it up with KB+ work on KBART2 -- deadline by June.

**Comment by kristenwilson** [comment]
DK notes from KB+ discussion: Title History – store as Preceding Titles, recognizing that KBART TH is not rich enough to populate the KB+ TH model
• Access Type – consider storing the KBART value simply in order to fulfill data in / data out expectations; however it is agreed that the (inadequate) KBART expression should not be allowed to corrupt the KB+ OA Type
• Export needs to be upgraded to deliver KBART2

**Comment by ianibo** [comment]
Added TH element to KBART export
