### ISSUE TITLE
Sort order does not work

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#288]
The mechanism for creating a sort order for ref data values and menu values does not work. I can enter 1, 2, 3... into the blanks for sort order, but it does not affect the display on the record itself.

**Comment by sosguthorpe** [comment]
The next update will include a fix for this. The current values will be observed within the current type. So the refdata type will be used to determine the grouping and the order of menus. And then within the type this value takes effect.

i.e. An admin could add a "Primary" and "Secondary" type for the menus and set primary sort to be 1 and secondary to be 2. That would create the 2 groups within the menus. Then the sort order of the domain component itself can be used to make an item appear higher within it's section.
