### ISSUE TITLE
Incorrect estimate of titles to be created

### ISSUE THREAD

**Issue by ostephens** [k-int/gokb-phase1#29]
Using Project GOKb:Test:TI Test Partial ID Match (http://gokb.k-int.com/gokb/search/index?qbe=g%3Aprojects&qp_name=%25Partial%25&det=1)

Aim is to test if no TI IDs for matching (i.e. no ISSN,eISSN,DOI,ISBN) in project, but publicationTitle string matches existing TI, this is counted as a 'partial match' and imported, but with a review request created.

However, on starting Ingest process get following estimates

![screen shot 2013-08-19 at 13 34 32](https://f.cloud.github.com/assets/576174/985884/0afd35ae-08cc-11e3-8e08-61343a5fef3f.png)

Number shown for titles '9405' matches current total number of TIs in GOKb instance

**Comment by sosguthorpe** [comment]
I don't get this behaviour. Can you retest and confirm that this is fixed.

**Comment by ostephens** [comment]
Confirm now works as expected
