### ISSUE TITLE
Incorrect estimates of titles to be created on uploading a line which matches multiple TIs on ID matching

### ISSUE THREAD

**Issue by ostephens** [k-int/gokb-phase1#30]
Created a test project "GOKb:Test:TI Bad Match" which contains a line with an ISSN which matches one existing TI and eISSN that matches a different existing TI.

Title creation/update estimates on attempt to ingest look like:

![screen shot 2013-08-19 at 13 59 59](https://f.cloud.github.com/assets/576174/986021/f166eab4-08cf-11e3-8636-45b50df4dac5.png)

It isn't suprising that there is a an oddity here as file deliberately incorrect. However, I think obvious problems (like an estimate of '-1' titles created) should be caught. Both numbers have to be zero or greater.

It maybe that having an estimate of <0 suggests we shouldn't allow ingest to proceed? Or at least a warning of somekind?

**Comment by sosguthorpe** [comment]
The estimation process needs a bit of an overhaul.

**Comment by ostephens** [comment]
This scenario still creates the same estimate as previously when ingesting package as either Update or Replacement

**Comment by sosguthorpe** [comment]
I would expect packages to be different only, as no matter which type of update you do you everything behaves the same appart from the Packages and TIPPs. Seeing as we don't give TIPP estimates I would expect them to be very similar.

When doing a replacement type each existing package should result in both an update (retirement of existing) and creation. For update existing would only cause a single update.

**Comment by ostephens** [comment]
Just about to take off so only brief reply - the issue I'm seeing is with Titles - only single title in file indicated as '-1' to be created and '2' to be updated. 

Cheers

Owen

**Comment by ostephens** [comment]
Fixed with latest update
