### ISSUE TITLE
Add refdata validation type

### ISSUE THREAD

**Issue by sosguthorpe** [k-int/gokb-phase1#301]
We need to allow certain fields to be validated against the current set of refdata for a particular category instead of a set list.

**Comment by sosguthorpe** [comment]
@kristenwilson 
I have added this functionality as a favour for this release as it was fairly quick to implement. However, there are now a couple of things to be aware of. Depending on which server you are connected to in the refine client the values "could" be different for the refdata in the system and therefore refine will behave differently for each server.

The second point is there might now be more/fewer "valid" options for some fields in refine since we are now driving from the data on the server. Can you please test thoroughly to ensure you are happy with this functionality. If it looks like it's had some undesired side-effects we will roll it back and re-address at a later date.

**Comment by kristenwilson** [comment]
Steve, I tested this with multiple values and ref data categories and all seems to be working as it should. Thanks for squeezing this in. The only issue I saw was that the warning message in Refine is displaying deprecated values in the list of allowed values. Would it be possible to filter out the deprecated ones?
