### ISSUE TITLE
Errors on partial ingest

### ISSUE THREAD

**Issue by ostephens** [k-int/gokb-phase1#31]
Tried to ingest a project "GOKb:Test:TI Bad Match" with line that deliberately matches ISSN against one existing TI and eISSN against a different existing TI.

When go to Ingest, get a 'partial ingest'

Open the partially ingested file, see error "One or more title was not ingested during the last ingest."

Use 'quick resolution' to create facet of errors (this is not entirely intuitive - wonder if we can create Facet automatically?)

On facet all information available is 'error'. This is going to be challenging for user to de-bug. Is there any way we can get more information back at this stage - what was the error? (e.g. "Error, ISSN matched Title X; eISSN matched Title Y"). I think we need to provide better feedback at this stage to the user

If it isn't possible to display data in Refine, maybe a list of errors stored against project accessible via Web UI?

**Comment by sosguthorpe** [comment]
This needs to thought about and some in depth researching dev done in refine. Realise this isn't ideal at all but propose we leave it for now with a caveat that it will be improved in some way. Want to try and force it into the data if we can.

**Comment by ostephens** [comment]
OK - is there anywhere the errors that cause the reject are logged at the moment? Some information for users better than none. But that said there are a limited number of scenarios that cause this rejection so there should be a clear process for uncovering the problem.

So fine to leave as is. If there is anyway of offering any info (e.g. via an error log in the web UI) that would be great, but otherwise will be fine.

**Comment by ostephens** [comment]
This seems to be working less well than previously
Created a file where one title should fail as a 'bad match'
I'm not seeing any messages about 'Partial Ingest' - either on ingest, or on re-opening the project. Previously this information was displayed I believe?

**Comment by sosguthorpe** [comment]
Fixed. Which unearthed another error because of the case-insensitivity of column names. Refine is case sensitive and therefore I've had to add a new method that can be used in GREL to lookup the actual value in the document for an insensitive title.

**Comment by ostephens** [comment]
Fixed
