### ISSUE TITLE
Make all URLs and links to components in GOKb clickable

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#310]
Currently, some URLs and names of other components in GOKb are not clickable (i.e., you can't click them because doing so enables editing of the field). It would greatly increase usability to allow users to navigate to URLs and other components within the UI by clicking field values. Alternately, we could have a "link" next to these values for clicking, to preserve the UX for editing (see example on review tasks).

Linking is needed for the following values:

Package:
- Provider (link to Org)
- Source (link to Source)
- Nominal Platform (link to Platform)

Title:
- Latest publisher (link to Org)

TIPP:
- Host Platform URL (open link in new tab)

Platform:
- Source (link to source)
- Primary URL (open link in new tab)

Office:
- Web site (open link in new tab)

Projects:
- Source (link to source)

Source:
- URL (open link in new tab)

**Comment by kristenwilson** [comment]
Note that top priority is TIPP URL link.

**Comment by ianibo** [comment]
No idea whats going on with the tags on this one - please test

**Comment by kristenwilson** [comment]
All of the links within the CRED are working. The four URL fields still do not have clickable links. These are:
- TIPP - host platform URL
- Platform - primary URL
- Office - web site 
- Source - URL

These should all open in a new tab, as specified above.
