### ISSUE TITLE
"Latest publisher" field is not populated when no publishers are active

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#311]
If all of the publishers listed on the "Publishers" tab of the TI have end dates, the latest publisher field remains blank. The "latest publisher" field should display the name of the publisher with the most recent end date. 

See example: https://gokb.kuali.org/gokb/resource/show/org.gokb.cred.TitleInstance%3A52417

**Comment by ianibbo** [comment]
This is a tricky one..

It used to be called "Current publisher" in the UI and what the object
knows about is the publisher attached to the title that currently does not
have an end date. In a(4.0?) change we were asked to change the "Current
publisher" label to "latest publisher" - but the value in the field is
still actually "Current Publisher" (Publisher without an end date).

Therefore, this is a bit more computationally expensive as we need to read
through each publisher record and select the latest one. Not impossible,
but again, lots of little things like this will add up to sluggish
behaviour in the UI.

Happy to add - but not a non-trivial task.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by kristenwilson** [comment]
Per Ian, this is actually easier to fix that initially though. Slated for 4.2.

**Comment by kristenwilson** [comment]
Confirmed
