### ISSUE TITLE
Set up email inbox for gokb.org to reduce emails sent to spam

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#315]
Many user are finding that confirmation emails for account registration are going into their spam boxes or even getting blocked entirely by their employers' email set up. Ian says:

What I _think_ we really need is a hello@gokb.org [And perhaps a family of support@gokb.org,...] hosted by a real domain. There are a few options for this..

1) It might well be that robert m already has an email inbox for the domain supplied by GoDaddy, and that we can send mail through that MX record. The dns records for the domain don't show any MX records tho.

2) We could set up a one-off gmail account - gokb@gmail.com

3) We can set up a mail exchanger on the server, but that still means getting access to the GoDaddy DNS config.

**Comment by ianibo** [comment]
Done - configured on live. email is globalopenkb@gmail.com (google user names need to be > 6 chars, so gokb@gmail.com not doable). Will supply gmail password over phone for anyone wanting it.

**Comment by kristenwilson** [comment]
I tested this morning by creating a new account on live. After about 10 minutes, I still have not received any email at all (in inbox or spam). I tested on K-Int test again and did receive the email from the old address.

**Comment by ianibbo** [comment]
This config change was only made on live, as it's not a software thing...
We'll make the change on ki test tho as well for testing and note here once
its done

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by kristenwilson** [comment]
Just wanted to note that the problems with the registration emails not working on live are urgent to resolve, since we have opened the service up to the general public on gokb.org and have users in training. I've already gotten one email from another user saying they did not receive the email for the live service.

Depending on how long this will take to fix, it might be better to switch the mailbox on live back to the old one and get things resolved on test first.

**Comment by ianibo** [comment]
Just looking - not aware of any reason this should not be working..

On 2 February 2015 at 19:51, kristenwilson notifications@github.com wrote:

> Just wanted to note that the problems with the registration emails not
> working on live are urgent to resolve, since we have opened the service up
> to the general public on gokb.org and have users in training. I've
> already gotten one email from another user saying they did not receive the
> email for the live service.
> 
> Depending on how long this will take to fix, it might be better to switch
> the mailbox on live back to the old one and get things resolved on test
> first.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/k-int/gokb-phase1/issues/315#issuecomment-72524820.

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo
GoodReads: https://www.goodreads.com/user/show/3106516-ian-ibbotson

**Comment by ianibo** [comment]
Sorry - stupid error on my part - email response addresses were being
overridden. I've changed it and restarted now. Should be fixed on live.

On 2 February 2015 at 20:09, ianibbo@gmail.com ianibbo@gmail.com wrote:

> Just looking - not aware of any reason this should not be working..
> 
> On 2 February 2015 at 19:51, kristenwilson notifications@github.com
> wrote:
> 
> > Just wanted to note that the problems with the registration emails not
> > working on live are urgent to resolve, since we have opened the service up
> > to the general public on gokb.org and have users in training. I've
> > already gotten one email from another user saying they did not receive the
> > email for the live service.
> > 
> > Depending on how long this will take to fix, it might be better to switch
> > the mailbox on live back to the old one and get things resolved on test
> > first.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/k-int/gokb-phase1/issues/315#issuecomment-72524820.
> 
> ## 
> 
> Ian Ibbotson
> W: http://ianibbo.me
> E: ianibbo@gmail.com
> skype: ianibbo
> twitter: ianibbo
> GoodReads: https://www.goodreads.com/user/show/3106516-ian-ibbotson

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo
GoodReads: https://www.goodreads.com/user/show/3106516-ian-ibbotson

**Comment by kristenwilson** [comment]
Thanks, Ian. Looks like it's working now.

**Comment by kristenwilson** [comment]
Yes, this is working for me now too. We still need to propagate this change to the Kuali test version of GOKb.

**Comment by ianibo** [comment]
Change is on test also now. Closing issue - please open new calls for subsequent issues.
