### ISSUE TITLE
Alphabetize Imprints list

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#316]

**Comment by kristenwilson** [comment]
Similar to platforms, would it be possible to interfile upper- and lowercase letters for sort? Currently imprints beginning with a lowercase letter sort to the bottom of the list.

**Comment by ianibo** [comment]
Should be sortable with 
alter database GoKB character set utf8 collate utf8_general_ci;
on server.

**Comment by ianibo** [comment]
Also needs running on a per table basis::

ALTER TABLE acl_class COLLATE utf8_general_ci;
ALTER TABLE acl_entry COLLATE utf8_general_ci;
ALTER TABLE acl_object_identity COLLATE utf8_general_ci;
ALTER TABLE acl_sid COLLATE utf8_general_ci;
ALTER TABLE activity COLLATE utf8_general_ci;
ALTER TABLE additional_property_definition COLLATE utf8_general_ci;
ALTER TABLE annotation COLLATE utf8_general_ci;
ALTER TABLE audit_log COLLATE utf8_general_ci;
ALTER TABLE batch_control COLLATE utf8_general_ci;
ALTER TABLE combo COLLATE utf8_general_ci;
ALTER TABLE component_history_event COLLATE utf8_general_ci;
ALTER TABLE component_history_event_participant COLLATE utf8_general_ci;
ALTER TABLE document COLLATE utf8_general_ci;
ALTER TABLE ftcontrol COLLATE utf8_general_ci;
ALTER TABLE history COLLATE utf8_general_ci;
ALTER TABLE identifier_namespace COLLATE utf8_general_ci;
ALTER TABLE kb_component_tags_value COLLATE utf8_general_ci;
ALTER TABLE kbcomponent COLLATE utf8_general_ci;
ALTER TABLE kbcomponent_additional_property COLLATE utf8_general_ci;
ALTER TABLE kbcomponent_variant_name COLLATE utf8_general_ci;
ALTER TABLE kbdomain_info COLLATE utf8_general_ci;
ALTER TABLE note COLLATE utf8_general_ci;
ALTER TABLE org_refdata_value COLLATE utf8_general_ci;
ALTER TABLE org_role COLLATE utf8_general_ci;
ALTER TABLE platform_refdata_value COLLATE utf8_general_ci;
ALTER TABLE refdata_category COLLATE utf8_general_ci;
ALTER TABLE refdata_value COLLATE utf8_general_ci;
ALTER TABLE refine_operation COLLATE utf8_general_ci;
ALTER TABLE refine_project_skipped_titles COLLATE utf8_general_ci;
ALTER TABLE registration_code COLLATE utf8_general_ci;
ALTER TABLE review_request COLLATE utf8_general_ci;
ALTER TABLE review_request_allocation_log COLLATE utf8_general_ci;
ALTER TABLE role COLLATE utf8_general_ci;
ALTER TABLE rule COLLATE utf8_general_ci;
ALTER TABLE saved_search COLLATE utf8_general_ci;
ALTER TABLE user COLLATE utf8_general_ci;
ALTER TABLE user_curatory_groups COLLATE utf8_general_ci;
ALTER TABLE user_role COLLATE utf8_general_ci;
ALTER TABLE user_territories COLLATE utf8_general_ci;
ALTER TABLE web_hook COLLATE utf8_general_ci;
ALTER TABLE web_hook_endpoint COLLATE utf8_general_ci;

**Comment by ianibo** [comment]
Nope - needed this
ALTER TABLE kbcomponent CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;

**Comment by ianibo** [comment]
Commands needed to make this work::

ALTER TABLE acl_class CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE acl_entry CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE acl_object_identity CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE acl_sid CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE activity CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE additional_property_definition CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE annotation CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE audit_log CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE batch_control CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE combo CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE component_history_event CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE component_history_event_participant CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE document CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE ftcontrol CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE history CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE identifier_namespace CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE kb_component_tags_value CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE kbcomponent CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE kbcomponent_additional_property CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE kbcomponent_variant_name CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE kbdomain_info CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE note CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE org_refdata_value CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE org_role CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE platform_refdata_value CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE refdata_category CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE refdata_value CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE refine_operation CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE refine_project_skipped_titles CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE registration_code CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE review_request CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE review_request_allocation_log CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE role CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE rule CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE saved_search CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE user CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE user_curatory_groups CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE user_role CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE user_territories CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE web_hook CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE web_hook_endpoint CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;

**Comment by ianibo** [comment]
COmmands run on test
