### ISSUE TITLE
No option to edit Variant/Alternate Titles?

### ISSUE THREAD

**Issue by ostephens** [k-int/gokb-phase1#32]
E.g. can see a list of Alternate Titles at
http://gokb.k-int.com/gokb/search/index?qbe=g%3Atitles&qp_name=Ambix%25&det=1

But can't edit any of the title strings (although can edit Status, Variant Type and Locale)

**Comment by ianibbo** [comment]
I thought these would only be generated by the import process and therefore
didn't allow user edit.. should they be? seems dangerous.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
Maybe you're right - they can delete them I guess if they are wrong
