### ISSUE TITLE
Add ability to manually add an ID in CRED

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#320]

**Comment by kristenwilson** [comment]
This should be possible for all records that allow an ID to be assigned -- currently, TI and Org.

**Comment by ianibo** [comment]
Reopened and added testme label.

**Comment by kristenwilson** [comment]
Confirmed that this works. Would it be possible to make it so that the user stays on the Identifiers tab after adding a new one? As it is, they are taken back to the main tab, then have to navigate back to Identifiers to add another or check that it was added correctly.
