### ISSUE TITLE
Make select platform menu in Refine open to all users

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#323]
In the OpenRefine extension, there is a menu that allows users to select which platform they'd like to use (live, test, k-int). By default, users are prompted to sign into the live platform when they first open Refine. This creates a problem because if users have permission to user Refine on test, but not live (as will be the case for all users in training), they will be unable to access the menu to switch the application to the correct platform. Can we make the platform menu to all users with a valid GOKb group when they sign into Refine?

**Comment by sosguthorpe** [comment]
The problem with sending them to a valid service is that you are not signing into refine, you are signing into the GOKb service. Therefore you have to point refine at the GOKb service you are attempting to sign in. Searching for a service they can connect to would cause a major headache. How would the system be able tio determine the difference between a user that hasn't got access to any service and a mistyped username/password.

I propose we add the selection box to the login prompt thus allowing the user to change it before logging in.

**Comment by ianibo** [comment]
Steve - have asked @latusaki to look at this right away, pref before the call at 4 ;) can you support him pls?

**Comment by kristenwilson** [comment]
Need updated extension to test.

**Comment by iyawnis** [comment]
@kristenwilson  I have re-built the extensions after the last change to Login menu : https://github.com/k-int/gokb-phase1/commit/ff0e1af2a93f1028dcc2ab77eb22918cfbb885b6 . Is this what you needed ?

**Comment by kristenwilson** [comment]
Thanks @latusaki. I tried this with the test Kuali extension and it worked. I noticed you have three extensions rebuilt. We've moved to having only a single extension with the last release, so I just wanted to make sure that we'll still have that going forward.

**Comment by iyawnis** [comment]
I just wasn't completely aware of the built process, all three builts are the same, I will make the required changes so that there is only one zip generated.
