### ISSUE TITLE
Title History A : Publication Dates / Pub Date Conflicts

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#327]
Generate review tasks for TIPPs that have coverage that extends beyond the publication date of the related TI.

**Comment by iyawnis** [comment]
Is there any filtering I should apply, based on the status of titles / tipps? e.g should I only be looking at current ones?

**Comment by iyawnis** [comment]
Also, are we only interested in the publication end date, or publication start date as well? Finally, on my system I have title without publishedTo date. The TIPP specifies accessEndDate. Should this raise a conflict?

**Comment by kristenwilson** [comment]
We probably need a more detailed spec about how this would actually work, since there a number of unanswered questions I can think of. Maybe we can talk about it at an upcoming meeting.

**Comment by kristenwilson** [comment]
See 1-4 on Owen's spec at https://docs.google.com/document/d/1VTIcE9DdVjm90rg6hVrfIOBKnY7CYIFTrQX0MbYe5us/edit

**Comment by kristenwilson** [comment]
See also #407

**Comment by ostephens** [comment]
N.B. this issue's scope has been extended as part of the spec in the Google Doc mentioned above - now covers both review tasks and creating warnings/fixes in OpenRefine

**Comment by kristenwilson** [comment]
I've set up a couple test cases, and this seems to be working well. 
https://gokb.k-int.com/gokb/resource/show/org.gokb.cred.TitleInstance%3A67236#fullTitleHistory
https://gokb.k-int.com/gokb/resource/show/org.gokb.cred.TitleInstance%3A29828#fullTitleHistory

**Comment by kristenwilson** [comment]
Accidentally closed the wrong issue.

**Comment by jhsolomon** [comment]
Is this the same issue as #428?

**Comment by kristenwilson** [comment]
Yes, #428 is a bug that relates to this issue.

**Comment by kristenwilson** [comment]
As of testing today, it appears that nos. 1 and 2 from the spec have been completed. However no. 3 (quick resolution to replace date) and no. 4 (review tasks in CRED) have still not been implemented.

**Comment by sosguthorpe** [comment]
Hi @kristenwilson. Review Tasks should be created when ingesting a project with incorrect TIPP dates. Is there a particular project you used to test?

**Comment by ianibo** [comment]
Just asking @ostephens to document some test cases for us so we can have some shared baseline for the desired behaviour - should have thought of that before - sorry!

**Comment by kristenwilson** [comment]
@sosguthorpe, I ingested the project Taylor & Francis: Open Access Journals: 20150924. It has two warnings for incorrect title history information in it that are unresolved. 

I'm not seeing any review tasks related to these though: https://gokb.k-int.com/gokb/search/index?qbe=g%3AreviewRequests&qp_status=org.gokb.cred.RefdataValue%3A399&qp_project=org.gokb.refine.RefineProject%3A67247&qp_raisedby=&qp_allocatedto=&qp_showDeleted=on&searchAction=search&searchName=

**Comment by kristenwilson** [comment]
This seems to be on the right track now. The general behavior matches the spec and is what we wanted to see.  I'm noticing just a few oddities:
1. When I ingest a project that has pre-dated and post-dated coverage dates, I'm getting review tasks for the pre-dated errors, but not the post-dated ones. See Cambridge University Press: All Titles: 20151023 or Taylor & Francis: Open Access Journals: 20150924.
2. When I use the automatic adjustment feature, it sets the date so that it is just slightly off from the date in the CRED. In one example, Animal Conservation, the PublishedTo date is 2000/01/01. But when I used the automatic adjustment in Refine, it set the DateFirstPackageIssue field to 1999-12-31T19:00:00Z. The end date behaves the same way. An end date of 2004/12/31 in the CRED was applied in Refine as 2004-12-30T19:00:00Z.
3. The problem described above also causes the warning message involving pre-dated titles to not disappear after applying the quick resolution, since using the resolution actually leads to a pre-dated date still being present. I think this will be fixed with the above, but just an FYI.

**Comment by sosguthorpe** [comment]
I do not experience any of these issues and am now thinking that this has something to do with timezones. It looks like refines "toDate()" method is applying an offset to the date based on your timezone.

**Comment by kristenwilson** [comment]
Retested and all issues are resolved.
