### ISSUE TITLE
Multi-word searching for packages does not find all expected records

### ISSUE THREAD

**Issue by ostephens** [k-int/gokb-phase1#330]
e.g. search for 'biological' finds four packages all of which contain the phrase 'biological sciences':
https://test-gokb.kuali.org/gokb/search/index?qbe=g%3A1packages&qp_name=biological&qp_showDeleted=on

but search for 'biological sciences' finds only two of these four packages:
https://test-gokb.kuali.org/gokb/search/index?qbe=g%3A1packages&qp_name=biological+sciences&qp_showDeleted=on

Similarly searching for 'decision' finds three packages all of which contain the phrase 'decision sciences':
https://test-gokb.kuali.org/gokb/search/index?qbe=g%3A1packages&qp_name=decision&qp_showDeleted=on

but search for 'decision sciences' only finds one of these three packages:
https://test-gokb.kuali.org/gokb/search/index?qbe=g%3A1packages&qp_name=decision+sciences&qp_showDeleted=on

**Comment by ianibo** [comment]
Config is applying normalisation [kbc_normname] but searching on kbc_name. Seem to recall a past issue asking for normalised name search - need to check that it's not been changed back to kbc_name for some other reason.

**Comment by ianibo** [comment]
Ah no...
Because we went with the normalised key approach, the normalised form of "decision sciences" is "decision sciences" - wheras the normalised title is [for example] "20141020 backfile decision elsevier  package sciencedirect sciences". So a search for the normalised string is not going to match. Will need discussion - and probably a move to porter stemmer, or moving back to searching on non-normalised name [Easiest for now].

**Comment by ostephens** [comment]
I still don't understand why the search finds some of the packages? Why should the search succeed for:
Elsevier: ScienceDirect Subject Collection - Decision Sciences
but not
Elsevier: ScienceDirect Backfile Package - Decision Sciences

Looking at the code I don't think the normalisation reorders words? But even if it does in both examples 'decision' and 'sciences' are not adjacent?

Am I missing something?

**Comment by ianibbo** [comment]
The contents of normname are definitely ordered!!!! I'm pretty sure of
myself on this one

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
OK - misreading that! I trust you :)
But in that case why does the first string get found?

**Comment by ianibbo** [comment]
Possible the normname has not been regenerated after a change to the
normalise routine I guess

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
OK - looks like generateComparableKey does sort but normaliseString doesn't in GOKbTextUtils.groovy - I was looking at the latter

**Comment by ianibbo** [comment]
Regenerating normnames now

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ianibbo** [comment]
Yes - and we split them out and made normalise do a more sensible thing so
that refine could continue to use the comparableKey stuff - so it looks
like the DB has titles normalised using the previous implementation of
normaliseString...

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
OK - so if the normalised titles will contain the words in the original order (once they've been regenerated), doesn't that mean the commit you've made here is no longer needed?

**Comment by ianibbo** [comment]
Yes, if thats the case - I'll back out the commit if it works

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ianibo** [comment]
Please retest now normnames regenerated.

**Comment by ostephens** [comment]
Tested on https://test-gokb.kuali.org/gokb/. Confirmed search now works as expected - a search for 'decision sciences' now finds all three records which contain this phrase

**Comment by ostephens** [comment]
Can you let me know once normrnames have been regenerated on live?

**Comment by ianibbo** [comment]
Need to restart the app to do this properly, so will do it first thing
friday when the us are sleeping.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
OK - cheers

**Comment by ostephens** [comment]
Did this get run on live? Still seeing issues searching for 'decision sciences' on live

**Comment by ianibbo** [comment]
Don't think it did... Can prolly do it now

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ianibbo** [comment]
Reindexing now..

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
Tested on live - fixed
