### ISSUE TITLE
Automated suggestion and user driven reuse of Rules (R5),2015-06

### ISSUE THREAD

**Issue by ianibo** [k-int/gokb-phase1#333]

**Comment by ostephens** [comment]
Spec document now at https://docs.google.com/document/d/1iVwleOfPcCnEbyXUTB2lwDsTQ5O9DZKDtcGxst9mtwE/edit?usp=sharing

**Comment by kristenwilson** [comment]
User driven reuse of rules is complete. Automated suggestion will be part of release 6.X. Moving this to next milestone.

**Comment by kristenwilson** [comment]
Closing this and adding a new issue for the rules work for the bulk data loader.
