### ISSUE TITLE
Linked data: Initial and ongoing real time population of Triple Store (R5),2015-03

### ISSUE THREAD

**Issue by ianibo** [k-int/gokb-phase1#338]

**Comment by iyawnis** [comment]
Does this mean we need the functionality found in GOKbLinkedDataAdapter ported to gokb in a quartz job ? Also, checking for updates instead of pulling everything..

**Comment by iyawnis** [comment]
any relation to #200

**Comment by kristenwilson** [comment]
I'm going to move this to 6.0, as it may take a while to sort out the issues with OLE that are delaying it.

**Comment by jhsolomon** [comment]
@ianibbo is this still an issue or can we close this?

**Comment by ianibo** [comment]
CLosing
