### ISSUE TITLE
If Publisher Relationship created on Ingest suggest 'Publisher From' left empty

### ISSUE THREAD

**Issue by ostephens** [k-int/gokb-phase1#37]
Currently when a Publisher Relationship is added to a TI via an ingest it is created with the "Publisher From" date set as the current date. The "Publisher To" date is set as Empty.

Suggest both dates should be Empty and setting date becomes a Review task

**Comment by ianibbo** [comment]
Note for steve: Title now has a method called changePublisher(pub_org) that
does what owen describes in this issue. It's used in the title transfer
workflow. I'm currently extending it not to do anything if the pub you're
asking it to use is already the current.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
Still behaves the same following latest update - see http://gokb.k-int.com/gokb/resource/show/org.gokb.cred.TitleInstance%3A33032 - Cambridge University Press publisher added this morning via ingest

**Comment by ostephens** [comment]
Fixed with latest update
