### ISSUE TITLE
Software Release (Lab Branch),13.4 Ð Merge approved functionality with GOKb service branch (R6.0.n),2015-12

### ISSUE THREAD

**Issue by ianibo** [k-int/gokb-phase1#385]

**Comment by kristenwilson** [comment]
Do we still want to consider merging Labs with main branch as part of this release?

**Comment by kristenwilson** [comment]
Consider merging a copy of GOKb live onto the labs brach for testing.

**Comment by kristenwilson** [comment]
Already complete
