### ISSUE TITLE
"Last Updated" field is updated when a user view a TIPP or Title record

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#397]
The Last Updated field on the TIPP and Title records is updated whenever a user views one of these records, regardless of if they have made any changes. These fields should be updated only if a user edits a field on one of these records. I have not seem the issue on other record types so far.

**Comment by iyawnis** [comment]
I cant find a way of recreating this locally or on gokb.k-int.com... Could I have some more details on the steps taken/ specific resources involved? I tried viewing them directly, or for titles through quick view as well.

**Comment by kristenwilson** [comment]
I'm now unable to reproduce this either, though I have seen it and and had a couple different users report it. I'll leave this issue open and provide more info if I figure out more about what's happening.
