### ISSUE TITLE
Title record returning strange error

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#398]
When trying to view the record for the title Composites Engineering, we're seeing an error message that reads: 

Error 500 - Internal Server Error.
Error processing GroovyPageView: Error executing tag : Negative array index [-1] too large for array size 0

Any ideas what would produce this?

See: http://gokb.kuali.org/gokb/resource/show/org.gokb.cred.TitleInstance%3A49374

**Comment by iyawnis** [comment]
Hm.. since its on kuali I cant access it.. is this the only text returned, or is there a full grails exception? If there is more can you attach a screenshot please?

**Comment by ostephens** [comment]
Only the text is returned - screenshot below

![screen shot 2015-03-02 at 09 50 29](https://cloud.githubusercontent.com/assets/576174/6438520/a437adc2-c0c1-11e4-9d2b-cbb2087718c7.png)

**Comment by iyawnis** [comment]
Right... this is going to be tricky without access to server logs.. ill talk with steve.

**Comment by iyawnis** [comment]
Note to self:
Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag <g:render>: null
    at gsp_gokb_resourceshow_gsp$_run_closure2.doCall(gsp_gokb_resourceshow_gsp.groovy:77)
    at gsp_gokb_resourceshow_gsp.run(gsp_gokb_resourceshow_gsp.groovy:89)
    ... 10 more
Caused by: java.lang.NullPointerException

**Comment by ianibbo** [comment]
This exception looks to be coming from the g:renderException tag itself -
thus it's an exception throw whilst processing an error. The
g:renderException tag seems to make an assumption about there being an
exception present.

looking in error.gsp, I'd suggest changing

<g:renderException exception="${exception}" />

to

```
    <g:if test="${exception != null}">
        <g:renderException exception="${exception}" />
     </g:if>
```

At least in the first place to see if this stops the outer exception - then
we need to find out why the error page is being called.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ianibbo** [comment]
I think the root problem is here::

345:      if ( ( from_titles?.size() == 1 ) && ( to_titles?.size() == 1 )
&& ( from_titles[0].participant.id != to_titles[0].participant.id ) ) {
346:        hint="Rename"
347:      }

Where the code assumes that participant is set - suspect it is not in this
case for some reason!

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by iyawnis** [comment]
This was the root problem indeed. Double checking everything and fix inc soon.
