### ISSUE TITLE
Some users unable to ingest project through Refine

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#399]
Some users are receiving errors messages when they try to ingest Refine projects into GOKb, and the ingest fails. A screenshot is below: 

![cannot_retrieve_content_2015-03-02_1004](https://cloud.githubusercontent.com/assets/7397776/6451685/2929ebc6-c0fe-11e4-8ca8-05ecc8bc754c.png)

Along with this error, these same users have reported that when they check the package status in Open Refine, the packages don't appear to be checked out, even though they can work on them in Open Refine. They still say they are checked in.

I have not been able to reproduce these errors even though I am using the same Windows computer and same browser (Firefox).

**Comment by kristenwilson** [comment]
Update: We found that this error is only occurring if we try to upload Imprints using the new column and imprint look up values. If we delete this column, the ingest works. Would it be possible to look into a fix soon? We've updated a lot of our macros to include imprints, so we're now unable to do any updates until this is fixed.

**Comment by iyawnis** [comment]
@kristenwilson Can you confirm that this works as expected on gokb.k-int.com ?

**Comment by kristenwilson** [comment]
Confirmed working on K-Int test platform.

**Comment by iyawnis** [comment]
Thats good news. I will notify you tomorrow as soon as it is deployed on
live.
