### ISSUE TITLE
KBartEmbargo not showing in Web UI

### ISSUE THREAD

**Issue by ostephens** [k-int/gokb-phase1#4]
Ingested a TIPP with a value in KBARTEmbargo col in the Refine project, but not displaying in Web UI. Relevant TIPP is http://gokb.k-int.com/gokb/resource/show/org.gokb.cred.TitleInstancePackagePlatform%3A7186

**Comment by ianibo** [comment]
Is the value (/should the value be) "6 months"? Or is the value appearing to the right of End Issue something else? (Or has steve popped a fix in?)

**Comment by ostephens** [comment]
Yes - apologies
