### ISSUE TITLE
Can't unlink combo

### ISSUE THREAD

**Issue by ianibo** [k-int/gokb-phase1#40]
Have added an unlink option to the combo list include. This can be seen on the Org display lists tab. Clicking "Unlink" fires off the AjaxSupportController::unlinkManyToMany method which ultimately calls remove on the combo set. However this doesn't seem to be removing the link combo. 

Could you investigate pls steve? (P.S. Go to a title and navigate to a tipp from there to land on an org with some linked tipps/titles)

**Comment by ianibo** [comment]
Temporarily worked around by adding an hard delete version in _combosByType.gsp which deals with the list of combos of a type rather than the meta-property at the component level. Could make it soft delete instead... Need to discuss with @ostephens

**Comment by ostephens** [comment]
This works, but now cannot remember why it was required :( sorry
