### ISSUE TITLE
Don't show deleted titles in the search results for Before/After fields in title change event

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#402]
Currently, deleted titles are showing in the search results for the Before and After fields on the title change event tab. If there are multiple versions of a title, it's impossible to tell which is the active one.

Example: http://screencast.com/t/Cu6IUnkDS5a

**Comment by iyawnis** [comment]
This should not be labelled as bug, as search type downs work like this across the system, and do not  apply any filtering anywhere. Extending them to filter deleted items should be possible and I am looking into this now.

**Comment by kristenwilson** [comment]
Thanks. I think that all type downs across the system should exclude deleted items. If something is deleted, it means we don't want people doing anything with it anymore, so it's better to remove the possibility that could happen by accident.
