### ISSUE TITLE
Curator Dashboard 

### ISSUE THREAD

**Issue by iyawnis** [k-int/gokb-phase1#405]
This is the curator dashboard that has been made, based on the draft spec. @kristenwilson  does it meet your expectations? Is it missing anything ?

![screenshot from 2015-03-26 12 59 58](https://cloud.githubusercontent.com/assets/2336352/6846690/0ceedba2-d3b8-11e4-9d6b-9b565655d843.png)

**Comment by iyawnis** [comment]
Deleted/Closed review requests are not visible, and there is no option to show them.

**Comment by ianibo** [comment]
How does the det and offset parameters work if there are 2 lists on the one
screen? Won't they get confused? That was the reason for the "First 20"
approach before.

e

On 26 March 2015 at 12:44, Ioannis Latousakis notifications@github.com
wrote:

> This is the curator dashboard that has been made, based on the draft spec.
> @kristenwilson https://github.com/kristenwilson does it meet your
> expectations? Is it missing anything ?
> [image: curator_dash]
> https://cloud.githubusercontent.com/assets/2336352/6846387/cec54386-d3b5-11e4-93f4-94782b28b9b3.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/k-int/gokb-phase1/issues/405.

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo
GoodReads: https://www.goodreads.com/user/show/3106516-ian-ibbotson

**Comment by iyawnis** [comment]
I added a pagination template under group/ , and I am passing a parameter name for offset, so they increment different offsets `params="${params+["${offset_param}": ...` . I didnt need `det` yet so I havent checked what is its use..

**Comment by iyawnis** [comment]
I made some small additions to the search pagination template and now it works for both. Its current behaviour hasnt changed on existing pages. Unless kristen got any feedback this screen is done.

**Comment by kristenwilson** [comment]
Ioannis, this looks good to me so far. Thanks!

**Comment by kristenwilson** [comment]
It appears that the dashboard option has disappeared from the CRED. Can we get this back in, then I will do some final testing. Thanks!

**Comment by ianibo** [comment]
Heya - The "My Groups" menu option only appears if the user has a group. To double check - Search -> Curatory Groups and make sure at least one exists. If not Create -> Curatory Group. Then go to the User -> My Profile top right and add a group to the list of the users curatory groups. Seems to be OK for me, closing here - Tested on http://test-gokb.kuali.org/gokb/home/profile using admin user and OhioLink CG. Please open new issue if the problem persists.

**Comment by jhsolomon** [comment]
Would it be possible to link to the review tasks from the Curator Panel? Would it also be possible to close multiple review requests from the Curator Panel?
