### ISSUE TITLE
Users unable to check-in projects

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#409]
Multiple users have reported an issue in OpenRefine where they are unable to check in projects or reopen projects. This generally occurs after the initial check in. The user works on the project for the first time, checks it in, and then exits OpenRefine. When they log back in, the project displays as checked out, but there is no option to open it or check it back in. This issue is not occurring for all users and I cannot reproduce it myself.

**Comment by sosguthorpe** [comment]
Have an incline this may have now gone away as a result of version 4.2.4 being released to fix #410.

Can you please ask the users to recheck?
