### ISSUE TITLE
Co-reference service returns multiple records for same TI

### ISSUE THREAD

**Issue by ostephens** [k-int/gokb-phase1#41]
e.g. http://gokb.k-int.com/gokb/coreference/index?nspart=issn&idpart=0590-8876&format=xml

Returns three identical entries. My wild guess would be that this is because of the variant titles attached to the TI? The same TI on Kuali.org instance (where there are currently no variant titles) returns single record

http://gokb.kuali.org/gokb/coreference/index?nspart=issn&idpart=0590-8876&format=xml

NB wanted to log this, but not urgent to fix

**Comment by sosguthorpe** [comment]
Think this is actually linked to the multiple Identifiers issue #38

**Comment by ostephens** [comment]
Seems to have been fixed as a result of fixing #38
