### ISSUE TITLE
No projects displaying on the My Projects tab in Refine

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#410]
Some users have having an issue where nothing is displaying on the My Projects tab in Refine, despite these users having projects for which they are the creator. Not all users are having this problem and I cannot recreate it myself. It appears that the users having this problem are also having the issue reported in #409.

**Comment by sosguthorpe** [comment]
@kristenwilson Can you please mail me with a users details that are experiencing this problem so I can attempt to replicate the issue locally please?

**Comment by kristenwilson** [comment]
Here are two users:
smulewi
Teddy Gray

On Fri, May 29, 2015 at 8:25 AM, sosguthorpe notifications@github.com
wrote:

> @kristenwilson https://github.com/kristenwilson Can you please mail me
> with a users details that are experiencing this problem so I can attempt to
> replicate the issue locally please?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/k-int/gokb-phase1/issues/410#issuecomment-106788263.

## 

Kristen Wilson
Associate Head, Acquisitions and Discovery
GOKb Editor
North Carolina State University Libraries
919-513-3354
kristen_wilson@ncsu.edu

**Comment by sosguthorpe** [comment]
Should now be fixed. Merged as Hotfix onto release branch and pushed out to all users. Clients should auto update to version 4.2.4.
