### ISSUE TITLE
Quick resolutions are broken in OpenRefine

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#411]
The quick resolutions menu is broken in OpenRefine. When you try to open the menu for any of the error or warning messages, you just get a message that says "no available actions." This is urgent to fix as it's a core piece of functionality.

**Comment by iyawnis** [comment]
Updated client available from https://gokb.k-int.com/gokb/api/downloadUpdate

**Comment by kristenwilson** [comment]
Confirmed that this is fixed. Thanks!

**Comment by kristenwilson** [comment]
@latusaki I was using Refine a bit more extensively and noticed there are still a few issues with the quick resolutions. Some of them fine work (renaming columns, appending columns), but others do not. The ones I've seen so far that are broken are creating facets for invalid values and doing the date conversions. Can you check into these?

**Comment by iyawnis** [comment]
Sorry for this. I only had the rename/append columns available while testing as well, will check now.

**Comment by iyawnis** [comment]
I have tested that facets and date conversions work, and double checked with steve, there should be no more issues with this. The fixed version is available from  https://gokb.k-int.com/gokb/api/downloadUpdate

**Comment by kristenwilson** [comment]
Thanks, Ioannis. Tested this morning and looks like everything is working.
