### ISSUE TITLE
Global search not working at all on test

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#413]
Currently all global searches performed on test lead to an error page.

**Comment by julianladisch** [comment]
https://test-gokb.kuali.org/gokb/globalSearch/index?q=foobar
gives this error message:

Error 500: Internal Server Error

```
URI      /gokb/globalSearch/index
Class    org.elasticsearch.cluster.block.ClusterBlockException
Message  blocked by: 
         [SERVICE_UNAVAILABLE/1/state not recovered / initialized];
         [SERVICE_UNAVAILABLE/2/no master];
```

**Comment by ianibo** [comment]
Back now - ES was down. Please don't  use github for reporting operational / infrastructure issues, but only for software / dev issues. Probably best to stick with email for other stuff. We have a Zendesk instance available to supported customers.
