### ISSUE TITLE
CRED: Package download options need to be available without edit permissions

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#414]
I just learned that the ability to do the kbart and tsv exports for packages is tied to the permission to be able to edit packages. These options really should be available to all users. I don't know if this can be considered a bug, but I never intended to have that functionality restricted. The ability to provide easy exports of package files is one of our big selling points for publishers and consortia, so we need to fix this soon. Do you think this could be done in 5.0?

**Comment by ianibo** [comment]
New /packages endpoint

**Comment by jhsolomon** [comment]
I do not see this option in my view-only account. I can see that there is now a way to save a search, but there is no way to download a package or the items in my saved folder.

![image](https://cloud.githubusercontent.com/assets/13369381/13611007/5fdb7c16-e52e-11e5-945d-52b4b9f0b11f.png)

**Comment by jhsolomon** [comment]
When I go to http://test-gokb.kuali.org/gokb/packages  I can search for packages, but get an error when I click on the package link.

![image](https://cloud.githubusercontent.com/assets/13369381/13611204/48cf5186-e52f-11e5-9416-9433e350111d.png)

![image](https://cloud.githubusercontent.com/assets/13369381/13611212/55ee74c8-e52f-11e5-9a8b-d008216909a0.png)

**Comment by ianibbo** [comment]
This should be available from the /packages endpoint

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ianibbo** [comment]
Ack OK thanks - this is obvs broken.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by jhsolomon** [comment]
Would there be a way to integrate this into the package record?

On Tue, Mar 8, 2016 at 1:40 PM, ianibbo notifications@github.com wrote:

> Ack OK thanks - this is obvs broken.
> 
> Ian Ibbotson
> Director
> Knowledge Integration Ltd
> 35 Paradise Street, Sheffield. S3 8PZ
> T: 0114 273 8271
> M: 07968 794 630
> W: http://www.k-int.com
> 
> On 8 March 2016 at 18:12, jhsolomon notifications@github.com wrote:
> 
> > When I go to http://test-gokb.kuali.org/gokb/packages I can search for
> > packages, but get an error when I click on the package link.
> > 
> > [image: image]
> > <
> > https://cloud.githubusercontent.com/assets/13369381/13611204/48cf5186-e52f-11e5-9416-9433e350111d.png
> > 
> > [image: image]
> > <
> > https://cloud.githubusercontent.com/assets/13369381/13611212/55ee74c8-e52f-11e5-9a8b-d008216909a0.png
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/k-int/gokb-phase1/issues/414#issuecomment-193896886
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/k-int/gokb-phase1/issues/414#issuecomment-193907935.

## 

Jennifer Solomon
GOKb Editor, Acquisitions and Discovery
North Carolina State University Libraries
919-515-2743
j kristen_wilson@ncsu.eduhsolomo@ncsu.edu

**Comment by ianibo** [comment]
Yeah we can add a link if that will be sufficient

On 8 March 2016 at 19:59, jhsolomon notifications@github.com wrote:

> Would there be a way to integrate this into the package record?
> 
> On Tue, Mar 8, 2016 at 1:40 PM, ianibbo notifications@github.com wrote:
> 
> > Ack OK thanks - this is obvs broken.
> > 
> > Ian Ibbotson
> > Director
> > Knowledge Integration Ltd
> > 35 Paradise Street, Sheffield. S3 8PZ
> > T: 0114 273 8271
> > M: 07968 794 630
> > W: http://www.k-int.com
> > 
> > On 8 March 2016 at 18:12, jhsolomon notifications@github.com wrote:
> > 
> > > When I go to http://test-gokb.kuali.org/gokb/packages I can search for
> > > packages, but get an error when I click on the package link.
> > > 
> > > [image: image]
> > > <
> > 
> > https://cloud.githubusercontent.com/assets/13369381/13611204/48cf5186-e52f-11e5-9416-9433e350111d.png
> > 
> > > [image: image]
> > > <
> > 
> > https://cloud.githubusercontent.com/assets/13369381/13611212/55ee74c8-e52f-11e5-9a8b-d008216909a0.png
> > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/k-int/gokb-phase1/issues/414#issuecomment-193896886
> > > .
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/k-int/gokb-phase1/issues/414#issuecomment-193907935
> > .
> 
> ## 
> 
> Jennifer Solomon
> GOKb Editor, Acquisitions and Discovery
> North Carolina State University Libraries
> 919-515-2743
> j kristen_wilson@ncsu.eduhsolomo@ncsu.edu
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/k-int/gokb-phase1/issues/414#issuecomment-193943396.

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo
GoodReads: https://www.goodreads.com/user/show/3106516-ian-ibbotson

**Comment by jhsolomon** [comment]
I think that would be helpful, otherwise I'm not sure that view-only users
will understand how to get to the download page.

On Tue, Mar 8, 2016 at 3:07 PM, Ian Ibbotson notifications@github.com
wrote:

> Yeah we can add a link if that will be sufficient
> 
> On 8 March 2016 at 19:59, jhsolomon notifications@github.com wrote:
> 
> > Would there be a way to integrate this into the package record?
> > 
> > On Tue, Mar 8, 2016 at 1:40 PM, ianibbo notifications@github.com
> > wrote:
> > 
> > > Ack OK thanks - this is obvs broken.
> > > 
> > > Ian Ibbotson
> > > Director
> > > Knowledge Integration Ltd
> > > 35 Paradise Street, Sheffield. S3 8PZ
> > > T: 0114 273 8271
> > > M: 07968 794 630
> > > W: http://www.k-int.com
> > > 
> > > On 8 March 2016 at 18:12, jhsolomon notifications@github.com wrote:
> > > 
> > > > When I go to http://test-gokb.kuali.org/gokb/packages I can search
> > > > for
> > > > packages, but get an error when I click on the package link.
> > > > 
> > > > [image: image]
> > > > <
> > 
> > https://cloud.githubusercontent.com/assets/13369381/13611204/48cf5186-e52f-11e5-9416-9433e350111d.png
> > 
> > > > [image: image]
> > > > <
> > 
> > https://cloud.githubusercontent.com/assets/13369381/13611212/55ee74c8-e52f-11e5-9a8b-d008216909a0.png
> > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > > > https://github.com/k-int/gokb-phase1/issues/414#issuecomment-193896886
> > > > .
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/k-int/gokb-phase1/issues/414#issuecomment-193907935
> > > .
> > 
> > ## 
> > 
> > Jennifer Solomon
> > GOKb Editor, Acquisitions and Discovery
> > North Carolina State University Libraries
> > 919-515-2743
> > j kristen_wilson@ncsu.eduhsolomo@ncsu.edu
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/k-int/gokb-phase1/issues/414#issuecomment-193943396
> > .
> 
> ## 
> 
> Ian Ibbotson
> W: http://ianibbo.me
> E: ianibbo@gmail.com
> skype: ianibbo
> twitter: ianibbo
> GoodReads: https://www.goodreads.com/user/show/3106516-ian-ibbotson
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/k-int/gokb-phase1/issues/414#issuecomment-193946569.

## 

Jennifer Solomon
GOKb Editor, Acquisitions and Discovery
North Carolina State University Libraries
919-515-2743
j kristen_wilson@ncsu.eduhsolomo@ncsu.edu

**Comment by jhsolomon** [comment]
I rechecked and am still getting the "Error 500: Internal Server Error" for both the package and the kbart download.

**Comment by jhsolomon** [comment]
tested in Chrome and Firefox.

package export is working from both the package record "public kbart" link and the http://test-gokb.kuali.org/gokb/packages endpoint.

fix confirmed. @kristenwilson please test.

**Comment by ianibo** [comment]
Add second button for alternate export, remove menu options. Call TSV/CSV Export GoKB Export

**Comment by jhsolomon** [comment]
The KB+File download is giving  me an error:
![image](https://cloud.githubusercontent.com/assets/13369381/14252820/ec79b862-fa56-11e5-9494-cab3a328cae5.png)

Could we change the link name to GOKb File? KB+ is a little confusing to me.

**Comment by jhsolomon** [comment]
On the http://test-gokb.kuali.org/gokb/packages endpoint, can we change "Public Kbart" to "Download Kbart file"?

**Comment by ianibo** [comment]
Tested - packages endpoint now says download Kbart file
![image](https://cloud.githubusercontent.com/assets/53283/14298277/007655ac-fb7c-11e5-848f-50ec3f3be982.png)

Tested KBart and GoKB download links from package screen. All appears to match. Re-adding retest label, removing Ian review label. Please update or close accordingly.

**Comment by jhsolomon** [comment]
Thank you! Package downloads are working in Chrome and Firefox. 

On the package page, can you change "GoKB File" to "GOKb File"? Sorry to be picky...

**Comment by jhsolomon** [comment]
fix confirmed

**Comment by kristenwilson** [comment]
I downloaded several files of both types for a few different packages. They were all empty. The KBART file did at least have headers, but the GOKb file was completely blank. @jhsolomon did you not find this when you tested?

**Comment by jhsolomon** [comment]
I just re-tested this and the GOKb file was blank and the KBART file had the column headers. From the http://test-gokb.kuali.org/gokb/packages page, the KBART file only had the column headers.

**Comment by ianibbo** [comment]
Ack - sorry guys - Introduced a bug adding the download date into the
filename that is causing the action to bomb out prematurely. Fixing.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ianibbo** [comment]
Think I introduced this last night - which might by why it suddenly appears
broken - fixing now. Sorry.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by jhsolomon** [comment]
fix confirmed

**Comment by kristenwilson** [comment]
Confirmed fixed.
