### ISSUE TITLE
Global search is broken in 5.0 beta

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#419]
In the 5.0 beta version of GOKb, I can preform global searches, but clicking on any search result leads to an error screen. http://screencast.com/t/saoWCybzQ9js

**Comment by ostephens** [comment]
Some results work from global search results. If I were to guess I'd say that the fulltext index needs re-building on test to get rid of results that no longer exist. Do you want me to try a Reset Free Text Index @kristenwilson ?

**Comment by ianibbo** [comment]
Do you have access to the administration menu full reset option? Cam look
at scripting this in the deploy script later on.

**Comment by ostephens** [comment]
@ianibbo - thought I did, but trying it I get 'access denied' (I can see the menu option, but not use it)

**Comment by ianibo** [comment]
Just tried this and it seems fine. Closing the original issue, please raise a new one if it's broken again. Owen - what shall we do about the access denied - how did you log in?

**Comment by jhsolomon** [comment]
The search is working, but I get very different results if I search for "wiley" vs "wiley-blackwell" or "oxford" vs "oxford university press."
