### ISSUE TITLE
"Capture edits" check box not always displaying

### ISSUE THREAD

**Issue by ostephens** [k-int/gokb-phase1#421]
For the cell level edits 'Capture edits' check box is not displaying in all cases. E.g. if the row you are editing isn't on the first page of the Refine project. E.g. - on first page displays fine:

<img width="949" alt="screen shot 2015-09-18 at 16 43 22" src="https://cloud.githubusercontent.com/assets/576174/9963717/8a4951e4-5e24-11e5-83a1-2018f4767f51.png">

On next page doesn't:
<img width="956" alt="screen shot 2015-09-18 at 16 43 36" src="https://cloud.githubusercontent.com/assets/576174/9963734/97166aec-5e24-11e5-8b6c-04ea1bfa5882.png">

Also seems to have issues when you've applied Filters to a col.

Looking at browser javascript console I'm seeing:
[Error] TypeError: undefined is not an object (evaluating 'theProject.rowModel.rows[self._rowIndex].cells')
    (anonymous function) (project-bundle.js, line 49383)
    each (project-bundle.js, line 385)
    _extendEdit (project-bundle.js, line 49376)
    (anonymous function) (project-bundle.js, line 49569)
    _startEdit
    (anonymous function) (project-bundle.js, line 35387)
    dispatch (project-bundle.js, line 4643)
    handle (project-bundle.js, line 4311)

<img width="1193" alt="screen shot 2015-09-18 at 16 46 48" src="https://cloud.githubusercontent.com/assets/576174/9963781/e6ffa69a-5e24-11e5-8a38-8b271b2c65d4.png">

**Comment by kristenwilson** [comment]
I've also found that the checkbox does not appear when a filter is applied.

**Comment by kristenwilson** [comment]
This is fixed now.
