### ISSUE TITLE
KBART2 export is missing several fields

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#424]
The KBART2 export is missing several of the new fields added for KBART phase 2. 

It seems like we could easily include a couple of these fields based on the data we have now.
- publication_type: This could be populated from the medium field on the title record.
- access_type: This could be populated from the payment type field on the TIPP

The following fields are specific to monographs, so we won't be able to populate them now. I wonder if it would be good form to include them as blank columns in our export to show that we are aware of the revisions to KBART. That seems to be what most publishers are doing. We should also consider how we could provide this data as part of the ebooks implementation. 
- date_monograph_published_print
- date_monograph_published_online
- monograph_volume
- monograph_edition
- first_editor
  parent_publication_title_id

**Comment by ianibo** [comment]
These are omitted for the moment being books fields - and will only apply to Titles subclassed as books - we can add them as blank columns if needed. I think parent_publication_title is in there tho?

Would you like the columns in there and with blank values? Happy to do so if thats the case.

Ian.

**Comment by ianibo** [comment]
Just checked and preceding_publication_title_id is present, parent is not - parent is for conference proceedings I think and we don't currently have a place to store that. Happy to add a field and the output, or to leave blank, or continue to omit. Omitting fields does not invalidate the kbartness of the file, and it seems more appropriate not to supply fields if they are irrelevant, but happy to be guided. Please add comments to this issue and we'll fix tomorrow.

**Comment by kristenwilson** [comment]
Thinking about this more, I'm fine with omitting the book-specific fields. But it does seem like publication_type and access_type should be present in all cases. Could we add in just those two?

**Comment by ianibbo** [comment]
Sure

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by jhsolomon** [comment]
Fix confirmed

**Comment by kristenwilson** [comment]
Actually, it looks like there's a small error with the export. The data in the parent_publication and access_type fields (and probably parent_publication_id) is shifted one column to the left so that this data appears in the wrong field. 

![2015-10-12_1557](https://cloud.githubusercontent.com/assets/7397776/10437280/fbb0979c-70f9-11e5-9b65-63c5710d5417.png)

**Comment by jhsolomon** [comment]
Retested and the export is still showing the error above. (The data in the parent_publication and access_type fields (and probably parent_publication_id) is shifted one column to the left so that this data appears in the wrong field.)

I also noticed that the dates did not export.

![image](https://cloud.githubusercontent.com/assets/13369381/10457539/dc9e430e-7194-11e5-8d0d-a9eaca1cf30a.png)

**Comment by kristenwilson** [comment]
Confirmed fixed.
