### ISSUE TITLE
Can't select columns to use as conditions for cell level edits

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#425]
In testing the the cell-level edits functionality, I can't choose the columns to use as conditions for the edit. The check-box for "capture edit" is present, but when I select it, I don't get any column selection ability. 

![2015-09-23_1217](https://cloud.githubusercontent.com/assets/7397776/10051044/7ba053a0-61ed-11e5-9aeb-a3cbdbd69436.png)

**Comment by sosguthorpe** [comment]
This is because only GOKb recognised column names can be used in the conditions of the edit. Perhaps we should include a message that states there are no columns with valid names yet?

**Comment by kristenwilson** [comment]
Ah, of course. Yes, I think it would be good to have a message so people remember they have to fix the column names first.

**Comment by kristenwilson** [comment]
Confirmed this is fixed.
