### ISSUE TITLE
Title history warning messages not being generated?

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#428]
I've been unable to get any title history warning messages to display, even when I know the coverage dates in the Refine project contradict the publication dates in GOKb. Not sure if I'm missing something or if there's a problem.

Example:

Refine project: Taylor & Francis: Open Access Journals: 20150924
GOKb: https://gokb.k-int.com/gokb/resource/show/org.gokb.cred.TitleInstance%3A59327

In Refine, the title Green Chemistry Letters and Reviews has coverage dates of 2012/03/01-2015/12/31. In GOKb, I've given it fake publication dates of 2014/01/01-2014/12/31. So this should generate warnings for both predating the start date and post-dating the end date.

I've confirmed that the title in the Refine project matches the title record in GOKb on ISSN and e-ISSN.

I did just enter the publication dates into GOKb this morning -- not sure if that could have any effect. 

See #327

**Comment by jhsolomon** [comment]
This issue is not yet fixed. I was able to add false data with no warnings.

**Comment by jhsolomon** [comment]
Retested and still did not receive a warning message.

**Comment by kristenwilson** [comment]
Title history warning messages are now being generated.
