### ISSUE TITLE
Move full title history to main title history section (remove tab)

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#430]
At our call last Friday, we talked about the idea of moving the full title history up to the main title history section, rather than having it on a separate tab. I like this idea, but I wonder if it could be problematic if the title history chain was too long? Would it be possible to do something like by default only showing the changes affecting the title currently viewed, then have a "show more..." link to expand? 

We should also consider which headings we prefer for the table. I like the ones that are on the "full TH" tab right now. They're a bit clearer than what's in the main title history section. Any objections to using that language?

**Comment by jhsolomon** [comment]
These changes have not been made. @kristenwilson Do we want to hold this for 6.0?

I like your suggestion to use the "On this date This/These titles   Changed to This/These titles" instead of the before/after.

**Comment by kristenwilson** [comment]
We talked about this on a previous call and Ian said that any UI tweaks to this functionality could be done as part of 5.0. I'd like to keep it in this release if possible.

**Comment by ianibo** [comment]
Done

**Comment by kristenwilson** [comment]
This looks good. Some questions/small things:

(Here's an example that illustrates all of these:  https://gokb.k-int.com/gokb/resource/show/org.gokb.cred.TitleInstance%3A21944)
1. In the old display, the name of the title you were currently looking at was bolded. Can we get this back? I think it's especially important with a longer display to remember what title record you're on. 
2. Can we get a line break in between titles if there is more than one title in the same cell? Otherwise, it's not very clear that multiple titles were affected. This was also in the old display
3. The publication dates are also not displaying in the grid the way they used to. 
4. It looks like the show less/show more toggle was not implemented. Do we think this is needed for long histories? I created a fairly long example and I don't think it looks excessively long, but I'd like to hear others' opinions.

**Comment by ianibo** [comment]
Is the example you created the one you expect show more/less on? If so, whats the magic number at which the button should show?

**Comment by kristenwilson** [comment]
I had it in mind as >2. So essentially we'd preserve the old model where only the immediate before and after lines for a given title show up by default, then the "show more" would expand to the complete history. But I realize I didn't actually document that anywhere -- sorry! What do you think?

**Comment by ianibo** [comment]
Sounds good - ok wil try and get that changed before the call

**Comment by kristenwilson** [comment]
The "show hidden" button is now present. Immediate title history information (2 lines) for the title is shown by default. Clicking the "show hidden" button expands to the full title history.

 There are still a couple issues:
1. Would it be possible to have the button say "show more" instead of "show hidden"? I think this is more standard language.
2. After clicking "show hidden" to display the full title history, the button still says "show hidden." At this point, however, there's nothing hidden anymore. Would it be possible to have the button say "show less" when the full history is already displayed?
3. Currently, if you click "show hidden" when the full title history is already displaying, it will collapse the display so that all title history is hidden. Would it be possible to return the display to the initial state where only 2 lines are displaying?
