### ISSUE TITLE
Quick resolution for no data in issn/eissn cols doesn't work

### ISSUE THREAD

**Issue by ostephens** [k-int/gokb-phase1#44]
Getting warning message:
"One or more rows contain no data in both column "title.identifier.issn" and "title.identifier.eissn"

Quick Resolution offers to 'create facet'
Facet contains no information

**Comment by ostephens** [comment]
Ah - realised that several of the 'Quick resolutions' don't work if there is invalid data in the relevant cols. In this case invalid ISSNs/eISSNs were present. Once these resolved the Quick Resolution facet worked fine

**Comment by sosguthorpe** [comment]
Looking locally I can't seem to produce the behavior specified here. Do you have a specific example?

**Comment by ostephens** [comment]
Cannot recreate
