### ISSUE TITLE
Ingest: Update method attribute

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#450]
Create an attribute that identifies the source of the last update to the component -- Refine, TSV import, manual

**Comment by jhsolomon** [comment]
@ianibo Can you tell me where this is located in the package record? For some reason, I don't see it...

**Comment by ianibo** [comment]
![image](https://cloud.githubusercontent.com/assets/53283/13904264/6385d95c-ee92-11e5-956f-fb5fdf0fc3ae.png)

**Comment by jhsolomon** [comment]
thank you!

**Comment by jhsolomon** [comment]
When I loaded a package through Refine, the "Update Method" did not auto-populate, but it did allow me to type in the update method. Is this the correct functionality?

Also, at the bottom of the page, the "Last updated by" field did not update. It should have my username since I was the person who updated it on 3/22/2016.

http://test-gokb.kuali.org/gokb/resource/show/org.gokb.cred.Package%3A100455

**Comment by jhsolomon** [comment]
The update method is not auto-populating, but it will allow me to type in the update method. Is this the correct workflow?

http://test-gokb.kuali.org/gokb/resource/show/org.gokb.cred.Package%3A291568

The last updated field did not change when I ingested the package. It should have my username, not the username of the person who created the package.

Is this related to the package not fully ingesting in Refine?

**Comment by ianibo** [comment]
AAAH... last updated by rather than ingest method? So there are different things - how the package was updated - refine, direct ingest, etc [Method] and person - a user - it's the person that isn't updating, right -- So we want a pseudo user called "Auto" that represents the automated ingest? Sorry for being dense -- can you confirm I've now understood?

**Comment by jhsolomon** [comment]
Yes, that's correct. Thanks!

On Sun, Apr 3, 2016 at 5:19 AM, Ian Ibbotson notifications@github.com
wrote:

> AAAH... last updated by rather than ingest method? So there are different
> things - how the package was updated - refine, direct ingest, etc [Method]
> and person - a user - it's the person that isn't updating, right -- So we
> want a pseudo user called "Auto" that represents the automated ingest?
> Sorry for being dense -- can you confirm I've now understood?
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/k-int/gokb-phase1/issues/450#issuecomment-204923315

## 

Jennifer Solomon
GOKb Editor, Acquisitions and Discovery
North Carolina State University Libraries
919-515-2743
j kristen_wilson@ncsu.eduhsolomo@ncsu.edu

**Comment by jhsolomon** [comment]
The user is now updating. Confirmed fix.

**Comment by kristenwilson** [comment]
I updated a package using Refine and the update method was not populated. I'm unsure of the status of the bulk uploader, so I have not tested that. However, I believe the point of this field is that it should be auto-populated during ingest.

**Comment by jhsolomon** [comment]
The Update Method field is still not populating, but the Last Updated By is working. 

![image](https://cloud.githubusercontent.com/assets/13369381/14336795/7ce33c18-fc35-11e5-8826-663815db4088.png)

![image](https://cloud.githubusercontent.com/assets/13369381/14336807/b20bf510-fc35-11e5-817e-cf9ebb6ca6f3.png)

**Comment by ianibo** [comment]
Looking at http://test-gokb.kuali.org/gokb/resource/show/org.gokb.cred.Package:88993 I can see the message updated by refine... Does this look right? 
![image](https://cloud.githubusercontent.com/assets/53283/14354135/11735a68-fcd4-11e5-9e2f-09ec779b2e9f.png)

**Comment by jhsolomon** [comment]
Yes, that field is correct, but now the Last Updated by has the wrong
username.
Last updated by lamadden

On Thu, Apr 7, 2016 at 10:18 AM, Ian Ibbotson notifications@github.com
wrote:

> Looking at
> http://test-gokb.kuali.org/gokb/resource/show/org.gokb.cred.Package:88993
> I can see the message updated by refine... Does this look right?
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/k-int/gokb-phase1/issues/450#issuecomment-206927137

## 

Jennifer Solomon
GOKb Editor, Acquisitions and Discovery
North Carolina State University Libraries
919-515-2743
j kristen_wilson@ncsu.eduhsolomo@ncsu.edu

**Comment by ianibo** [comment]
Ok - Refine processing will now additionally overwrite the last updated by field with the username of the refine user. Updating test shortly.

**Comment by jhsolomon** [comment]
fix confirmed

**Comment by kristenwilson** [comment]
fix confirmed
