### ISSUE TITLE
Ingest: Source file mapping

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#451]
Provide mechanism for editors to map Source Files being ingested to existing packages and platforms so we know which TIPPS to create / update (e.g. a CUFTS file potentially duplicates packages and platforms already ingested)

**Comment by ianibo** [comment]
The most efficient way to get cufts data in is to have a command of the form

  curl -v --user admin:admin -X POST \
    --form content=@./$cufts_file \
    --form source="CUFTS" \
    --form fmt="cufts" \
    --form pkg="$cufts_file" \
    --form platformUrl="http://lib-code.lib.sfu.ca/projects/CUFTS/" \
    --form format="JSON" \
    http://localhost:8080/gokb/packages/deposit

Which runs in the background -- pkg==the name of the package to ingest. platformUrl is only used when we can't figure out a platform from the titleUrl, less confident about creating a mapping for thats case. Is this method usable? Obviously, ingesting CUFTS is going to require some level of manual work anyway - Download and Unzip - this approach sits nicely with automating the month-on-month processing, with the added benefit that the eBooks style "activity" tab will show what titles are being added/removed on a month by month basis.
