### ISSUE TITLE
Make Macro Refine Transformations field more readable

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#456]
When the Refine Transformations field on a macro is saved, it displays the code nicely formatted. However, when you switch to the edit view of a field, you just see a block of text with no formatting. Would it be possible to display an easier-to-read view of the text while you're editing it?

**Comment by sosguthorpe** [comment]
I'm afraid this is not possible. The textarea in HTML removes formatting when displaying the text. In actual fact the text is formatted as it is when saved under the hood and it is the browser element removing it.

**Comment by sosguthorpe** [comment]
Scratch what I just said. We can do this.

**Comment by kristenwilson** [comment]
Confirmed testing complete.
