### ISSUE TITLE
OAI: concatenated publisher names in titleInstance

### ISSUE THREAD

**Issue by julianladisch** [k-int/gokb-phase1#459]
If a title has two publisher names (because the publisher has changed at some time) the two publisher names get concatenated in the OAI export.

Example titleInstance (Applied Petrochemical Research):
https://test-gokb.kuali.org/gokb/resource/show/org.gokb.cred.TitleInstance%3A10953#publishers

The two publisher names are
- 101 Communications
- 2Cs Communications

The OAI export
https://test-gokb.kuali.org/gokb/oai/titles?verb=ListRecords&resumptionToken=||30275|gokb
has this publisher data:
`<publisher id="14"><name>101 Communications2Cs Communications</name></publisher>`

There should be separate `<publisher>` entries for the two publishers in the OAI export.

**Comment by ianibo** [comment]
Fixed on dev
