### ISSUE TITLE
Problem with Package updates

### ISSUE THREAD

**Issue by ostephens** [k-int/gokb-phase1#46]
Tried to update a package using a file that updates a TIPP Status, and omits a row that is in the current package on GOKb.

The test project is "GOKb:Test:TI Test Set Update". On attempt to ingest as 'update' get error "Ingest attempted by ostephens has failed"

**Comment by sosguthorpe** [comment]
No longer failing to ingest.

**Comment by ostephens** [comment]
Ingest now succeeds
