### ISSUE TITLE
Cannot create new package in GOKb-Test

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#460]
I am not able to successfully create a new package in Refine. I am able to put in the provider name and the title, but I receive an error message: There was an error completing a new Component package.  

http://127.0.0.1:3333/project?project=2003103482358

![image](https://cloud.githubusercontent.com/assets/13369381/11661506/3ade3118-9da0-11e5-9fa2-c0d11c3a6986.png)

**Comment by jhsolomon** [comment]
I am still not able to create a new package name. Has this issue been addressed?

**Comment by kristenwilson** [comment]
Moving this to 5.1 because it needs to be fixed before we can move forward with the release.

**Comment by jhsolomon** [comment]
Confirmed fix
