### ISSUE TITLE
Publisher reconcilation not working on Kuali Test

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#464]
In Kuali Test, if I got to Reconcile>Start Reconciling, I do not see the GOKb option. It seems possible that a few new features have been accidentally removed from the test environment. See also #463.

**Comment by kristenwilson** [comment]
The GOKb reconciliation option is now present. However, the reconciliation is still having some issues. I tried reconciling Imprints in a project, an I got an error message saying that GOKb could not connect to the Kuali Test service (unfortunately I've lost the exact text). However, I could see in the grayed out background (behind the "working" dialogue) that the reconciliation was happening. This error message appeared only after a lengthy wait (~10 minutes). After that, I was not able to return to the project, the "working" dialogue continued to spin indefinitely.

**Comment by sosguthorpe** [comment]
This is actually not the reconciliation that is failing but the validation and is directly related to #472.
Will need retesting after we have released.

**Comment by jhsolomon** [comment]
It took about 4 minutes for the reconciliation to complete on JSTOR: JSTOR Complete: 20160120 (approximately 3300 titles). 

The functionality seems to be working well. I was able to select appropriate orgs, using the suggestions, or create new orgs when needed.

**Comment by jhsolomon** [comment]
In Project Euclid: Project Euclid Free: 20160120 it only took about 10 seconds for the reconciliation process to complete on 85 rows. However, when I select "choose new match" nothing is happening. And after selecting this option for 10 or so titles, I received an error message.

![image](https://cloud.githubusercontent.com/assets/13369381/12457359/0c984278-bf72-11e5-80db-2e30ce24c7fc.png)

**Comment by sosguthorpe** [comment]
I'm not able to recreate the issue here with that project. All seems to be working fine for me. Is there a specific row that is causing the issue?

**Comment by jhsolomon** [comment]
I think row 83 (Mathematical Society of Japan) is an example, but I am not sure I am going through all of the steps correctly. 
What does it mean when it says "new" after the publisher name? Does that mean I have properly created a new org? And if so, when I facet the orgs, why is it still included in the list of orgs that need to be looked up in GOKb before they are considered valid?

![image](https://cloud.githubusercontent.com/assets/13369381/12483694/76fd231a-c024-11e5-8b81-bc366be55c3d.png)

**Comment by sosguthorpe** [comment]
No New is a place holder in refine that means it hasn't matched. It 
doesn't actually do anything except allow you to facet on "new" after 
you are finished so that you can create the ones you need manually. I'm 
afraid this is something that open-refine does for all reconciliation.

**Comment by jhsolomon** [comment]
Ok, thanks! Just so that I'm clear, there is no way to change the "new" to
another word.

On Thu, Jan 21, 2016 at 10:07 AM, sosguthorpe notifications@github.com
wrote:

> No New is a place holder in refine that means it hasn't matched. It
> doesn't actually do anything except allow you to facet on "new" after
> you are finished so that you can create the ones you need manually. I'm
> afraid this is something that open-refine does for all reconciliation.
> 
> On 21/01/16 14:51, jhsolomon wrote:
> 
> > I think row 83 (Mathematical Society of Japan) is an example, but I am
> > not sure I am going through all of the steps correctly.
> > What does it mean when it says "new" after the publisher name? Does
> > that mean I have properly created a new org? And if so, when I facet
> > the orgs, why is it still included in the list of orgs that need to be
> > looked up in GOKb before they are considered valid?
> > 
> > image
> > <
> > https://cloud.githubusercontent.com/assets/13369381/12483694/76fd231a-c024-11e5-8b81-bc366be55c3d.png
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/k-int/gokb-phase1/issues/464#issuecomment-173594030
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/k-int/gokb-phase1/issues/464#issuecomment-173599286.

## 

Jennifer Solomon
GOKb Editor, Acquisitions and Discovery
North Carolina State University Libraries
919-515-2743
j kristen_wilson@ncsu.eduhsolomo@ncsu.edu

**Comment by sosguthorpe** [comment]
Not without extensive work as the value is also used in faceting.

**Comment by jhsolomon** [comment]
OK, I understand!

Confirmed fix
