### ISSUE TITLE
Create flag that allows fields to be updated with null values

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#469]
We identified a need to update fields with null values in certain contexts, primarily coverage dates. 

The main use case is a title with an end coverage date, which then changes to open-ended coverage. Under the current conditions, the new blank end date will never overwrite the old date. 

Owen and Ian suggested a flag for certain fields that indicate that blank values should be coded as null and be allowed to overwrite existing values.

**Comment by jhsolomon** [comment]
Completed, but not switched on. May need configuration for specific fields.
