### ISSUE TITLE
Create widget to delete incorrect orgs

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#470]
Currently, we have several Providers listed incorrectly as the Latest Publisher in GOKb Live. What we need is:
1. A widget (Ian thinks this will be just 2 minutes work to create)
2. Remove the name of the Provider where it is listed as the Publisher
3. Leave the Publisher name field blank

List of Providers to remove from Latest Publisher field:
JSTOR
Directory of Open Access Journals
Highwire
Project Muse
Project Euclid

**Comment by ianibo** [comment]
Any chance you list a couple of problem titles as test cases (URLs would be ace) - just so we have something to test against? Cheers.

**Comment by jhsolomon** [comment]
Of course! Plenty of examples to go around.

http://gokb.kuali.org/gokb/resource/show/org.gokb.cred.TitleInstance%3A54806#publishers

http://gokb.kuali.org/gokb/resource/show/org.gokb.cred.TitleInstance%3A27538#publishers

http://gokb.kuali.org/gokb/resource/show/org.gokb.cred.TitleInstance%3A54622#publishers

**Comment by ianibo** [comment]
New action added for orgs to deprecate unwanted listings and replace them with a preferred one.

**Comment by jhsolomon** [comment]
@ianibo Is it possible to deprecate the unwanted org and leave it blank?

**Comment by ianibbo** [comment]
Anything specific about why this isn't working? Search for org then select
actions -> deprecate?

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ianibo** [comment]
Have added additional delete link inline in title publishers table. Will
deploy this evening.

On 8 March 2016 at 18:39, ianibbo notifications@github.com wrote:

> Anything specific about why this isn't working? Search for org then select
> actions -> deprecate?
> 
> Ian Ibbotson
> Director
> Knowledge Integration Ltd
> 35 Paradise Street, Sheffield. S3 8PZ
> T: 0114 273 8271
> M: 07968 794 630
> W: http://www.k-int.com
> 
> On 8 March 2016 at 18:08, jhsolomon notifications@github.com wrote:
> 
> > Reopened #470 https://github.com/k-int/gokb-phase1/issues/470.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/k-int/gokb-phase1/issues/470#event-582112986.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/k-int/gokb-phase1/issues/470#issuecomment-193907782.

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo
GoodReads: https://www.goodreads.com/user/show/3106516-ian-ibbotson

**Comment by jhsolomon** [comment]
I think we are on the same page, but just to clarify, the functionality is
working when I select a new "Org to Use." What was missing was the ability
to remove the org name and replace it with a blank.

On Tue, Mar 8, 2016 at 2:45 PM, Ian Ibbotson notifications@github.com
wrote:

> Have added additional delete link inline in title publishers table. Will
> deploy this evening.
> 
> On 8 March 2016 at 18:39, ianibbo notifications@github.com wrote:
> 
> > Anything specific about why this isn't working? Search for org then
> > select
> > actions -> deprecate?
> > 
> > Ian Ibbotson
> > Director
> > Knowledge Integration Ltd
> > 35 Paradise Street, Sheffield. S3 8PZ
> > T: 0114 273 8271
> > M: 07968 794 630
> > W: http://www.k-int.com
> > 
> > On 8 March 2016 at 18:08, jhsolomon notifications@github.com wrote:
> > 
> > > Reopened #470 https://github.com/k-int/gokb-phase1/issues/470.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/k-int/gokb-phase1/issues/470#event-582112986.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/k-int/gokb-phase1/issues/470#issuecomment-193907782
> > .
> 
> ## 
> 
> Ian Ibbotson
> W: http://ianibbo.me
> E: ianibbo@gmail.com
> skype: ianibbo
> twitter: ianibbo
> GoodReads: https://www.goodreads.com/user/show/3106516-ian-ibbotson
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/k-int/gokb-phase1/issues/470#issuecomment-193938737.

## 

Jennifer Solomon
GOKb Editor, Acquisitions and Discovery
North Carolina State University Libraries
919-515-2743
j kristen_wilson@ncsu.eduhsolomo@ncsu.edu

**Comment by ianibbo** [comment]
Yep, gotcha - have added an extra option inline on the title - will deploy
this eve

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by jhsolomon** [comment]
Fantastic!
fix confirmed.

On Tue, Mar 8, 2016 at 3:00 PM, ianibbo <notifications@github.com> wrote:

> Yep, gotcha - have added an extra option inline on the title - will deploy
> this eve
>
> Ian Ibbotson
> Director
> Knowledge Integration Ltd
> 35 Paradise Street, Sheffield. S3 8PZ
> T: 0114 273 8271
> M: 07968 794 630
> W: http://www.k-int.com
>
> On 8 March 2016 at 19:58, jhsolomon <notifications@github.com> wrote:
>
> > I think we are on the same page, but just to clarify, the functionality
> is
> > working when I select a new "Org to Use." What was missing was the
> ability
> > to remove the org name and replace it with a blank.
> >
> > On Tue, Mar 8, 2016 at 2:45 PM, Ian Ibbotson <notifications@github.com>
> > wrote:
> >
> > > Have added additional delete link inline in title publishers table.
> Will
> > > deploy this evening.
> > >
> > > On 8 March 2016 at 18:39, ianibbo <notifications@github.com> wrote:
> > >
> > > > Anything specific about why this isn't working? Search for org then
> > > select
> > > > actions -> deprecate?
> > > >
> > > >
> > > > Ian Ibbotson
> > > > Director
> > > > Knowledge Integration Ltd
> > > > 35 Paradise Street, Sheffield. S3 8PZ
> > > > T: 0114 273 8271
> > > > M: 07968 794 630
> > > > W: http://www.k-int.com
> > > >
> > > > On 8 March 2016 at 18:08, jhsolomon <notifications@github.com>
> wrote:
> > > >
> > > > > Reopened #470 <https://github.com/k-int/gokb-phase1/issues/470>.
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <https://github.com/k-int/gokb-phase1/issues/470#event-582112986>.
> > > >
> > > > >
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > https://github.com/k-int/gokb-phase1/issues/470#issuecomment-193907782
> > > >.
> > > >
> > >
> > >
> > >
> > > --
> > > Ian Ibbotson
> > > W: http://ianibbo.me
> > > E: ianibbo@gmail.com
> > > skype: ianibbo
> > > twitter: ianibbo
> > > GoodReads: https://www.goodreads.com/user/show/3106516-ian-ibbotson
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/k-int/gokb-phase1/issues/470#issuecomment-193938737
> > >.
> > >
> >
> >
> >
> > --
> > Jennifer Solomon
> > GOKb Editor, Acquisitions and Discovery
> > North Carolina State University Libraries
> > 919-515-2743
> > j <kristen_wilson@ncsu.edu>hsolomo@ncsu.edu
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/k-int/gokb-phase1/issues/470#issuecomment-193942909
> >.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/k-int/gokb-phase1/issues/470#issuecomment-193943660>.
>



-- 
Jennifer Solomon
GOKb Editor, Acquisitions and Discovery
North Carolina State University Libraries
919-515-2743
j <kristen_wilson@ncsu.edu>hsolomo@ncsu.edu

**Comment by jhsolomon** [comment]
oy, sorry, I found a few titles that were problematic. The ability to deprecate the org with the blank option is working, but it does not seem to be updating all titles. below are a few examples.

http://test-gokb.kuali.org/gokb/resource/show/org.gokb.cred.TitleInstance%3A27178#publishers

http://test-gokb.kuali.org/gokb/resource/show/org.gokb.cred.TitleInstance%3A14335#publishers

http://test-gokb.kuali.org/gokb/resource/show/org.gokb.cred.TitleInstance%3A33796#publishers

**Comment by ianibo** [comment]
Just want to be sure on this -- the delete option will only clear out the publisher in the current title -- are you wanting to nuke all the links to that publisher in all titles? My worry is that someone might hit the delete button wanting to only remove the current. Is a better workflow to add a "Delete all" method to the org actions? The workflow then would be -- click on org in titles page to go to org page, then select "Delete all" in org actions. Or have I misunderstood again? ta

**Comment by jhsolomon** [comment]
Maybe this is two separate actions? 

The original need was to remove incorrect publishers listed as the "Latest Publisher". E.g., Project Muse or JSTOR should never be publishers. My understanding was that the deprecate org function would take the current publisher and replace it with a different publisher OR the blank. Then the Latest Publisher would be empty, which is better than an incorrect publisher.

The reason to do this is that with JSTOR and other large packages, this means there are several thousand titles with incorrect publishers and it would take quite a long time to go into each title page and remove these individually.

Does that help, or did I make us all more confused?

**Comment by jhsolomon** [comment]
I think this workflow is much better! 

fix confirmed. @kristenwilson please test.

**Comment by ianibo** [comment]
Add intermediate page with more explanation, rename action to deprecate pub from titles etc.

**Comment by jhsolomon** [comment]
Under Available Actions tab, change text to:
"Replace Publisher with..."
"Remove Publisher name from title records..."

On the intermediate page, add text similar to Replace Platform page:
"This action will replace the existing Publisher in all associated titles with the new Publisher selection."

"This action will remove the Publisher name from all associated titles and leave the publisher name field empty."

**Comment by jhsolomon** [comment]
Confirmed fix. @kristenwilson Do these two workflows make sense to you?

**Comment by kristenwilson** [comment]
The workflows make sense, but some of the text Jennifer supplied in a
previous comment has not be added. I think the additional explanation is
necessary to make sure it's clear what this function does.

The intermediate page for "Replace publisher with..." is supposed to say ""This
action will replace the existing Publisher in all associated titles with
the new Publisher selection." I don't see that on the intermediate page.

For "Remove publisher name from title records," I don't see any
intermediate page at all -- the action just takes effect. I would like to
see an intermediate page here with an option to cancel. This page should
say, "This action will remove the Publisher name from all associated titles
and leave the publisher name field empty."

On Mon, Apr 4, 2016 at 11:15 AM, jhsolomon notifications@github.com wrote:

> Confirmed fix. @kristenwilson https://github.com/kristenwilson Do these
> two workflows make sense to you?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/k-int/gokb-phase1/issues/470#issuecomment-205343700

## 

Kristen Wilson
Associate Head, Acquisitions and Discovery
North Carolina State University Libraries
919-513-3354
kristen_wilson@ncsu.edu
ORCID: http://orcid.org/0000-0002-3509-3417

**Comment by ianibo** [comment]
Intermediate screen added 
![image](https://cloud.githubusercontent.com/assets/53283/14312009/34ae9a94-fbe2-11e5-847e-be5446a24659.png)

**Comment by ianibo** [comment]
Deployed fix - updated testme label. Not tested as I wasn't sure which orgs to nuke :)

**Comment by jhsolomon** [comment]
Orgs are nuking properly. Fix confirmed and retested.

**Comment by kristenwilson** [comment]
Confirmed
