### ISSUE TITLE
Error messages are displaying when there is no error

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#471]
In GOKb Test, I looked up the platform name using the Refine look-up function and the cells populated correctly, but I am still seeing the error messages.

http://127.0.0.1:3333/project?project=2411893028430

![image](https://cloud.githubusercontent.com/assets/13369381/12245690/227725c4-b878-11e5-9e1a-fde50656708c.png)

**Comment by kristenwilson** [comment]
Moving this to 5.1 because it needs to be fixed before we can move forward with the next release.

**Comment by sosguthorpe** [comment]
I haven't been able to replicate this. This will need reconfirming once I have built the release on test and if it is still a problem I'll need some exact replication steps to follow.

**Comment by jhsolomon** [comment]
I was not able to replicate this problem. It may have been due to the slow performance or an issue on my end. 

Fix confirmed.
