### ISSUE TITLE
Performance issues on Kuali Test

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#472]
On the Kuali Test platform, I'm experiencing significant slowness. Some functions are fast, like faceting or using quick resolutions. But anything that involves connecting to GOKb (checking in, applying macros, reconiliation) is extremely slow. 

I've also begun to see error messages saying "Cannot retrieve content from https://test-gokb.kuali.org/api/projectDataValid" during multiple functions. Most recently I received this message while simply creating a new project that has not even been checked in to GOKb yet. This has made it impossible to begin a new project and proceed with testing.

**Comment by ianibbo** [comment]
Hey Kristen,

not sure what is going on here -- the server seems to be fine on a first
inspection. I know it's a bit of a long shot - are you sure the connection
is OK? I think we need to do a better job of trapping and reporting issues
with the underlying connection. I've upped the server logging and optimised
all the tables, but to do more analysis I need to generate more traffic and
try to watch the server whilst it's failing. If you could let me know when
you are about to start working I'll try and watch the logs in real time to
see if I can see whats going on.

ian

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ianibbo** [comment]
Seeing some odd lines in the apache log file::

[Mon Jan 11 20:43:19.100162 2016] [proxy_ajp:error] [pid 15254:tid
140429257275136](70007)The timeout specified has expired: [client
152.14.139.5:61000] AH00893: dialog to 127.0.0.1:8009 (localhost) failed
[Mon Jan 11 20:44:46.724376 2016] [proxy_ajp:error] [pid 15253:tid
140429391558400](70007)The timeout specified has expired: AH01030:
ajp_ilink_receive() can't receive header
[Mon Jan 11 20:44:46.724415 2016] [proxy_ajp:error] [pid 15253:tid
140429391558400] [client 152.14.139.5:63884] AH00992: ajp_read_header:
ajp_ilink_receive failed
[Mon Jan 11 20:44:46.724425 2016] [proxy_ajp:error] [pid 15253:tid
140429391558400](70007)The timeout specified has expired: [client
152.14.139.5:63884] AH00893: dialog to 127.0.0.1:8009 (localhost) failed

Might need to tune up the ajp connector, will discuss with steve.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by sosguthorpe** [comment]
Managed to get the validation step for ~3100 record project down to 17 seconds. The problem is that each row has to be matched to a title pre ingest and then the dates can be compared. Because of this 17 seconds is reasonable. If this is unacceptable then we can make improvements to this, but they would have to be delivered in a future release.

**Comment by kristenwilson** [comment]
@sosguthorpe I think 17 seconds is reasonable for this step. The performance problems prompting this issue were in the neighborhood of several minutes up to 10+ minutes. This will be a big improvement.

**Comment by jhsolomon** [comment]
It took about 4 minutes for the reconciliation to complete on the JSTOR: JSTOR Complete: 20160120 (approximately 3300 titles).

**Comment by jhsolomon** [comment]
Overall, the performance on Test was very good today! I experienced slowness when I tried to reconcile the JSTOR packages (3300 titles) and on a few other occasions, but I think that was due to my connection at home.

**Comment by kristenwilson** [comment]
Performance was much improved for me also. Calling this fixed.
