### ISSUE TITLE
Platform look up is not working in Live

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#473]
@sosguthorpe Can you take a look at this? I am not able to look up any platforms in GOKb live.

http://127.0.0.1:3333/project?project=1693475205792

**Comment by sosguthorpe** [comment]
Sure. Can you please check in the project and just tell me the name of the project in the issue. Pasting your refine link here will not work, as the local ID isn't the same from user to user.

**Comment by jhsolomon** [comment]
Here you go!

American Institute of Physics: Scitation Titles: 20160114

On Thu, Jan 14, 2016 at 11:55 AM, sosguthorpe notifications@github.com
wrote:

> Sure. Can you please check in the project and just tell me the name of the
> project in the issue. Pasting your refine link here will not work, as the
> local ID isn't the same from user to user.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/k-int/gokb-phase1/issues/473#issuecomment-171701283.

## 

Jennifer Solomon
GOKb Editor, Acquisitions and Discovery
North Carolina State University Libraries
919-515-2743
j kristen_wilson@ncsu.eduhsolomo@ncsu.edu

**Comment by sosguthorpe** [comment]
I just used the platform lookup without issue here. You are referring to the functionality from the right-click menu right? And the project seems to have looked up values in there. Can you be more specific about the exact problem your having and also maybe a screenshot?

If you are referring to the Reconciliation stuff then this isn't on live yet and so wouldn't be usable.

**Comment by jhsolomon** [comment]
Thanks!

I was having some problems with my VM yesterday, so after that was
refreshed, I deleted and reinstalled Refine with the current GOKb
extension. The look up function seems to be working fine for me now.

On a side note, Refine was very slow yesterday, but this morning seems the
performance seems to be much better.

On Fri, Jan 15, 2016 at 8:19 AM, sosguthorpe notifications@github.com
wrote:

> I just used the platform lookup without issue here. You are referring to
> the functionality from the right-click menu right? And the project seems to
> have looked up values in there. Can you be more specific about the exact
> problem your having and also maybe a screenshot?
> 
> If you are referring to the Reconciliation stuff then this isn't on live
> yet and so wouldn't be usable.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/k-int/gokb-phase1/issues/473#issuecomment-171958222.

## 

Jennifer Solomon
GOKb Editor, Acquisitions and Discovery
North Carolina State University Libraries
919-515-2743
j kristen_wilson@ncsu.eduhsolomo@ncsu.edu

**Comment by sosguthorpe** [comment]
Glad to hear it is working well for you now.
