### ISSUE TITLE
Unable to update GOKb Test

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#475]
Could you check on what might be going on with the FreelyAccessibleJapaneseTitles: AllTitles: 20160209 package in GOKb Test? 

I have tried several times, but continue to get the same error.

![image](https://cloud.githubusercontent.com/assets/13369381/12929067/de3d5fb2-cf3e-11e5-9092-20bc1007f2f2.png)

**Comment by sosguthorpe** [comment]
Ian,

Looks like the elastic load balancer is cutting the connection before tomcat does. There are no errors appearing in the logs at the server end, and the project has 9000+ rows which explains the time. I am forwarding to @ianibbo as I can't change these settings.

**Comment by ianibbo** [comment]
Alas I'm not authorized to change the LB timeout, we can ask the kuali guys
to do this -- the obvious question tho is -- is raising the timeout the
right thing to do? It's making it a really long running transaction :(

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by jhsolomon** [comment]
If we did not change the timeout, what other options do we have for
ingesting a file this size? Is this something we could do via the TSV
importer?

On Wed, Feb 10, 2016 at 6:22 AM, ianibbo notifications@github.com wrote:

> Alas I'm not authorized to change the LB timeout, we can ask the kuali guys
> to do this -- the obvious question tho is -- is raising the timeout the
> right thing to do? It's making it a really long running transaction :(
> 
> Ian Ibbotson
> Director
> Knowledge Integration Ltd
> 35 Paradise Street, Sheffield. S3 8PZ
> T: 0114 273 8271
> M: 07968 794 630
> W: http://www.k-int.com
> 
> On 10 February 2016 at 10:29, sosguthorpe notifications@github.com
> wrote:
> 
> > Ian,
> > 
> > Looks like the elastic load balancer is cutting the connection before
> > tomcat does. There are no errors appearing in the logs at the server end,
> > and the project has 9000+ rows which explains the time. I am forwarding
> > to
> > @ianibbo https://github.com/ianibbo as I can't change these settings.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/k-int/gokb-phase1/issues/475#issuecomment-182300373
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/k-int/gokb-phase1/issues/475#issuecomment-182322985.

## 

Jennifer Solomon
GOKb Editor, Acquisitions and Discovery
North Carolina State University Libraries
919-515-2743
j kristen_wilson@ncsu.eduhsolomo@ncsu.edu

**Comment by ianibbo** [comment]
Yeah.. I'd really try via the tsv upload.  Can I pick up the file
somewhere?

Ta,
E

**Comment by jhsolomon** [comment]
Ian, I just shared the link with you to my google drive. It's a zipped
file, but the document you need is: JapaneseSingleTitles_AllTitles_20160208

https://drive.google.com/open?id=0B9YT8kJnUu_tWjJlS0VWWklvUzg

thanks!

On Thu, Feb 11, 2016 at 4:19 PM, ianibbo notifications@github.com wrote:

> Yeah.. I'd really try via the tsv upload. Can I pick up the file
> somewhere?
> 
> Ta,
> E
> 
> On 11 Feb 2016 8:39 pm, "jhsolomon" notifications@github.com wrote:
> 
> > If we did not change the timeout, what other options do we have for
> > ingesting a file this size? Is this something we could do via the TSV
> > importer?
> > 
> > On Wed, Feb 10, 2016 at 6:22 AM, ianibbo notifications@github.com
> > wrote:
> > 
> > > Alas I'm not authorized to change the LB timeout, we can ask the kuali
> > > guys
> > > to do this -- the obvious question tho is -- is raising the timeout the
> > > right thing to do? It's making it a really long running transaction :(
> > > 
> > > Ian Ibbotson
> > > Director
> > > Knowledge Integration Ltd
> > > 35 Paradise Street, Sheffield. S3 8PZ
> > > T: 0114 273 8271
> > > M: 07968 794 630
> > > W: http://www.k-int.com
> > > 
> > > On 10 February 2016 at 10:29, sosguthorpe notifications@github.com
> > > wrote:
> > > 
> > > > Ian,
> > > > 
> > > > Looks like the elastic load balancer is cutting the connection before
> > > > tomcat does. There are no errors appearing in the logs at the server
> > > > end,
> > > > and the project has 9000+ rows which explains the time. I am
> > > > forwarding
> > > > to
> > > > @ianibbo https://github.com/ianibbo as I can't change these
> > > > settings.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > > > https://github.com/k-int/gokb-phase1/issues/475#issuecomment-182300373
> > > > .
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/k-int/gokb-phase1/issues/475#issuecomment-182322985
> > > .
> > 
> > ## 
> > 
> > Jennifer Solomon
> > GOKb Editor, Acquisitions and Discovery
> > North Carolina State University Libraries
> > 919-515-2743
> > j kristen_wilson@ncsu.eduhsolomo@ncsu.edu
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/k-int/gokb-phase1/issues/475#issuecomment-183052323
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/k-int/gokb-phase1/issues/475#issuecomment-183063479.

## 

Jennifer Solomon
GOKb Editor, Acquisitions and Discovery
North Carolina State University Libraries
919-515-2743
j kristen_wilson@ncsu.eduhsolomo@ncsu.edu

**Comment by jhsolomon** [comment]
We are having the same problem with a Springer package of  approx. 3000 titles: Springer: Springer Complete Test: 20160212

In Test, the performance is very slow and then it times out when I try to update GOKb.
