### ISSUE TITLE
Review tasks related to coverage ranges that pre- or post-date the published date ranges are not being generated on GOKb Test

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#476]
Review tasks related to coverage ranges that pre- or post-date the published date ranges are not being generated at all when I ingest a package on GOKb Test. Warning messages related to these are showing up in OpenRefine, but the review tasks just seem to be missing.

For an example, see the project Cambridge University Press: All Titles: 20160209 Test

**Comment by jhsolomon** [comment]
fix confirmed
