### ISSUE TITLE
OA status menu broken

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#478]
There are many "null" options in the OA status menu. Can these be deleted? This seems to be in all titles, but this is one example:
http://gokb.kuali.org/gokb/resource/show/org.gokb.cred.TitleInstance%3A337505

![image](https://cloud.githubusercontent.com/assets/13369381/13359542/da02244a-dc82-11e5-9fc6-2fb8c3c7542a.png)

**Comment by ianibo** [comment]
Yeah..
http://gokb.kuali.org/gokb/resource/show/org.gokb.cred.RefdataCategory%3A48
seems to report a number of blanks.. Will investigate removing them.

Ian.

On 26 February 2016 at 17:18, jhsolomon notifications@github.com wrote:

> There are many "null" options in the OA status menu. Can these be deleted?
> This seems to be in all titles, but this is one example:
> 
> http://gokb.kuali.org/gokb/resource/show/org.gokb.cred.TitleInstance%3A337505
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/13369381/13359542/da02244a-dc82-11e5-9fc6-2fb8c3c7542a.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/k-int/gokb-phase1/issues/478.

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo
GoodReads: https://www.goodreads.com/user/show/3106516-ian-ibbotson

**Comment by jhsolomon** [comment]
Thanks, sounds good.

On Tue, Mar 8, 2016 at 2:52 PM, Ian Ibbotson notifications@github.com
wrote:

> Yeah..
> http://gokb.kuali.org/gokb/resource/show/org.gokb.cred.RefdataCategory%3A48
> seems to report a number of blanks.. Will investigate removing them.
> 
> Ian.
> 
> On 26 February 2016 at 17:18, jhsolomon notifications@github.com wrote:
> 
> > There are many "null" options in the OA status menu. Can these be
> > deleted?
> > This seems to be in all titles, but this is one example:
> > 
> > http://gokb.kuali.org/gokb/resource/show/org.gokb.cred.TitleInstance%3A337505
> > 
> > [image: image]
> > <
> > https://cloud.githubusercontent.com/assets/13369381/13359542/da02244a-dc82-11e5-9fc6-2fb8c3c7542a.png
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/k-int/gokb-phase1/issues/478.
> 
> ## 
> 
> Ian Ibbotson
> W: http://ianibbo.me
> E: ianibbo@gmail.com
> skype: ianibbo
> twitter: ianibbo
> GoodReads: https://www.goodreads.com/user/show/3106516-ian-ibbotson
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/k-int/gokb-phase1/issues/478#issuecomment-193940690.

## 

Jennifer Solomon
GOKb Editor, Acquisitions and Discovery
North Carolina State University Libraries
919-515-2743
j kristen_wilson@ncsu.eduhsolomo@ncsu.edu

**Comment by jhsolomon** [comment]
fix confirmed
