### ISSUE TITLE
Add search field to Request for Review page

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#481]
Could we add a search field for "Cause" to the Review page: http://gokb.kuali.org/gokb/resource/show/org.gokb.cred.ReviewRequest%3A76313

This would make sorting types of issues much more convenient.

**Comment by ianibbo** [comment]
Hehe - one step ahead of you for once::
http://test-gokb.kuali.org/gokb/search/index?qbe=g%3AreviewRequests

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by jhsolomon** [comment]
Fantastic!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

On Thu, Mar 10, 2016 at 11:06 AM, ianibbo notifications@github.com wrote:

> Hehe - one step ahead of you for once::
> http://test-gokb.kuali.org/gokb/search/index?qbe=g%3AreviewRequests
> 
> Ian Ibbotson
> Director
> Knowledge Integration Ltd
> 35 Paradise Street, Sheffield. S3 8PZ
> T: 0114 273 8271
> M: 07968 794 630
> W: http://www.k-int.com
> 
> On 10 March 2016 at 15:49, jhsolomon notifications@github.com wrote:
> 
> > Could we add a search field for "Cause" to the Review page:
> > 
> > http://gokb.kuali.org/gokb/resource/show/org.gokb.cred.ReviewRequest%3A76313
> > 
> > This would make sorting types of issues much more convenient.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/k-int/gokb-phase1/issues/481.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/k-int/gokb-phase1/issues/481#issuecomment-194926959.

## 

Jennifer Solomon
GOKb Editor, Acquisitions and Discovery
North Carolina State University Libraries
919-515-2743
j kristen_wilson@ncsu.eduhsolomo@ncsu.edu

**Comment by jhsolomon** [comment]
Also, Could the Cause search bar include the drop-down menu like the other categories?

**Comment by ianibo** [comment]
Looks like this will be too difficult in the short term - the major problem is populating the list of values. However, I wonder if we can do a workaround? If you enter criteria like %Preflight% into the cause box you can then save the search as "Failing Ingests" and execute that search from the saved items screen (Left menu). You could also bookmark the search and execute it later on? Would that do as a workaround?

**Comment by jhsolomon** [comment]
I think a better workaround (for me) is just to copy and paste the text of the Review Task into the search field. I tested this and it works just fine.

**Comment by kristenwilson** [comment]
Confirmed.
