### ISSUE TITLE
Package will not ingest in Live

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#483]
One of our data loaders at NCSU has tried several times to ingest this package: Brill: Brill Journal Collection: 20160314

She continues to get a Null message. I tried this as well and received the same message. Can you see what might be wrong?

**Comment by ianibo** [comment]
Can you attach the file here please? ty

**Comment by jhsolomon** [comment]
here you go!

[brill_online_journals.txt](https://github.com/k-int/gokb-phase1/files/182057/brill_online_journals.txt)
