### ISSUE TITLE
Imprint look up is not working in Refine

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#487]
@sosguthorpe In Live, when I try to use the GOKb Lookup function for an imprint, the search box does not open. I am not having this problem with the other look up categories.

Also, the Imprint reconcile function is working correctly, so I have been using that for the time being.

**Comment by sosguthorpe** [comment]
@jhsolomon Released client 5.1.1 as a bugfix release for this issue. Your client should update automatically.

**Comment by jhsolomon** [comment]
After the restart, the GOKb extension is no longer part of my Refine installation. Should I reinstall Refine and the GOKb extension?

![image](https://cloud.githubusercontent.com/assets/13369381/14184321/9d1a2002-f742-11e5-8149-f7efa36a9da3.png)

**Comment by jhsolomon** [comment]
fix confirmed
