### ISSUE TITLE
GOKb extension disappearing from Refine

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#488]
I reinstalled both Refine and the GOKb extension and was able to see the GOKb login menu. I also got the notification that Refine had been updated and would need to restart. 

![image](https://cloud.githubusercontent.com/assets/13369381/14185265/249bdf12-f747-11e5-8b13-39c5f4fa57f5.png)

But upon restarting it, the GOKb extension was missing again.

**Comment by sosguthorpe** [comment]
@jhsolomon It appears there is a bug in the update code for the current version of the extension that prevents the new extension being installed properly. I can only apologise for this. Please download version 5.1.1 directly https://gokb.k-int.com/gokb/api/downloadUpdate

This should fix the update issue and the issue it was released to fix. Apologies again for the inconvenience.

**Comment by jhsolomon** [comment]
Thank you! Fix confirmed.
