### ISSUE TITLE
Review Tasks are identifying missing TIPPs that are not missing from the package file

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#489]
Review Tasks identify missing TIPPs that are included in the current package.

**Comment by ianibo** [comment]
We suspect this is caused by a change to the way normalised identifiers are stored. Retest please, and post links to package, review requests and name of refine project here if it happens again.

**Comment by jhsolomon** [comment]
confirmed fix. tested with Brill: Online Journals: test 2
