### ISSUE TITLE
Validation on org.publisher.name in Refine

### ISSUE THREAD

**Issue by ostephens** [k-int/gokb-phase1#49]
Following feedback from SMEs, now request following validation on this col in Refine:

If org.publisher.name column ommitted, raise an error to prompt addition of column (quick resolution could be to rename existing column, or add an additional col)
Blank values should be allowed in the column but should raise a warning indicating there are missing values
Apart from blank values, values in this col need to have been looked up from GOKb Orgs (this is as currently)

**Comment by ianibo** [comment]
Changed as specified. Needs retest - May have unexpected side effects.
