### ISSUE TITLE
Packages endpoint is not updating 

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#493]
I tried to search for and download a Karger package file from: http://test-gokb.kuali.org/gokb/packages

While the download option is working for, the search was unable to find the two packages I ingested earlier today.

**Comment by ianibbo** [comment]
Ah yeah - that screen is run by elasticsearch and we need to increase the
frequency it updates.

you can manually trigger from Admin -> Update Full text Indexes.

I've run that now - can you see if the packages are available now?

Thanks,
Ian.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com
Doodle: http://doodle.com/ianibbo

**Comment by jhsolomon** [comment]
No, not yet.

On Wed, Apr 20, 2016 at 12:16 PM, ianibbo notifications@github.com wrote:

> Ah yeah - that screen is run by elasticsearch and we need to increase the
> frequency it updates.
> 
> you can manually trigger from Admin -> Update Full text Indexes.
> 
> I've run that now - can you see if the packages are available now?
> 
> Thanks,
> Ian.
> 
> Ian Ibbotson
> Director
> Knowledge Integration Ltd
> 35 Paradise Street, Sheffield. S3 8PZ
> T: 0114 273 8271
> M: 07968 794 630
> W: http://www.k-int.com
> Doodle: http://doodle.com/ianibbo
> 
> On 20 April 2016 at 17:13, jhsolomon notifications@github.com wrote:
> 
> > I tried to search for and download a Karger package file from:
> > http://test-gokb.kuali.org/gokb/packages
> > 
> > While the download option is working for, the search was unable to find
> > the two packages I ingested earlier today.
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > https://github.com/k-int/gokb-phase1/issues/493
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/k-int/gokb-phase1/issues/493#issuecomment-212496602

## 

Jennifer Solomon
GOKb Editor, Acquisitions and Discovery
North Carolina State University Libraries
919-515-2743
j kristen_wilson@ncsu.eduhsolomo@ncsu.edu

**Comment by jhsolomon** [comment]
Ok now they are there :)

On Wed, Apr 20, 2016 at 12:17 PM, Jennifer Solomon jhsolomo@ncsu.edu
wrote:

> No, not yet.
> 
> On Wed, Apr 20, 2016 at 12:16 PM, ianibbo notifications@github.com
> wrote:
> 
> > Ah yeah - that screen is run by elasticsearch and we need to increase the
> > frequency it updates.
> > 
> > you can manually trigger from Admin -> Update Full text Indexes.
> > 
> > I've run that now - can you see if the packages are available now?
> > 
> > Thanks,
> > Ian.
> > 
> > Ian Ibbotson
> > Director
> > Knowledge Integration Ltd
> > 35 Paradise Street, Sheffield. S3 8PZ
> > T: 0114 273 8271
> > M: 07968 794 630
> > W: http://www.k-int.com
> > Doodle: http://doodle.com/ianibbo
> > 
> > On 20 April 2016 at 17:13, jhsolomon notifications@github.com wrote:
> > 
> > > I tried to search for and download a Karger package file from:
> > > http://test-gokb.kuali.org/gokb/packages
> > > 
> > > While the download option is working for, the search was unable to find
> > > the two packages I ingested earlier today.
> > > 
> > > —
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/k-int/gokb-phase1/issues/493
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > https://github.com/k-int/gokb-phase1/issues/493#issuecomment-212496602
> 
> ## 
> 
> Jennifer Solomon
> GOKb Editor, Acquisitions and Discovery
> North Carolina State University Libraries
> 919-515-2743
> j kristen_wilson@ncsu.eduhsolomo@ncsu.edu

## 

Jennifer Solomon
GOKb Editor, Acquisitions and Discovery
North Carolina State University Libraries
919-515-2743
j kristen_wilson@ncsu.eduhsolomo@ncsu.edu

**Comment by ianibo** [comment]
Max interval should be 5 mins.

**Comment by jhsolomon** [comment]
I tried this a few different times over the past hour, but I do not see the
current package: Taylor & Francis: Taylor & Francis Sport, Leisure &
Tourism 2016

On Fri, Apr 22, 2016 at 5:04 AM, Ian Ibbotson notifications@github.com
wrote:

> Max interval should be 5 mins.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/k-int/gokb-phase1/issues/493#issuecomment-213341333

## 

Jennifer Solomon
GOKb Editor, Acquisitions and Discovery
North Carolina State University Libraries
919-515-2743
j kristen_wilson@ncsu.eduhsolomo@ncsu.edu

**Comment by jhsolomon** [comment]
I tried again with Taylor & Francis: Sociology & Related Disciplines 2016, but I still do not see this package. I do see several similarly titled packages, which do not seem like they should all be there.
For example:
Taylor & Francis Sociology & Related Disciplines Collection (Download Kbart File)  
Taylor & Francis:Sociology & Related Disciplines Collection (Download Kbart File)

Maybe it is updating, but it is not updating with the correct package title? Would it be possible to populate Title Count and Last Updated columns?

![image](https://cloud.githubusercontent.com/assets/13369381/14749827/b0ceadf8-088f-11e6-9685-6b85ad40e12b.png)

**Comment by jhsolomon** [comment]
fix confirmed
