### ISSUE TITLE
OpenRefine performance very slow

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#496]
In Live, the performance is very slow on this package:
Elsevier: ScienceDirect Freedom Collection Journals: 20160503

The user reported that she is having a hard time faceting and staring titles because of the speeds.

**Comment by jhsolomon** [comment]
Also, I'm not able to sort the packages in Refine 

![image](https://cloud.githubusercontent.com/assets/13369381/14992218/0104ec64-1133-11e6-8166-d6eda9b850c3.png)

**Comment by jhsolomon** [comment]
Yesterday when I was loading data in Refine, it seemed like the performance was good. But today it is timing out, even on small packages.

Simon Fraser University: Open Journal Systems List: 20160503 

![image](https://cloud.githubusercontent.com/assets/13369381/14992913/67f0a2e4-1136-11e6-81ca-100d3aaf4911.png)

**Comment by ianibo** [comment]
OK thanks Jennifer -- Digging now

On 3 May 2016 at 18:53, jhsolomon notifications@github.com wrote:

> Yesterday when I was loading data in Refine, it seemed like the
> performance was good. But today it is timing out, even on small packages.
> 
> Simon Fraser University: Open Journal Systems List: 20160503
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/13369381/14992913/67f0a2e4-1136-11e6-81ca-100d3aaf4911.png
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> https://github.com/k-int/gokb-phase1/issues/496#issuecomment-216611149

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo
GoodReads: https://www.goodreads.com/user/show/3106516-ian-ibbotson

**Comment by jhsolomon** [comment]
Re-tested Refine changes this morning. The performance is much better so far, but I can't complete the ingest. I get an error when I try to "Update GOKb".

Taylor & Francis Mental Health & Social Care 2016: 20160506

![image](https://cloud.githubusercontent.com/assets/13369381/15074071/e587e56a-136a-11e6-8f7d-927d8819ac1a.png)

**Comment by jhsolomon** [comment]
Re-retested and not able to ingest.

UNC Greensboro: OJS Journals: 20160506

![image](https://cloud.githubusercontent.com/assets/13369381/15076709/ecf2c01e-1378-11e6-88bc-83bacea1f200.png)

**Comment by ianibo** [comment]
Any better after tidy up? Be good if issues could have a definitive resolution or it's hard to know when we can close them -- and may be better to do reports on knowint.zendesk.com   rather than raise bug reports?

**Comment by jhsolomon** [comment]
yes, Refine performance is better, thanks!
