### ISSUE TITLE
Global search not working

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#497]
Global search is not working currently.

![image](https://cloud.githubusercontent.com/assets/13369381/15019612/bb7dec1c-11ec-11e6-8f7f-922efbaacdb1.png)

**Comment by jhsolomon** [comment]
also received error with Title search

![image](https://cloud.githubusercontent.com/assets/13369381/15079780/924320ea-1388-11e6-9fc0-6aa75fc76a52.png)

**Comment by ianibo** [comment]
Tagged test - if this happens again can we raise an issue on knowint.zendesk.com rather than an bug report here - this is caused by elasticsearch being down, so it's more an operational support issue than a software bug :)

**Comment by jhsolomon** [comment]
fix confirmed
