### ISSUE TITLE
Duplicate TIs in CRED

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#498]
There is something going on that is creating duplicate TIs with full TI records. If you delete one, you end up deleting both. This is also causing the pre-date and post-date warnings to not be able to reconcile in Refine.

Advances in Neuroimmunology, if you search for the ISSN in the title search, you get two identical records:
http://gokb.kuali.org/gokb/resource/show/org.gokb.cred.TitleInstance%3A48281
http://gokb.kuali.org/gokb/resource/show/org.gokb.cred.TitleInstance%3A48281

**Comment by ianibbo** [comment]
Ouch.. probably need to hold off whilst I investigate...

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com
Doodle: http://doodle.com/ianibbo

**Comment by ianibbo** [comment]
Phew - don't do that to me!

Looks like a second copy of the ISSN is being added to the record - most
likely a hypenation issue. They are then being reformatted and displayed.
Need to add a distinct keyword to the query to make the results unique, but
this is less worrying than it first appears!

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com
Doodle: http://doodle.com/ianibbo

**Comment by jhsolomon** [comment]
Perhaps the button can go on the Titles page?

![image](https://cloud.githubusercontent.com/assets/13369381/15045287/c0d8e804-12a7-11e6-85b1-999ac0ddecef.png)

**Comment by ianibo** [comment]
Deployed fix for repeating titles with same identifier. Can we create a separate issue for the duplicates report and stick it into a backlog category?

**Comment by jhsolomon** [comment]
Fix confirmed and backlog issue added #505
