### ISSUE TITLE
Duplicate taylor & francis Namespace

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#499]
Could you delete the multiple taylor & francis namespaces? 

![image](https://cloud.githubusercontent.com/assets/13369381/15044696/4c26a828-12a4-11e6-8506-559becd50489.png)

**Comment by ianibo** [comment]
Done.

**Comment by jhsolomon** [comment]
Almost! Could you also delete "taylor" and "Taylor & Francis".

TaylorAndFrancis should remain in the list.

**Comment by jhsolomon** [comment]
fix confirmed. request moved to zendesk.
