### ISSUE TITLE
Refine client hangs with a 'Working' message

### ISSUE THREAD

**Issue by ostephens** [k-int/gokb-phase1#5]
After successful ingest of a project (http://gokb.k-int.com/gokb/resource/show/org.gokb.refine.RefineProject%3A7230), go back into the project, Refine hangs with 'Working' message.

Output is:
23:58:59.570 [                   refine] GET /command/gokb/isUp (135353ms)
23:58:59.619 [                   refine] POST /command/core/get-importing-configuration (49ms)
23:58:59.644 [                   refine] GET /command/core/get-all-project-metadata (25ms)
23:58:59.784 [                   refine] GET /command/gokb/projectList (140ms)
23:59:02.025 [                   refine] GET /command/core/get-preference (2241ms)
23:59:02.030 [                   refine] GET /command/core/get-preference (5ms)
23:59:02.035 [                   refine] GET /command/gokb/isUp (5ms)
23:59:02.036 [                   refine] GET /command/core/get-project-metadata (1ms)
23:59:02.083 [                   refine] GET /command/core/get-project-metadata (47ms)
23:59:02.150 [                   refine] GET /command/core/get-models (67ms)
23:59:02.180 [                   refine] GET /command/core/get-history (30ms)
23:59:02.182 [                   refine] POST /command/core/get-rows (2ms)
23:59:02.184 [                   refine] GET /command/gokb/project-validate (2ms)
23:59:02.220 [                   refine] GET /command/gokb/project-validate (36ms)

**Comment by sosguthorpe** [comment]
Multiple packages were causing issue as code was expecting unique result in query. Changed and seems to have fixed it. It does bring up the issue of errors occurring in the API and how they should be fed through to refine.

Opened issue #6 to address this.
