### ISSUE TITLE
Error when trying to create a new org

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#500]
![image](https://cloud.githubusercontent.com/assets/13369381/15073715/16151c90-1369-11e6-9c80-ff4da02a8e77.png)

**Comment by ianibo** [comment]
Ouch! Looking

**Comment by jhsolomon** [comment]
And new source

![image](https://cloud.githubusercontent.com/assets/13369381/15073770/6a894526-1369-11e6-9b05-8263b690dd40.png)

**Comment by jhsolomon** [comment]
fix confirmed.
The previous workflow of clicking Create and Edit before typing in the text boxes is now fixed.
