### ISSUE TITLE
Delete empty orgs from CRED

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#501]
Can you delete these? Or is there a way that we can hide them?

![image](https://cloud.githubusercontent.com/assets/13369381/15076771/4a47f64e-1379-11e6-8c3b-59034589532e.png)

**Comment by ianibo** [comment]
Have added an ID column so that even when a name is missing you can still click on the records. Deleted records.

**Comment by jhsolomon** [comment]
fix confirmed
