### ISSUE TITLE
GOKb Refine extension is down

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#511]
![image](https://cloud.githubusercontent.com/assets/13369381/15328623/87aab014-1c23-11e6-909f-59ab0b5c71a2.png)

**Comment by ianibo** [comment]
Heya - restarted this server - can you let us know what button / link led
to this so we can put something a bit more defensive behind it?

Cheers,
e

On 17 May 2016 at 16:36, jhsolomon notifications@github.com wrote:

> [image: image]
> https://cloud.githubusercontent.com/assets/13369381/15328623/87aab014-1c23-11e6-909f-59ab0b5c71a2.png
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/k-int/gokb-phase1/issues/511

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo
GoodReads: https://www.goodreads.com/user/show/3106516-ian-ibbotson

**Comment by jhsolomon** [comment]
Sure thing!

https://gokb.k-int.com/gokb/api/downloadUpdate

On Tue, May 17, 2016 at 12:55 PM, Ian Ibbotson notifications@github.com
wrote:

> Heya - restarted this server - can you let us know what button / link led
> to this so we can put something a bit more defensive behind it?
> 
> Cheers,
> e
> 
> On 17 May 2016 at 16:36, jhsolomon notifications@github.com wrote:
> 
> > [image: image]
> > <
> > https://cloud.githubusercontent.com/assets/13369381/15328623/87aab014-1c23-11e6-909f-59ab0b5c71a2.png
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > https://github.com/k-int/gokb-phase1/issues/511
> 
> ## 
> 
> Ian Ibbotson
> W: http://ianibbo.me
> E: ianibbo@gmail.com
> skype: ianibbo
> twitter: ianibbo
> GoodReads: https://www.goodreads.com/user/show/3106516-ian-ibbotson
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/k-int/gokb-phase1/issues/511#issuecomment-219782086

## 

Jennifer Solomon
GOKb Editor, Acquisitions and Discovery
North Carolina State University Libraries
919-515-2743
j kristen_wilson@ncsu.eduhsolomo@ncsu.edu
