### ISSUE TITLE
Error when trying to change platform in TIPP record

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#514]
In TIPP : 291567 - Iowa Research Online: Global All Titles / Iowa Historical Review / null

I tried to click on the Platform and received an Error message.

![image](https://cloud.githubusercontent.com/assets/13369381/15394754/bc8a6c40-1da2-11e6-8cb2-b253c3b780ff.png)

![image](https://cloud.githubusercontent.com/assets/13369381/15394764/c72e4568-1da2-11e6-8f8b-ae4712d0ac40.png)

**Comment by ianibbo** [comment]
Yep, I added something to show rather than hide the platform. This link is
trying to link through to the platfrom rather than allow you to edit it -
since a TIPP can't really be a TIPP without a platform [So it should never
have been created, we need to discover how that happened]. We probably
don't want to make the click on the value open up a drop down to change the
platform, since the TIPP parts of a TIPP should be immutable?

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com
Doodle: http://doodle.com/ianibbo

**Comment by jhsolomon** [comment]
I _think_ this was a title that I added the package manually. It did not
force me to select a Platform, so that is probably where the issue began.
Could we force the Platform to be mandatory when adding a title to the
package?

[image: Inline image 1]

On Thu, May 19, 2016 at 9:36 AM, ianibbo notifications@github.com wrote:

> Yep, I added something to show rather than hide the platform. This link is
> trying to link through to the platfrom rather than allow you to edit it -
> since a TIPP can't really be a TIPP without a platform [So it should never
> have been created, we need to discover how that happened]. We probably
> don't want to make the click on the value open up a drop down to change the
> platform, since the TIPP parts of a TIPP should be immutable?
> 
> Ian Ibbotson
> Director
> Knowledge Integration Ltd
> 35 Paradise Street, Sheffield. S3 8PZ
> T: 0114 273 8271
> M: 07968 794 630
> W: http://www.k-int.com
> Doodle: http://doodle.com/ianibbo
> 
> On 19 May 2016 at 14:19, jhsolomon notifications@github.com wrote:
> 
> > In TIPP : 291567 - Iowa Research Online: Global All Titles / Iowa
> > Historical Review / null
> > 
> > I tried to click on the Platform and received an Error message.
> > 
> > [image: image]
> > <
> > https://cloud.githubusercontent.com/assets/13369381/15394754/bc8a6c40-1da2-11e6-8cb2-b253c3b780ff.png
> > 
> > [image: image]
> > <
> > https://cloud.githubusercontent.com/assets/13369381/15394764/c72e4568-1da2-11e6-8f8b-ae4712d0ac40.png
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > https://github.com/k-int/gokb-phase1/issues/514
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/k-int/gokb-phase1/issues/514#issuecomment-220326169

## 

Jennifer Solomon
GOKb Editor, Acquisitions and Discovery
North Carolina State University Libraries
919-515-2743
j kristen_wilson@ncsu.eduhsolomo@ncsu.edu

**Comment by ianibbo** [comment]
Yeah  think thats a good idea :)

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com
Doodle: http://doodle.com/ianibbo

**Comment by jhsolomon** [comment]
Ok I will put in a new issue!

**Comment by jhsolomon** [comment]
see #515
