### ISSUE TITLE
error screen in GOKb test package

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#523]
Nature Publishing Group: Nature Publishing Group Journals
http://test-gokb.kuali.org/gokb/resource/show/org.gokb.cred.Package%3A261803

![image](https://cloud.githubusercontent.com/assets/13369381/16230738/ff4e9774-3790-11e6-8fb7-ce5b08a8f17f.png)

**Comment by ianibo** [comment]
Hey Jennifer - Test is all over the place at the moment - probably best
stay away from it.

On 21 June 2016 at 14:18, jhsolomon notifications@github.com wrote:

> Nature Publishing Group: Nature Publishing Group Journals
> 
> http://test-gokb.kuali.org/gokb/resource/show/org.gokb.cred.Package%3A261803
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/13369381/16230738/ff4e9774-3790-11e6-8fb7-ce5b08a8f17f.png
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/k-int/gokb-phase1/issues/523, or mute the thread
> https://github.com/notifications/unsubscribe/AADQI-I3VZTN_w3cQcwFlYC5greGLbhGks5qN-StgaJpZM4I6uQv
> .

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo
GoodReads: https://www.goodreads.com/user/show/3106516-ian-ibbotson

**Comment by ianibo** [comment]
Closing - will retest once on new test box. k-int can't even connect to test server any more - so need to hold off until new server is in place.

**Comment by jhsolomon** [comment]
Thanks!

On Tue, Jun 21, 2016 at 9:22 AM, Ian Ibbotson notifications@github.com
wrote:

> Closed #523 https://github.com/k-int/gokb-phase1/issues/523.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/k-int/gokb-phase1/issues/523#event-699037583, or mute
> the thread
> https://github.com/notifications/unsubscribe/AMwAJV-6GdGzh3TPd-G-yfvXPkMzjoCzks5qN-WLgaJpZM4I6uQv
> .

## 

Jennifer Solomon
GOKb Editor, Acquisitions and Discovery
North Carolina State University Libraries
919-515-2743
j kristen_wilson@ncsu.eduhsolomo@ncsu.edu
