### ISSUE TITLE
Event date on Title History 

### ISSUE THREAD

**Issue by JNKint** [k-int/gokb-phase1#524]
Backlog request made by Jennifer:

Taken from Zendesk: https://knowint.zendesk.com/agent/tickets/2495

In Firefox, it is hard to navigate the dates. Is there a way to add a cursor or a more intuitive date field?

**Comment by sosguthorpe** [comment]
@jhsolomon Just had a look and the Calendar widget you get when you select the calendar seems pretty standard to me. Could you elaborate on what exactly the issue is or what you ideally would like to do?

**Comment by jhsolomon** [comment]
This was a request from a user and I think this is better resolved as a training issue. Thanks!
