### ISSUE TITLE
Error 503 : back-end server is at capacity

### ISSUE THREAD

**Issue by edelagnier** [k-int/gokb-phase1#525]
I would like to import the data through the gokb oai api, but the server is currently returning an error 503.

**Comment by ianibo** [comment]
Hi there - best to discuss with the GOKb team directly, ideally we keep git to software issues and the team manage service issues. For information, gokb has moved to https://gokb.openlibraryfoundation.org/.

**Comment by edelagnier** [comment]
Thank you, I will ask them there.
