### ISSUE TITLE
Journalinstance Error 500

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#526]
I searched for 1545-7230 Academic Psychiatry in Global Search. When I clicked on the link, I got the Error 500 screen.

![image](https://cloud.githubusercontent.com/assets/13369381/18519798/346c3de2-7a73-11e6-8e1f-3e8d24c6e577.png)

**Comment by ianibbo** [comment]
Crap - I forgot to reset the full text indexes - so these will be out of
sync with whats in the DB now - resetting now

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com
Doodle: http://doodle.com/ianibbo

**Comment by ianibo** [comment]
Closing - this was a deployment error not clearing down ES first.
