### ISSUE TITLE
Journalinstance vs Titleinstance

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#528]
Does that mean that ebooks are Ebookinstances? Or should we go back to Titleinstance? Or just Title?

**Comment by ianibo** [comment]
for GOKB you can just ignore the eBookInstance - in essence - Books and Journals are both Titles - so if a system contains 10 books and 10 journal records then you will see 20 titles (A mix of books and journals) You can just use Titles as you did before, but if you want to deal specifically / only with Books then feel free to use the Books collection, likewise with Journals.

The short story is : TitleInstance should work just as it did before, and you can safely ignore the other stuff (I may hide them, just to avoid confusion)

**Comment by ianibo** [comment]
Not sure how to resolve this one marked as a bug - can you add a specific thing that needs to be changed so we know what needs to be done to close the issue? ta.

**Comment by jhsolomon** [comment]
Oh that makes sense! I think this can stay as is.
