### ISSUE TITLE
Unable to make Variant Title "Authorized"

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#529]
This is for new title: 30172639.

I was creating a new title and when I selected "Make Authorized" I got an error screen.

![image](https://cloud.githubusercontent.com/assets/13369381/18521249/5a64b820-7a79-11e6-9002-2f4afd344ec7.png)

**Comment by ianibbo** [comment]
Ouch this is a bug

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com
Doodle: http://doodle.com/ianibbo

**Comment by ianibo** [comment]
Fix deployed to test, retest and close if fixed please, or re-allocate to @ianibo

**Comment by jhsolomon** [comment]
confirmed fix 9/20
