### ISSUE TITLE
A.A.U.T.A. news bulletin

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#530]
In reviewing the list of journal titles, I noticed that A.A.U.T.A. news bulletin has 6 versions. Is this because it does not have any identifiers?

**Comment by jhsolomon** [comment]
similarly, Accounting education (Sydney, N.S.W.) has 10 titles.

**Comment by ianibbo** [comment]
Yeah - that is not right... need to find a better way of handling this.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com
Doodle: http://doodle.com/ianibbo

**Comment by ianibo** [comment]
Update - waiting for import to find this title in package to retest - expecting soon.

**Comment by jhsolomon** [comment]
I ran Housekeeping yesterday, but it seems like a lot of issues are related to the incomplete dataload. @kristenwilson Please retest later this week.

**Comment by jhsolomon** [comment]
There are now 888 instances of Accounting Education.

![image](https://cloud.githubusercontent.com/assets/13369381/19972863/c3cf0966-a1b9-11e6-8c42-c20b9a011461.png)

**Comment by jhsolomon** [comment]
On Test there are 6 instances of the A.A.U.T.A news bulletin, but when I click on any of the links I get a 500 ERROR. There is 1 title visible on Live.

![image](https://cloud.githubusercontent.com/assets/13369381/20269020/7969ff5e-aa4f-11e6-983e-6f0298d21a58.png)

https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.JournalInstance%3A29710207

![image](https://cloud.githubusercontent.com/assets/13369381/20269054/92dc6e86-aa4f-11e6-8eca-af80f1a7e7e8.png)

http://gokb.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.TitleInstance%3A310117

**Comment by jhsolomon** [comment]
Fixed!
