### ISSUE TITLE
Co-ref service not working

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#532]
I'm getting an error screen when I click on the link to go to the Co-ref page.

![image](https://cloud.githubusercontent.com/assets/13369381/18525773/ea744ebe-7a8b-11e6-9075-87cc75e331c4.png)

**Comment by ianibbo** [comment]
Ok - Bug - same problem as authorize variant names - will fix and deploy in
the morning

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com
Doodle: http://doodle.com/ianibbo

**Comment by ianibo** [comment]
Link should be working on test again
![image](https://cloud.githubusercontent.com/assets/53283/18667923/816fae38-7f2a-11e6-9b29-fca245e6d8bf.png) Please retest and close if resolved, or re-allocate to ian.

**Comment by jhsolomon** [comment]
The co-ref link is working, but it is pulling in duplicate records, with multiple issues.
Is this because we have not run housekeeping yet?

![image](https://cloud.githubusercontent.com/assets/13369381/18668552/1e910aee-7f04-11e6-96a1-e4a55d064a29.png)

**Comment by ianibbo** [comment]
Yep

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com
Doodle: http://doodle.com/ianibbo

**Comment by jhsolomon** [comment]
I'll leave this open until later and then recheck after housekeeping.

**Comment by ianibo** [comment]
Housekeeping running now on test, should complete by 5pm UK time 4th Oct. Retest pls.

**Comment by jhsolomon** [comment]
Co-ref is working, but it's pulling in two different identifiers, both labeled as ISSNs.

1876-1666
https://gokb-test.openlibraryfoundation.org/gokb/coreference/index?nspart=&idpart=1876-1666

![image](https://cloud.githubusercontent.com/assets/13369381/19156293/5defca06-8baf-11e6-8c84-f7bba551d7a5.png)

**Comment by jhsolomon** [comment]
Working now
