### ISSUE TITLE
Multiple instances of same Org

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#533]
American Academy of Pediatrics is listed 10 times as an Org. 

American Academy of Psychiatry and Law is listed 2 times.

American Association for Cancer Research 9 times.

American Association for the Advancement of Science 5 times

Other Orgs are only listed once. Can you check on this?

**Comment by ianibbo** [comment]
Bug - investigating...

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com
Doodle: http://doodle.com/ianibbo
