### ISSUE TITLE
TIPPs

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#535]
In Test there are  17549 TIPPs compared to 98138 in Live. Does that seem like the right number after the clean-up?

**Comment by ianibbo** [comment]
It's not finished loading the packages yet - so better to just wait until
the final package has synced before doing these kinds of comparisons

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com
Doodle: http://doodle.com/ianibbo

**Comment by jhsolomon** [comment]
Closing this issue, as it is duplicated in #554
