### ISSUE TITLE
Identifiers that are not ISSNs are missing

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#537]
Only ISSNs and eISSNs are present in the title records. OCLC, Oxford, etc are no longer available.

**Comment by ianibbo** [comment]
Heya - Can you point me at a couple of test cases in the live DB with the
kinds of things that are missing please?

ta,
e

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com
Doodle: http://doodle.com/ianibbo

**Comment by ianibo** [comment]
Additional info - looks like these are in the source records: http://gokb.openlibraryfoundation.org/gokb/oai/titles?verb=GetRecord&metadataPrefix=gokb&identifier=org.gokb.cred.TitleInstance:24381

**Comment by ianibo** [comment]
Added changes to store non-class-one identifiers.
