### ISSUE TITLE
Package metadata is missing

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#539]
All package metadata is missing. Is this because it is still loading? 

Will the curatory group be repopulated?

**Comment by ianibo** [comment]
Need to add more metadata to package export::
https://gokb.openlibraryfoundation.org/gokb/oai/packages?verb=getRecord&metadataPrefix=gokb&identifier=org.gokb.cred.Package:128115

**Comment by ianibo** [comment]
Package handling updated - please add examples of packages on live and test where discrepancies are present.

**Comment by jhsolomon** [comment]
Looks like this is all coming in correctly, but will retest tomorrow when all packages have finished loading.

**Comment by jhsolomon** [comment]
Data is still missing, for example: https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Package%3A30018786

https://gokb.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Package%3A111773

Missing data:
Provider
Source
List verifier data
Curatory group
Nominal platform

Also, the Last Project field is no longer in Test. Is this correct?

**Comment by jhsolomon** [comment]
Closing this issue, as it is duplicated in #543
