### ISSUE TITLE
Title data elements missing 

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#542]
Missing
**OA status:** 
https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.JournalInstance%3A19636511#titledetails

http://gokb.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.TitleInstance%3A392924

**Edit Status**
https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.JournalInstance%3A9173153

http://gokb.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.TitleInstance%3A410115#identifiers

**Continuing Series**
https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.JournalInstance%3A17548881

http://gokb.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.TitleInstance%3A48769

**Custom Fields**
https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.JournalInstance%3A22239985#availability

http://gokb.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.TitleInstance%3A20928#identifiers

**Identifiers** 
https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.JournalInstance%3A22239985#availability

http://gokb.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.TitleInstance%3A20928#identifiers

All Data Elements
Title
Status
Status Reason
Latest Publisher
Imprint
Published From
Published To
Title History
Medium
OA Status
Continuing Series
Alternate Names
Identifiers
Publishers
Availability
Custom Fields
Review Tasks

**Comment by ianibo** [comment]
Title handling updated please list examples of title records in live and test with any additional discrepancies.

**Comment by jhsolomon** [comment]
Identifiers are coming in correctly. The other title data elements are sill missing.

**OA status:** 
https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.JournalInstance%3A19636511#titledetails

http://gokb.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.TitleInstance%3A392924

**Edit Status**
https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.JournalInstance%3A9173153

http://gokb.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.TitleInstance%3A410115#identifiers

**Continuing Series**
https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.JournalInstance%3A17548881

http://gokb.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.TitleInstance%3A48769

**Custom Fields**
https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.JournalInstance%3A22239985#availability

http://gokb.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.TitleInstance%3A20928#identifiers

**Comment by jhsolomon** [comment]
OA Status missing

https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.JournalInstance%3A19636511

![image](https://cloud.githubusercontent.com/assets/13369381/20277205/9f4b82c4-aa6d-11e6-89fc-ed7cd6433306.png)

http://gokb.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.TitleInstance%3A392924

![image](https://cloud.githubusercontent.com/assets/13369381/20277226/b54fbfe0-aa6d-11e6-85e3-43e9657a4d5c.png)

**Comment by jhsolomon** [comment]
Edit Status is incorrect, It should be Approved, not in In Progress.

https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.JournalInstance%3A9173153

![image](https://cloud.githubusercontent.com/assets/13369381/20277274/e1ba6cb0-aa6d-11e6-91b2-9660d64d9039.png)

http://gokb.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.TitleInstance%3A410115#identifiers

![image](https://cloud.githubusercontent.com/assets/13369381/20277286/ed5871d4-aa6d-11e6-8e75-4d0996dc0895.png)

**Comment by jhsolomon** [comment]
Continuing Series is missing.

https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.JournalInstance%3A17548881#titledetails

![image](https://cloud.githubusercontent.com/assets/13369381/20277335/14fd264e-aa6e-11e6-9221-41c6ed0e3d22.png)

http://gokb.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.TitleInstance%3A48769

![image](https://cloud.githubusercontent.com/assets/13369381/20277355/26685228-aa6e-11e6-8986-016cf7ae4423.png)

**Comment by jhsolomon** [comment]
Custom Field is missing data

https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.JournalInstance%3A22239985#addprops

![image](https://cloud.githubusercontent.com/assets/13369381/20277403/65c43ffe-aa6e-11e6-9641-6487de629721.png)

http://gokb.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.TitleInstance%3A20928#addprops

![image](https://cloud.githubusercontent.com/assets/13369381/20277413/716bb38c-aa6e-11e6-84e9-1cde02df9bdc.png)

**Comment by sosguthorpe** [comment]
This one should be fixed.

**Comment by jhsolomon** [comment]
@sosguthorpe The OA status and Continuing Series are missing.

https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.JournalInstance:22239985#titledetails

![image](https://cloud.githubusercontent.com/assets/13369381/20763348/a7829946-b6f7-11e6-9691-7149051188f2.png)


http://gokb.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.TitleInstance:20928

![image](https://cloud.githubusercontent.com/assets/13369381/20763362/b5f0c980-b6f7-11e6-8714-3ec0af89779a.png)

**Comment by sosguthorpe** [comment]
Ah yes. Thanks. Will fix after the packages are deployed.

**Comment by jhsolomon** [comment]
Great, the title elements look good.
