### ISSUE TITLE
Packages missing data elements

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#543]
Example: https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Package%3A30979125

http://gokb.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Package%3A244207

**Missing**
Provider
Source
Latest Project
List Verifier
List Verifier Date
Edit Status
Curatory Group
Breakable
Consistent
Fixed
Nominal Platform
Titles
Identifiers
Alternate Names

**Packages elements that were present**
Package Name
Update Method
Scope 
List Status
Decision Support
Activity
Payment Type
Global

**Comment by ianibo** [comment]
Package handling updated, please list records in test and live to show any discrepancies so we can investigate field by field.

**Comment by jhsolomon** [comment]
Packages are not coming through. 500 error.

![image](https://cloud.githubusercontent.com/assets/13369381/19481351/a261c1d8-951b-11e6-9cec-3c3b3ae8dba1.png)

**Comment by jhsolomon** [comment]
The package names all loaded, but the import did not complete and many of the packages are empty.

![image](https://cloud.githubusercontent.com/assets/13369381/19972025/37bdefde-a1b7-11e6-80e6-c17a35ad2b7e.png)

https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Package%3A30485523

**Comment by jhsolomon** [comment]
It looks like the packages are still loading, so I will continue to add to this issue as I see other items come up. 

For Taylor & Francis: African Studies, the only package element that is missing on Test that is on Live is the List Verifier Date
http://gokb.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Package%3A377462

![image](https://cloud.githubusercontent.com/assets/13369381/20277122/44c74c2a-aa6d-11e6-97e8-547f09aec466.png)

https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Package%3A30461022

![image](https://cloud.githubusercontent.com/assets/13369381/20277132/507406d0-aa6d-11e6-8901-94d7e33b7924.png)

**Comment by jhsolomon** [comment]
Some packages are missing Provider

https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Package%3A30323536

![screen shot 2016-12-02 at 11 14 08 am](https://cloud.githubusercontent.com/assets/13369381/20841136/b34ed7aa-b880-11e6-863f-49d404e5f9a0.png)

http://gokb.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Package%3A244206

![screen shot 2016-12-02 at 11 16 58 am](https://cloud.githubusercontent.com/assets/13369381/20841189/db487702-b880-11e6-929f-c339753415d1.png)

**Comment by sosguthorpe** [comment]
Can see that the provider is missing from the feed for that particular package. Will look into it.

**Comment by jhsolomon** [comment]
fixed 12/12
