### ISSUE TITLE
Missing packages

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#544]
American Chemical Society: Journals
http://gokb.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Package%3A244206

I could not find this current package in Test

**Comment by ianibo** [comment]
OK.. Package present: https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Package%3A31084159

BUT searching seems broken on package name - I think I know why. Please close this issue relating to missing packages - but we need to open a new one for searching with spaces

**Comment by jhsolomon** [comment]
fix confirmed
