### ISSUE TITLE
Organizations missing data elements

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#546]
https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Org%3A29708206
http://gokb.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Org%3A1042

https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Org%3A29370674
http://gokb.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Org%3A9250

**Missing**
Alternate Names
IDs
Packages
Roles
Source
Mission
Platforms
Published Titles

**Other data elements**
Name
Status
Reference
Licenses
Custom Fields
Review Tasks
Offices

**Comment by ianibo** [comment]
Phase 1 test : https://gokb.openlibraryfoundation.org/gokb/oai/orgs?verb=listRecords&metadataPrefix=gokb

Test org with props set::
https://gokb.openlibraryfoundation.org/gokb/oai/orgs?verb=getRecord&metadataPrefix=gokb&identifier=org.gokb.cred.Org:1

Orgs have variant names, IDs. Packages will be joined by loading packages.Not sure about Roles,

**Comment by ianibo** [comment]
Please list example records from live and test showing discrepancies for each missing field. Should be pulling data through now.

**Comment by jhsolomon** [comment]
American Chemical Society is missing:
Alternate Names
IDs
Roles

https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Org%3A29366019
http://gokb.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Org%3A1042

**Comment by ianibo** [comment]
http://gokb.openlibraryfoundation.org/gokb/oai/orgs?verb=listRecords&metadataPrefix=gokb

**Comment by jhsolomon** [comment]
Still missing data.

**Comment by jhsolomon** [comment]
@kristenwilson Please retest later this week.

**Comment by jhsolomon** [comment]
Orgs are still missing Roles.

https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Org%3A29366019

https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Org%3A29367370
http://gokb.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Org%3A7904

**Comment by jhsolomon** [comment]
Org is missing roles.

https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Org%3A29366019

![image](https://cloud.githubusercontent.com/assets/13369381/20278269/0fc95a40-aa72-11e6-9044-ae794349387f.png)

http://gokb.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Org%3A1042

![image](https://cloud.githubusercontent.com/assets/13369381/20278285/1aba257e-aa72-11e6-8d4f-ab1c4c2bf799.png)

**Comment by jhsolomon** [comment]
Org is adding a duplicate Alternate Name to the list. There are two instances of American Chemical Society and American Pharmaceutical Association on the list in Test.

https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Org%3A29366019

![image](https://cloud.githubusercontent.com/assets/13369381/20278339/4c29b1b0-aa72-11e6-8e68-4e76610c4ef5.png)

http://gokb.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Org%3A1042

![image](https://cloud.githubusercontent.com/assets/13369381/20278371/59be0d3a-aa72-11e6-8efe-64166d87de0b.png)

**Comment by sosguthorpe** [comment]
This should now be sorted.

**Comment by jhsolomon** [comment]
fixed 11/30
