### ISSUE TITLE
Data Files

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#548]
All data files are missing.

These should include:
Name
Status
Editable
GUID
MD5
Upload filename
Upload mime type
File size
Doctype
File
Attached to
Custom Fields
Review Request

**Comment by ianibo** [comment]
License Data

**Comment by jhsolomon** [comment]
All of the names are empty, but since the licenses are complete, I think the files are there. They are just not showing up properly in the data files window.

![image](https://cloud.githubusercontent.com/assets/13369381/19481188/22ffacca-951b-11e6-86c8-78a0b1393f80.png)

**Comment by jhsolomon** [comment]
@kristenwilson Please retest later this week.

**Comment by jhsolomon** [comment]
The files and components are loading correctly. I will check back on 11/3 to make sure that all of the newly added files are on Test. There should now be 27.

**Comment by jhsolomon** [comment]
I am closing this issue because the data files for the 18 licenses are all present.
