### ISSUE TITLE
Imprints

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#549]
Contains: Imprint Name

Currently, duplicated in all imprints.

**Comment by ianibo** [comment]
Any chance you and pick out a specific example of a title in live with an imprint and link here please?

**Comment by ianibo** [comment]
NVM -- found one http://gokb.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.TitleInstance%3A48146

**Comment by ianibo** [comment]
Looking at https://gokb.openlibraryfoundation.org/gokb/oai/titles?verb=GetRecord&metadataPrefix=gokb&identifier=org.gokb.cred.TitleInstance:48146 it appears that imprint appears twice in the record. Need to remove the second.

<gokb xmlns="http://www.gokb.org/oai_metadata/">
<title id="48146">
<name>Academic Pediatrics</name>
<imprint>Elsevier</imprint>
<medium>Journal</medium>
<OAStatus>Hybrid OA</OAStatus>
<continuingSeries>No</continuingSeries>
<publishedFrom>2009-01-01 00:00:00.0</publishedFrom>
<publishedTo />
<imprint>Elsevier</imprint>
<issuer />
<identifiers>
<identifier namespace="issn" value="1876-2859" />
<identifier namespace="elsevier" value="18762859" />
<identifier namespace="eissn" value="1876-2859" />
<identifier namespace="originEditUrl" value="https://gokb.openlibraryfoundaton.org/gokb/resource/show/org.gokb.cred.TitleInstance:48146" />
</identifiers>
<publisher id="4487">
<history>
<TIPPs count="5"></title>
</gokb>

**Comment by jhsolomon** [comment]
fix complete
