### ISSUE TITLE
Licenses

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#550]
All licenses are missing.

Should contain:
GOKb Shortcode
License Name
Status
Edit Status
License URL
License Type
Curatory Group
License Summary
Files

**Comment by ianibo** [comment]
Phase one checking::
http://gokb.openlibraryfoundation.org/gokb/oai/License?verb=listRecords&metadataPrefix=gokb

(Will become /licenses shortly)

**Comment by jhsolomon** [comment]
complete
