### ISSUE TITLE
Offices

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#551]
All offices are missing.

Should contain:
Name
Website
Email
Phone Number
Other Details
Address Line 1
Address Line 2
City
Zip/postcode
State
Province/County
Owner Org
Curatory Groups
Country

**Comment by ianibo** [comment]
Checking stage one :
https://gokb.openlibraryfoundation.org/gokb/oai/offices?verb=listRecords&metadataPrefix=gokb

Shows only one office in the system - suggest we add this by hand rather than automating.
