### ISSUE TITLE
Platforms missing data elements

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#552]
http://gokb.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Platform%3A67317

https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Platform%3A30979805

**Missing**
Provider 
Edit Status
Primary URL
Authentication

**Other data elements**
Software
Service
IP Auth Supported
Shibboleth Supported
User/Pass Supported
Alternate Names
Decision Support

**Comment by ianibo** [comment]
Properties should be coming through now, please list any missing along with links to live and test records showing differences.

**Comment by ianibo** [comment]
Package export looks pretty complete now: http://gokb.openlibraryfoundation.org/gokb/oai/packages?verb=getRecord&metadataPrefix=gokb&identifier=org.gokb.cred.Package%3A231459 so focussing on ingest currently

**Comment by jhsolomon** [comment]
There are only 5 platforms in Test vs 88 in Live.
![image](https://cloud.githubusercontent.com/assets/13369381/19480847/f68d5116-9519-11e6-9015-c8b2fabf7fe8.png)

Missing Alternate Name:
https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Platform%3A30073244
http://gokb.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Platform%3A195278

Missing Provider:
https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Platform%3A30019069
http://gokb.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Platform%3A75446

Missing Primary URL:
https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Platform%3A30073272
http://gokb.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Platform%3A195275

https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Platform%3A30073277
http://gokb.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Platform%3A195276

Missing Provider and URL:
https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Platform%3A30019069
http://gokb.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Platform%3A195275

Missing Source, Provider and URL:
https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Platform%3A29861635
http://gokb.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Platform%3A67319

**Comment by jhsolomon** [comment]
Today there are 62 platforms on Test vs 88 on Live. The following data elements are still not populating.

Missing Alternate Name:
https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Platform%3A30073244
http://gokb.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Platform%3A195278

Missing Provider:
https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Platform%3A30019069
http://gokb.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Platform%3A75446

Missing Source and Provider:
http://gokb.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Platform%3A195275
https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Platform%3A29433951

**Comment by jhsolomon** [comment]
Some platforms are still not loading. There are only 62 platforms on Test vs 88 on Live.

https://gokb-test.openlibraryfoundation.org/gokb/search/index?qbe=g%3A1platforms

![image](https://cloud.githubusercontent.com/assets/13369381/20278969/b39a968c-aa74-11e6-98cb-5b53a95dc5c7.png)

http://gokb.openlibraryfoundation.org/gokb/search/index?qbe=g%3A1platforms

![image](https://cloud.githubusercontent.com/assets/13369381/20278981/c2516106-aa74-11e6-9c7b-28725ac730e1.png)

**Comment by jhsolomon** [comment]
Missing Provider in Platform record.

https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Platform%3A29487253

![image](https://cloud.githubusercontent.com/assets/13369381/20279012/e353f35a-aa74-11e6-97e9-724cb0da7083.png)

http://gokb.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Platform%3A241905

![image](https://cloud.githubusercontent.com/assets/13369381/20279031/ef08a15a-aa74-11e6-96fb-2ee064e17836.png)

**Comment by jhsolomon** [comment]
Missing Source and Provider, but Primary URL is now loading properly.

https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Platform%3A29487311

![image](https://cloud.githubusercontent.com/assets/13369381/20279183/85a7c906-aa75-11e6-9435-5e49bdec6191.png)

http://gokb.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Platform%3A67319

![image](https://cloud.githubusercontent.com/assets/13369381/20279192/8f4b7e94-aa75-11e6-9f80-247446393656.png)

**Comment by sosguthorpe** [comment]
Think this should be complete now.

**Comment by jhsolomon** [comment]
fixed 11/30
