### ISSUE TITLE
Refdata categories

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#556]
**Contains**
Internal Id
Category name/ Description
Label
Values
KBComponent.Status
-Current
-Deleted
-Expected
-Retired
KBComponent.EditStatus
-Approved
-In Progress
-Rejected
TitleInstancePackagePlatform.Format
-Digitised
-Electronic 
-Print
TitleInstancePackagePlatform.DelayedOA
-No
-Unknown
-Yes
TitleInstancePackagePlatform.HybridOA
-No
-Unknown
-Yes
TitleInstancePackagePlatform.Primary
-No
-Yes
TitleInstancePackagePlatform.PaymentType
-Complimentary
-Free
-Limited Promotion
-OA
-Opt Out Promotion
-Paid
-Uncharged
-Unknown
TitleInstancePackagePlatform.CoverageDepth
-Abstracts
-Fulltext
-Selected Articles
Package.Scope
-Aggregator
-Back File
-Front File
-Master File
-Open Access
Package.ListStatus
-Checked
-In progress
Package.Breakable
-No
-Unknown
-Yes
Package.Consistent
-No
-Unknown
-Yes
Package.Fixed
-No
-Unknown
-Yes
Package.PaymentType
-Complimentary
-Free
-Limited Promotion
-Opt Out Promotion
-Paid 
-Uncharged
-Unknown
Package.LinkType
-Parent
-Previous
Package.Global
-Consortial
-Consortium
-Global
-Other
Platform.AuthMethod
-IP
-Open Access
-Shibboleth
-Unknown
-User Password
Platform.Role
-Admin
-Host

KBComponent Status does not match
https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.RefdataCategory%3A11

http://gokb.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.RefdataCategory%3A1

In Test, it is adding the Label that does not exist in Live. It is not displaying the sort key.

**Comment by ianibo** [comment]
Just summarising - KBComponent.Status is missing sort keys - is that the only difference?

**Comment by ianibo** [comment]
Ah - and label is set to the same as the name on test but not on live - tho label is not used anywhere afaik so has no functional impact?

**Comment by jhsolomon** [comment]
Yes, just missing the sort keys.
Should I continue listing out all of the refdata categories and values?

**Comment by ianibo** [comment]
Nope, I don't think that's needed thanks.

**Comment by jhsolomon** [comment]
The sort keys are still missing values. Is that expected because this is a default setting, or does that need to be added?
