### ISSUE TITLE
Users

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#557]
We will need to migrate all users from Live with all of their roles and curatory groups.

User Name
Display Name
Email
Curatory Groups
Home Org
Curatory Groups
Roles 
ROLE_USER
ROLE_EDITOR
ROLE_ADMIN
ROLE_CONTRIBUTOR
ROLE_API
ROLE_SUPERUSER
ROLE_REFINEUSER
ROLE_REFINETESTER

**Comment by ianibo** [comment]
Added the following wiki page that explains how to prepare a list of users in the current MySQL live environment : https://github.com/k-int/gokb-phase1/wiki/GOKb-Live-Server-Migration -- and added a script to scripts -- https://github.com/k-int/gokb-phase1/blob/dev-integration/scripts/sync_users.sh to migrate users - this should be done as the first step in the migration.

**Comment by ianibo** [comment]
Users should be loaded on to test now, roles not migrated yet whilst I double check that nothing odd is going on.

**Comment by jhsolomon** [comment]
Users are there, but not the roles:
kmhill6 should be a Contributor, but on Live is a User and on Test is nothing.
http://gokb.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.User%3A8
https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.User%3A29357933

kmblake should have all roles activated:
https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.User%3A29357932
http://gokb.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.User%3A7

**Comment by jhsolomon** [comment]
It looks like users with multiple roles are coming over correctly. For Viewers only, there are no roles selected in Test. Will they still be able to log in?

winkler4
http://gokb.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.User%3A9
https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.User%3A29357934

**Comment by jhsolomon** [comment]
The roles are correct, but are missing the curatory groups.

**Comment by jhsolomon** [comment]
The curatory groups are still missing from the user roles.

**Comment by jhsolomon** [comment]
Closing this issue since it is related to #547
