### ISSUE TITLE
Latest Publisher is showing as duplicate

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#562]
https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.JournalInstance%3A10701875#identifiers

**Comment by jhsolomon** [comment]
I'm not sure if this issue has been corrected or not.

Here is one example where the publisher is showing (correctly) once, but shows a last updated date of 31 October:
https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.JournalInstance%3A24577075

Whereas Academic Psychiatry is still showing the duplicated publisher name and a last updated date of 2 November:
https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.JournalInstance%3A10701875

**Comment by sosguthorpe** [comment]
This is very likely a duplicate of #565

**Comment by sosguthorpe** [comment]
@jhsolomon My local copy is now correctly importing the publisher history and not just concatenating their names. However the fact that this particular Title shows SpringerSpringer brings to light an issue with the original data. 

The title:
http://gokb.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.TitleInstance%3A39490#publishers
has 2 entries for Springer as the publisher both without end dates but with differing start dates. The import code will only save the first entry it comes across with that end-date and publisher.

**Comment by jhsolomon** [comment]
Fix confirmed 11/14
