### ISSUE TITLE
Inconsistent method usage for string normalization

### ISSUE THREAD

**Issue by hornmo** [k-int/gokb-phase1#564]
It looks like two different methods are used to normalize strings (which are then used to look for possible duplicates):
TSVIngestionService and KBComponentVariantName are still using GOKbTextUtils.normaliseString, while KBComponents and the TitleLookupService are using GOKbTextUtils.norm2

This may also explain #561 and #562

**Comment by ianibo** [comment]
This is fixed on the ebooks_pilot branch which is the baseline branch for v7.

**Comment by hornmo** [comment]
As it seems, the old method is still used in some places:

- IntegrationController in assertJsonldPlatform() 
- 2x in server/gokb/src/groovy/com/k_int/HQLBuilder.groovy
