### ISSUE TITLE
Org names combined

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#565]
Most of the org names loaded correctly, but Taylor and Francis has 14 iterations.

![image](https://cloud.githubusercontent.com/assets/13369381/19968523/4e9e8c56-a1ab-11e6-97a4-be113465920c.png)

**Comment by sosguthorpe** [comment]
I'm fixing this issue now. It is the title import combining the entire publisher history into one string.

**Comment by sosguthorpe** [comment]
I'm fixing this issue now. It is the title import combining the entire publisher history into one string.

**Comment by sosguthorpe** [comment]
I'm fixing this issue now. It is the title import combining the entire publisher history into one string.

**Comment by sosguthorpe** [comment]
Closing this one as a duplicate.
