### ISSUE TITLE
Data files that seem to have appeared out of nowhere

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#566]
Since we began testing, I am fairly sure that there have always been 18 data files that matched with the 18 licenses. Does anyone have an idea where the additional 9 files came from? The last updated dates are not at all recent and the users who added them are Viewers, so how is this even possible?

Should we manually add these to Test?

For example:
http://gokb.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.DataFile%3A195069

**Comment by kristenwilson** [comment]
Looking at live, we do have 18 licenses, but 27 data files (http://gokb.openlibraryfoundation.org/gokb/search/index?qbe=g%3AdataFiles) . The 9 files that are not related to licenses seem to be random stuff like pdfs of ebooks and KBART formatted title lists. Perhaps some users uploaded these files not understanding the purpose? 

It does look like the migration is working properly. I'd suggest that we just review the data files and delete anything that's not a legitimate ONIX-PL license file. Jennifer, does that sound good? If so, I think we can close this issue.

**Comment by jhsolomon** [comment]
The strange part was that I really don't remember when those data files showed up. And I did not think that Viewers would be able to upload files. 

But yes, I agree we can delete the files that are not legitimate ONIX-PL license files.
