### ISSUE TITLE
Housekeeping not working

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#567]
I am guessing this part of the larger issue with the import, but the housekeeping function does not seem to be working. This morning there were 1,791,836 titles and I've run housekeeping twice now and there are still 1,791,836 titles. 

In Live there are currently 46,000 titles, so there should be far fewer titles than that.

**Comment by sosguthorpe** [comment]
There were about 1,700,000 imported and show with "Unknown Title" as the name. These titles all have identifiers that are matched against when we import from GOKb live, and the extra info from live is fed into the Unknown title to update it into something we do know about. So after GOKb title import has ruhn I would always expect at least ~1,700,000 titles to be in there. Housekeeping will never delete these unknown titles, so I think there is a misunderstanding of what the housekeeping function is supposed to do here.

**Comment by jhsolomon** [comment]
Ian added housekeeping to list of post-deployment actions.
https://github.com/k-int/gokb-phase1/wiki/Actions-after-update
