### ISSUE TITLE
Licenses and Data Files missing from Test

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#569]
I can not see any of the Licenses or Data Files.

https://gokb-test.openlibraryfoundation.org/gokb/search/index?qbe=g%3ALicenses

![image](https://cloud.githubusercontent.com/assets/13369381/20283285/5f072a7e-aa86-11e6-9f21-91f53aeafb75.png)

http://gokb.openlibraryfoundation.org/gokb/search/index?qbe=g%3ALicenses

![image](https://cloud.githubusercontent.com/assets/13369381/20283335/8c684d9a-aa86-11e6-9cfa-6fb64dfe1d08.png)

**Comment by sosguthorpe** [comment]
This should now be fixed.

**Comment by jhsolomon** [comment]
fixed 11/30
