### ISSUE TITLE
Missing Imprints

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#570]
There are 57 imprints on Test vs 81 in Live.

https://gokb-test.openlibraryfoundation.org/gokb/search/index?qbe=g%3Aimprints

![image](https://cloud.githubusercontent.com/assets/13369381/20283461/28f55e82-aa87-11e6-826a-371c9519a17b.png)

http://gokb.openlibraryfoundation.org/gokb/search/index?qbe=g%3Aimprints

![image](https://cloud.githubusercontent.com/assets/13369381/20283471/2f8f09c8-aa87-11e6-86a3-2aed75f8262b.png)

**Comment by sosguthorpe** [comment]
Imprints are not copied over as is. They are added when they are encountered and this means that if the imprints are not related to another component they will not be in the new data.

**Comment by jhsolomon** [comment]
ok
