### ISSUE TITLE
OA status missing Hybrid OA option

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#571]
In creating a new title, the Hybird OA option is missing from the drop-down menu.

https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.TitleInstance%3A30521878#titledetails

![image](https://cloud.githubusercontent.com/assets/13369381/20283723/20eba560-aa88-11e6-9274-72151d124faa.png)

**Comment by ianibo** [comment]
Hybrid OA added to refdata defaults. However, please note that it wasn't present in the default data for live either, so likely it was manually added, and if used in any record, should have been auto-created, which means it's unlikely that it is actually used in any records.

**Comment by jhsolomon** [comment]
Most of the time, the OA status is added post-ingest. We do have a number of titles that are Hybrid OA. 
Here is one example:

http://gokb.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.TitleInstance%3A17178
