### ISSUE TITLE
Duplicate LOC control numbers

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#572]
This seems to be a new issue. The ISSNs look good, but now there are multiple instances of the LOC control number.

https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.JournalInstance:22239985#identifiers

![screen shot 2016-12-02 at 11 19 34 am](https://cloud.githubusercontent.com/assets/13369381/20841322/5ef8fec8-b881-11e6-90a4-bc20b089ae37.png)

**Comment by sosguthorpe** [comment]
Not sure why that particular Identifier has been duplicated. Will add some cleanup and also look into why it happened in the first place.

**Comment by jhsolomon** [comment]
fixed 12/12
