### ISSUE TITLE
Macros missing from Test

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#573]
I just noticed that all of the macros are missing from Test. There are 46 on Live.
http://gokb.openlibraryfoundation.org/gokb/search/index?qbe=g%3AMacros

**Comment by jhsolomon** [comment]
There are now 2 macros in Test.

![image](https://cloud.githubusercontent.com/assets/13369381/21363817/237a07cc-c6bc-11e6-9e7c-c73909878fa3.png)

**Comment by ianibo** [comment]
This is still in dev - no changes here yet so pls don't test

**Comment by sosguthorpe** [comment]
Macros have been imported. Note: 2 were skipped that didn't have a "name" or actual transformations applied.

**Comment by jhsolomon** [comment]
fixed 1/9/17
