### ISSUE TITLE
Reconciliation for Organization names is not linked in Refine

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#576]
![image](https://cloud.githubusercontent.com/assets/13369381/21148193/70bf0dbc-c125-11e6-8014-c38ed1da5b53.png)

**Comment by sosguthorpe** [comment]
Partially fixed! Can't seem to get orgs to be indexed though. Currently only 3 types in the index.
@ianibbo Hopefully you have an idea?

**Comment by ianibo** [comment]
Heya - Right - Prior to this version we used to just index all KBComponent instances (Checked by looking in v3_maint branch). Now that we're indexing specific subclasses we will need to explicitly add any component types we want adding -- Adding orgs now.

**Comment by ianibo** [comment]
(For reference) https://github.com/k-int/gokb-phase1/blob/3_0_maintenance/server/gokb/grails-app/services/org/gokb/FTUpdateService.groovy

**Comment by ianibo** [comment]
Added in commit e64a2edad05a107cc57b90ab88e2b3090c1cc068 - built - needs a test and a deploy. Steve - am I ok to do a deploy?

**Comment by jhsolomon** [comment]
fixed 12/20
