### ISSUE TITLE
Last updated column on Packages page not updating

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#579]
I just ingested this package, but the web app does not reflect the current date/time.

![image](https://cloud.githubusercontent.com/assets/13369381/21354859/aa8bfde2-c699-11e6-9dce-db85bf680ae7.png)

**Comment by ianibo** [comment]
Fixed an issue where only the last updated date was being used to find records for indexing in elasticsearch. Newly created records don't have a last updated date, only a dateCreated so were being skipped. Fixed issue, deployed, running full re-index now.

**Comment by ianibo** [comment]
lastUpdated is only touched for updated packages - for new packages the dateCreated field is populated. Can add the dateCreated field to list display if that helps?

**Comment by jhsolomon** [comment]
No, that's ok, we don't need the dateCreated field on that page view. 

However, just to clarify, this package was not a newly created package, it was an updated package.

**Comment by sosguthorpe** [comment]
So I think this is because the Package doesn't actually change. Only the associated TIPPs are changed and I would think that this is the same behaviour as live.
Maybe we should look at this in the next phase as I'm pretty sure it's "as live" and also none-breaking?

**Comment by jhsolomon** [comment]
fixed 1/10/17
