### ISSUE TITLE
Last Updated in Package page not updating

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#580]
Within the package page, the Last Updated field is not updating.

https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Package%3A30307307

![image](https://cloud.githubusercontent.com/assets/13369381/21354916/f1f02a8c-c699-11e6-94c6-8b3a5aa56a02.png)

**Comment by ianibo** [comment]
Duplicate of #579 -- same issue.

**Comment by sosguthorpe** [comment]
Closing as duplicate.
