### ISSUE TITLE
Package says partially ingested in Refine, but no titles in the web app

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#581]
After I loaded the Royal Society of Chemistry: RSC Journals CRKN package, Refine shows that this was partially ingested (with 5 titles not ingested). However, in the web app, there are no titles in the package and no review issues. 

https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Package%3A30306582

![image](https://cloud.githubusercontent.com/assets/13369381/21809379/6b1202f6-d715-11e6-8264-f21843b13fa9.png)

In Live, there are 133 titles in this package.
http://gokb.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Package%3A274092

![image](https://cloud.githubusercontent.com/assets/13369381/21809384/793758cc-d715-11e6-8d2d-e686a0a0701f.png)

Could this be related to #579?

**Comment by sosguthorpe** [comment]
No related. Means 1 or more rows failed. Looks like the platform isn't matching an existing platform in GOKb.

**Comment by jhsolomon** [comment]
fixed 1/10/17
