### ISSUE TITLE
Update Method field not updated

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#582]
After ingest, the Update Method did not populate.

https://gokb-test.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Package%3A30306582

![image](https://cloud.githubusercontent.com/assets/13369381/21809482/ef7f33c4-d715-11e6-97cf-d467539f9d48.png)

**Comment by sosguthorpe** [comment]
Closing as duplicate of #582.
#580 Already closed for this reason too.

**Comment by jhsolomon** [comment]
fixed 1/10/17
