### ISSUE TITLE
Coreference service returning multiple titles

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#587]
Apologies if I've asked this question before...But should we expect to see multiple results in the corefernce service?

For example, 0004-5497 Bulletin de l'Association française pour l'étude du cancer:
In Live, when I search for the ISSN, I get one result.
![image](https://cloud.githubusercontent.com/assets/13369381/21868354/6116daae-d820-11e6-89eb-f1a140382cfa.png)

But in Test, I get two identical results.
![image](https://cloud.githubusercontent.com/assets/13369381/21868375/6eb94fb6-d820-11e6-9f80-349dbc4eb09e.png)

**Comment by sosguthorpe** [comment]
This is because of the 2 hits on the search. It returns 2 rows 1 for matching the issnl and one for matching the issn. Both rows map to the same component so you see the same one twice. It is the same reason that #563 was added.

**Comment by jhsolomon** [comment]
that makes sense, thanks!
