### ISSUE TITLE
Grails error on trying to update 'Deprecate' value in Web UI

### ISSUE THREAD

**Issue by ostephens** [k-int/gokb-phase1#59]
TitleInstancePackagePlatform.PaymentType - tried to use ‘Deprecate’ to point ‘Unkown’ at ‘Unknown’ got error:

<h1>Error 500: Internal Server Error</h1>

<dl class="error-details">
<dt>URI</dt><dd>/gokb/ajaxSupport/genericSetRel</dd>
<dt>Class</dt><dd>groovy.lang.MissingPropertyException</dd><dt>Message</dt><dd>No such property: useInstead for class: org.gokb.cred.RefdataCategory</dd></dl><h2>Trace</h2><pre class="stack"> Line | Method
-&gt;&gt; 358 | genericSetRel in org.gokb.AjaxSupportController

---

| 195 | doFilter in grails.plugin.cache.web.filter.PageFragmentCachingFilter
| 63 | doFilter . . in grails.plugin.cache.web.filter.AbstractFilter
| 1110 | runWorker in java.util.concurrent.ThreadPoolExecutor
| 603 | run . . . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^ 722 | run in java.lang.Thread

**Comment by ianibbo** [comment]
Eek! thx!

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com
