### ISSUE TITLE
Data review request for Deleted TIPPs

### ISSUE THREAD

**Issue by ostephens** [k-int/gokb-phase1#63]
On Incremental Package update Data Review requests are now created for TIPPs that exist in the current Package but are not in update. This is correct behaviour for TIPPs with status Current.

However Data Review requests are being created when TIPP in current Package has status Deleted. e.g. http://gokb.k-int.com/gokb/search/index?qbe=g%3AreviewRequests&max=100&det=12

If TIPP has status Deleted then would be expected not to be in update, therefore no review request should be created.

Believe same logic should apply if TIPP has status Retired - no review request needed.

**Comment by sosguthorpe** [comment]
Added check to ensure TIPP is current before raising review request.

**Comment by ostephens** [comment]
Fixed
