### ISSUE TITLE
Expected behaviour on Incremental Update to Package with Current TIPP in import and Retired TIPP in CRED

### ISSUE THREAD

**Issue by ostephens** [k-int/gokb-phase1#65]
Scenario:

Updating a Package which contains a TIPP for 'Arms & Armour' with status of 'Retired'
Update has a row for 'Arms & Armour' with status of 'Current'

What is expected behaviour in this scenario? At the moment this seems to ignore the 'Retired' TIPP and create a new TIPP for the TI with Current status - this seems to be what happened in
http://gokb.k-int.com/gokb/search/index?qbe=g%3Atipps&qp_pkg_id=39709 - two TIPPs for Arms & Armour.

I'm not actually sure what the expected behaviour is here. I think I expected the existing TIPP to have it's Status updated to 'Current' from 'Retired' - but I can see this working either way.

Think at the moment I'd like to just check the behaviour is as you expect, and if so that's OK.

**Comment by ostephens** [comment]
After discussion OS/II/SO agree avoid creating new TIPPs - just update the status

**Comment by ostephens** [comment]
Still behaving as previously. If there is an 'Expected' or 'Retired' to TIPP, pushing an identical TIPP with status of 'Current' creates a new TIPP rather than updating the existing 'Expected' or 'Retired' TIPP

See http://gokb.k-int.com/gokb/search/index?qbe=g%3Atipps&qp_pkg_id=39767 just updated

**Comment by sosguthorpe** [comment]
Should now be fixed. Somehow lost my changes.

**Comment by ostephens** [comment]
Fixed
