### ISSUE TITLE
Support for importing custom fields via Refine

### ISSUE THREAD

**Issue by ostephens** [k-int/gokb-phase1#66]
It looks like this is still not supported?
As per spec 2.10:

2.10 Support for ‘user defined’ fields in import against TI or TIPP
    Sometimes there is information available in files that we don’t want to lose, but we don’t have defined property for it. Should support a form for column naming of gokb.ti.{fieldname}, gokb.tipp.{fieldname} which allows the addition of a field of a user-defined type to be stored. See 2.1.27
    To help prevent duplication of similarly named user defined fields, enable lookup of existing fieldnames when adding column name

**Comment by ostephens** [comment]
See Project "GOKb:Test:TICustomFieldCreate"

**Comment by sosguthorpe** [comment]
Should be fixed.

**Comment by ostephens** [comment]
Fixed
