### ISSUE TITLE
Editing cells using "Apply to all identical cells" doesn't work if cells are blank or null

### ISSUE THREAD

**Issue by ostephens** [k-int/gokb-phase1#67]
The 'Apply to all identical cells' does not seem to work if the cell edited (and identical cells) are blank or null

Works fine if cells are populated with some data (at least, tested strings)

**Comment by sosguthorpe** [comment]
Yeah this is a bug with refine. Not sure how easy it will be to override that function TBH. It may be worth investigating whether it works for the newest refine version or not.

**Comment by ostephens** [comment]
Also broken in Open Refine 2.6 beta - but if general refine issue I think we should follow up via that route

**Comment by ostephens** [comment]
Open issue on Open Refine github - closing here
https://github.com/OpenRefine/OpenRefine/issues/180
