### ISSUE TITLE
Act on data coming from Refine in 'platform.myType.name' col

### ISSUE THREAD

**Issue by ostephens** [k-int/gokb-phase1#70]
At the moment ingest process only acts upon data in col if headed 'platform.host.xxx'. To support other types of platform being set on ingest should act on values other than 'host' in this format.

NB whole modelling of platforms under review for R3 of GOKb, so maybe worth holding off until a way forward with Platforms better defined

**Comment by sosguthorpe** [comment]
Worth noting that as the Model currently stands we have 2 combo-based properties set against a TIPP:

TIPP.hostPlatform
TIPP.additionalPlatforms

Currently the platform specified in 'platform.host...' is stored in hostPlatform and nothing happens with additionalPlatforms.

**Comment by ostephens** [comment]
Closed as no demand to record other platform types in GOKb
