### ISSUE TITLE
If you try to view a Review Request that is no longer listed, get an Out of Bounds exception

### ISSUE THREAD

**Issue by ostephens** [k-int/gokb-phase1#71]
E.g. http://gokb.k-int.com/gokb/search/index?qbe=g%3AreviewRequests&det=23&qp_status=org.gokb.cred.RefdataValue%3A337&qp_user=&offset=20

Gives error:

Error 500: Internal Server Error
URI
/gokb/search/index
Class
java.lang.IndexOutOfBoundsException
Message
Index: 2, Size: 2

 Line | Method
->> 547 | RangeCheck in java.util.ArrayList

---

|   322 | get        in     ''
|   127 | get . . .  in grails.orm.PagedResultList
|    50 | index      in org.gokb.SearchController
|   195 | doFilter . in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|    63 | doFilter   in grails.plugin.cache.web.filter.AbstractFilter
|   886 | runTask .  in java.util.concurrent.ThreadPoolExecutor$Worker
|   908 | run        in     ''
^   662 | run . . .  in java.lang.Thread

This can occur if you have a filter (e.g.) for 'only show items with status of 'Needs Review' and you are updating status from 'Needs Review' to 'Reviewed'. Since the update doesn't refresh the screen, the next item in the list still has the old URL under the 'show' - as the number of items in the list has reduced, sometimes the URL points to a now non-existant list item (that barely makes sense to me, and I know what I mean)

**Comment by kristenwilson** [comment]
I thought this was fixed,but am seeing this error now when working with review tasks. What happens is that I'm looking at the second to last record using the quick view in a list of review tasks that is filtered to open. I close the review task that I'm looking at, then try to page to the next task. I get the out of bounds exception that Owen references above. 

Error 500: Internal Server Error

URI
    /gokb/search/index
Class
    java.lang.IndexOutOfBoundsException
Message
    Index: 7, Size: 7

 Line | Method
->>  635 | rangeCheck in java.util.ArrayList

---

|    411 | get        in     ''
|     70 | index . .  in org.gokb.SearchController
|    198 | doFilter   in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter . in grails.plugin.cache.web.filter.AbstractFilter
|    150 | invoke     in net.bull.javamelody.JspWrapper
|    285 | invoke . . in net.bull.javamelody.JdbcWrapper$DelegatingInvocationHandler
|    202 | doFilter   in net.bull.javamelody.MonitoringFilter
|    180 | doFilter . in     ''
|     82 | doFilter   in com.brandseye.cors.CorsFilter
|   1145 | runWorker  in java.util.concurrent.ThreadPoolExecutor
|    615 | run        in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run . . .  in java.lang.Thread

**Comment by kristenwilson** [comment]
Here's a demo of this problem, which is still occurring. See screencast for more info: http://screencast.com/t/hqUDtnJmqzR

**Comment by kristenwilson** [comment]
This is still happening exactly as described in the previous screencast.
