### ISSUE TITLE
Once a custom field has been added, can only add custom fields with same value

### ISSUE THREAD

**Issue by ostephens** [k-int/gokb-phase1#72]
I can add a custom field to a TI or TIPP with any name if there is no existing custom field on that TI/TIPP

However, if there already exists a custom field on that TI/TIPP I can only ingest using the same name as the existing custom field

**Comment by sosguthorpe** [comment]
Actually you can only add a field with a different value. I have released a fix but waiting on Ian to deploy on kuali.

**Comment by ostephens** [comment]
Ah - ok. Have updated issue to reflect actual issue :)

**Comment by ostephens** [comment]
Fixed
