### ISSUE TITLE
When ingesting project with custom field, if custom field already exists the new value should be concatenated with existing text

### ISSUE THREAD

**Issue by ostephens** [k-int/gokb-phase1#73]
Currently results in another custom field being added - see also #72

**Comment by sosguthorpe** [comment]
This just needs the UI to group values with the same property key. I was going to concatenate at a data level but it becomes difficult to see if something has already been appended or not. So multiple properties with same key seems the way to go.

**Comment by ostephens** [comment]
Ok - makes sense

**Comment by sosguthorpe** [comment]
Should be fixed.

**Comment by ostephens** [comment]
Fixed
