### ISSUE TITLE
Typo on http://gokb.k-int.com/gokb/upload/index

### ISSUE THREAD

**Issue by ostephens** [k-int/gokb-phase1#76]
On http://gokb.k-int.com/gokb/upload/index should be "ONIX-PL" not "ONYX"
Also "recognise" not "recognised"
Also "Please note - The system only maintains a unique copy of each file. repeat uploads will not be processed as new files." ; 'repeat' should be 'Repeat'

**Comment by ianibo** [comment]
Changed ONIX and repeat.. can you confirm you really want "recognise" not "recognised"?

**Comment by ostephens** [comment]
No - I'm clearly talking nonsense
