### ISSUE TITLE
Package quick create + Refine ingest results in two package records

### ISSUE THREAD

**Issue by ostephens** [k-int/gokb-phase1#79]
I'm creating a new Refine project for a new Package, using the new 'create Package' option then ingesting the project contents using 'Incremental Update'.

Result is I get two packages in GOKb, one named correctly and the other named with the identifier added - so:

OECD:Serials:OS1 = http://gokb.k-int.com/gokb/resource/show/org.gokb.cred.Package%3A40260
OECD:Serials:OS1::{Package:40260} = http://gokb.k-int.com/gokb/resource/show/org.gokb.cred.Package%3A40262

It is the latter one (presumably created in the Ingest process after the value has been put in the package.name col) that has the TIPPs created against it. The other package (with the correct name) has no TIPPs

**Comment by sosguthorpe** [comment]
Closing as cause is best described in referenced issue
