### ISSUE TITLE
Can't submit action using button on resource display page

### ISSUE THREAD

**Issue by ianibo** [k-int/gokb-phase1#80]
Heya.. 

Can't seem to cause the action mini-form on resource show page using the button type=submit. Added an input type=submit and that seems to work OK. Happened in chrome Version 30.0.1599.114 Ubuntu 13.10 (30.0.1599.114-0ubuntu0.13.10.2).

**Comment by ianibo** [comment]
Ah.. delete seems to trigger some confirmation JS, but title transfer seems blocked.. any ideas? ta.

**Comment by sosguthorpe** [comment]
Was being selected over which actions needed confirmation, have removed that. Also, fixed the error that was preventing the submit.
