### ISSUE TITLE
Field Notes - Using the link widget prevents clicking save for some reason

### ISSUE THREAD

**Issue by ianibo** [k-int/gokb-phase1#81]
As above, using the link widget seems to cause the save button to not work. All other widgets seem to work well. Just remove the link for now unless easy fix. Looking Good!

**Comment by sosguthorpe** [comment]
The link dialog seems to be fine to me? Successfully saved a note with a link in there.

**Comment by ianibo** [comment]
Yep, the dialog is fine, but I couldn't then click on the save button to actually save the note text containing a link?

**Comment by ianibo** [comment]
Ah scratch that - Done a pull and everything looks peachy on my laptop. Sorry.
