### ISSUE TITLE
Refine Ingest creates new Package when one already exists

### ISSUE THREAD

**Issue by ostephens** [k-int/gokb-phase1#92]
It is now required that package names in the package.name column are looked up from GOKb. These looked up values are like:

A.P. Publications Limited::{Package:40793}

Once the names are in this format the ingest can proceed.

However, on ingest a new Package using this full string as the name, rather than matching against the existing package with this name and ID. e.g. 

There existed a package "A.P. Publications Limited" with ID 40793 - http://gokb.k-int.com/gokb/resource/show/org.gokb.cred.Package%3A40793

The package.name column was populated with "A.P. Publications Limited::{Package:40793}" via a GOKb lookup

On Ingest a new package was created called "A.P. Publications Limited::{Package:40793}" with ID 40798 - http://gokb.k-int.com/gokb/resource/show/org.gokb.cred.Package%3A40798

This new package has the content, while http://gokb.k-int.com/gokb/resource/show/org.gokb.cred.Package%3A40793 has no titles attached

**Comment by sosguthorpe** [comment]
Yep. Packages not being looked up properly by the ingest service.

Related to #79

**Comment by sosguthorpe** [comment]
OK. This should now be fixed. The ingest service now looks up the packages.

Also made the package name column mandatory as the quick create can be used to create a package name. No packages should be derived from now on.

**Comment by sosguthorpe** [comment]
Packages need to be looked up now in refine
