### ISSUE TITLE
Project references need to be updated in the refine project

### ISSUE THREAD

**Issue by sosguthorpe** [k-int/gokb-phase1#94]
I have discovered a problem with the replacement (none-incremental) ingest now though. That is if you reference a package in refine, that package will be retired and a new one created in it's place. But the data within refine now references the old retired package.
This is something that has been missed in the thinking behind this and needs addressing. The data within the project should be updated.

**Comment by ostephens** [comment]
I think some discussion of how people think package 'replacement' should work is worth a discussion with the data managers and particular Kristen. Shall I raise it on the mailing list?

**Comment by sosguthorpe** [comment]
Will hang tight with this issue now as it's open to discussion as to whether we need the 'replacement'

**Comment by sosguthorpe** [comment]
Closing this issue as we the replace package option is no longer in refine.
