### ISSUE TITLE
Clicking on Title in Title History display uses wrong URL

### ISSUE THREAD

**Issue by ostephens** [k-int/gokb-phase1#96]
When viewing a title history on a Title Details page (e.g. http://gokb.k-int.com/gokb/resource/show/org.gokb.cred.TitleInstance%3A17059) the Title links in the Before/After columns link to

http://gokb.k-int.com/gokb/resource/view/org.gokb.cred.TitleInstance%3A17059

Should be

http://gokb.k-int.com/gokb/resource/show/org.gokb.cred.TitleInstance%3A17059

**Comment by sosguthorpe** [comment]
This one should be fixed.

**Comment by kristenwilson** [comment]
Confirmed fixed
