### ISSUE TITLE
Add "state" field to Office record

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#98]
The Office record doesn't contain a "state" field for US addresses. Can we add one?

**Comment by sosguthorpe** [comment]
Is region something semantically different to State/County? Is it the case that the current region field needs relabelling or do we definitely need a new State/County field?

**Comment by kristenwilson** [comment]
I think that most people in the US just wouldn't recognize region as part of a standard address. State would be clearer. I'm fine with relabeling the region field. If there is a reason to keep region for UK or other adresses, then I'm also fine with adding a new field.
